/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type CloseAndSwapLog = {
  owner: Address;
  market: Address;
  entryPrice: bigint;
  entryPriceExponent: number;
  duration: bigint;
  exitPrice: bigint;
  exitPriceExponent: number;
  sizeAmount: bigint;
  sizeUsd: bigint;
  collateralPrice: bigint;
  collateralPriceExponent: number;
  collateralAmount: bigint;
  profitUsd: bigint;
  lossUsd: bigint;
  feeAmount: bigint;
  feeRebateAmount: bigint;
  exitFeeAmount: bigint;
  receiveCustodyUid: bigint;
  receiveAmount: bigint;
  swapFeeAmount: bigint;
  oracleAccountTime: bigint;
  oracleAccountType: number;
  oracleAccountPrice: bigint;
  oracleAccountPriceExponent: number;
};

export type CloseAndSwapLogArgs = {
  owner: Address;
  market: Address;
  entryPrice: number | bigint;
  entryPriceExponent: number;
  duration: number | bigint;
  exitPrice: number | bigint;
  exitPriceExponent: number;
  sizeAmount: number | bigint;
  sizeUsd: number | bigint;
  collateralPrice: number | bigint;
  collateralPriceExponent: number;
  collateralAmount: number | bigint;
  profitUsd: number | bigint;
  lossUsd: number | bigint;
  feeAmount: number | bigint;
  feeRebateAmount: number | bigint;
  exitFeeAmount: number | bigint;
  receiveCustodyUid: number | bigint;
  receiveAmount: number | bigint;
  swapFeeAmount: number | bigint;
  oracleAccountTime: number | bigint;
  oracleAccountType: number;
  oracleAccountPrice: number | bigint;
  oracleAccountPriceExponent: number;
};

export function getCloseAndSwapLogEncoder(): FixedSizeEncoder<CloseAndSwapLogArgs> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["entryPrice", getU64Encoder()],
    ["entryPriceExponent", getI32Encoder()],
    ["duration", getI64Encoder()],
    ["exitPrice", getU64Encoder()],
    ["exitPriceExponent", getI32Encoder()],
    ["sizeAmount", getU64Encoder()],
    ["sizeUsd", getU64Encoder()],
    ["collateralPrice", getU64Encoder()],
    ["collateralPriceExponent", getI32Encoder()],
    ["collateralAmount", getU64Encoder()],
    ["profitUsd", getU64Encoder()],
    ["lossUsd", getU64Encoder()],
    ["feeAmount", getU64Encoder()],
    ["feeRebateAmount", getU64Encoder()],
    ["exitFeeAmount", getU64Encoder()],
    ["receiveCustodyUid", getU64Encoder()],
    ["receiveAmount", getU64Encoder()],
    ["swapFeeAmount", getU64Encoder()],
    ["oracleAccountTime", getI64Encoder()],
    ["oracleAccountType", getU8Encoder()],
    ["oracleAccountPrice", getU64Encoder()],
    ["oracleAccountPriceExponent", getI32Encoder()],
  ]);
}

export function getCloseAndSwapLogDecoder(): FixedSizeDecoder<CloseAndSwapLog> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["entryPrice", getU64Decoder()],
    ["entryPriceExponent", getI32Decoder()],
    ["duration", getI64Decoder()],
    ["exitPrice", getU64Decoder()],
    ["exitPriceExponent", getI32Decoder()],
    ["sizeAmount", getU64Decoder()],
    ["sizeUsd", getU64Decoder()],
    ["collateralPrice", getU64Decoder()],
    ["collateralPriceExponent", getI32Decoder()],
    ["collateralAmount", getU64Decoder()],
    ["profitUsd", getU64Decoder()],
    ["lossUsd", getU64Decoder()],
    ["feeAmount", getU64Decoder()],
    ["feeRebateAmount", getU64Decoder()],
    ["exitFeeAmount", getU64Decoder()],
    ["receiveCustodyUid", getU64Decoder()],
    ["receiveAmount", getU64Decoder()],
    ["swapFeeAmount", getU64Decoder()],
    ["oracleAccountTime", getI64Decoder()],
    ["oracleAccountType", getU8Decoder()],
    ["oracleAccountPrice", getU64Decoder()],
    ["oracleAccountPriceExponent", getI32Decoder()],
  ]);
}

export function getCloseAndSwapLogCodec(): FixedSizeCodec<
  CloseAndSwapLogArgs,
  CloseAndSwapLog
> {
  return combineCodec(getCloseAndSwapLogEncoder(), getCloseAndSwapLogDecoder());
}
