/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type CollectStakeRewardLog = {
  owner: Address;
  poolName: string;
  rewardAmount: bigint;
  rewardMint: Address;
};

export type CollectStakeRewardLogArgs = {
  owner: Address;
  poolName: string;
  rewardAmount: number | bigint;
  rewardMint: Address;
};

export function getCollectStakeRewardLogEncoder(): Encoder<CollectStakeRewardLogArgs> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["poolName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["rewardAmount", getU64Encoder()],
    ["rewardMint", getAddressEncoder()],
  ]);
}

export function getCollectStakeRewardLogDecoder(): Decoder<CollectStakeRewardLog> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["poolName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["rewardAmount", getU64Decoder()],
    ["rewardMint", getAddressDecoder()],
  ]);
}

export function getCollectStakeRewardLogCodec(): Codec<
  CollectStakeRewardLogArgs,
  CollectStakeRewardLog
> {
  return combineCodec(
    getCollectStakeRewardLogEncoder(),
    getCollectStakeRewardLogDecoder(),
  );
}
