/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type CompoundingTokenData = {
  lpPrice: bigint;
  compoundingPrice: bigint;
  ratios: Array<bigint>;
};

export type CompoundingTokenDataArgs = {
  lpPrice: number | bigint;
  compoundingPrice: number | bigint;
  ratios: Array<number | bigint>;
};

export function getCompoundingTokenDataEncoder(): Encoder<CompoundingTokenDataArgs> {
  return getStructEncoder([
    ["lpPrice", getU64Encoder()],
    ["compoundingPrice", getU64Encoder()],
    ["ratios", getArrayEncoder(getU64Encoder())],
  ]);
}

export function getCompoundingTokenDataDecoder(): Decoder<CompoundingTokenData> {
  return getStructDecoder([
    ["lpPrice", getU64Decoder()],
    ["compoundingPrice", getU64Decoder()],
    ["ratios", getArrayDecoder(getU64Decoder())],
  ]);
}

export function getCompoundingTokenDataCodec(): Codec<
  CompoundingTokenDataArgs,
  CompoundingTokenData
> {
  return combineCodec(
    getCompoundingTokenDataEncoder(),
    getCompoundingTokenDataDecoder(),
  );
}
