/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ExecuteLimitWithSwapLogUSDv1 = {
  owner: Address;
  market: Address;
  tradeId: bigint;
  entryPrice: bigint;
  entryPriceExponent: number;
  deltaSizeAmount: bigint;
  deltaSizeUsd: bigint;
  reserveCustodyUid: number;
  reservePrice: bigint;
  reservePriceExponent: number;
  reserveAmount: bigint;
  deltaCollateralUsd: bigint;
  feeUsd: bigint;
  rebateUsd: bigint;
  discountUsd: bigint;
  entryFeeUsd: bigint;
  oracleAccountTime: bigint;
  oracleAccountType: number;
  oracleAccountPrice: bigint;
  oracleAccountPriceExponent: number;
  limitPrice: bigint;
  limitPriceExponent: number;
  padding: Array<bigint>;
};

export type ExecuteLimitWithSwapLogUSDv1Args = {
  owner: Address;
  market: Address;
  tradeId: number | bigint;
  entryPrice: number | bigint;
  entryPriceExponent: number;
  deltaSizeAmount: number | bigint;
  deltaSizeUsd: number | bigint;
  reserveCustodyUid: number;
  reservePrice: number | bigint;
  reservePriceExponent: number;
  reserveAmount: number | bigint;
  deltaCollateralUsd: number | bigint;
  feeUsd: number | bigint;
  rebateUsd: number | bigint;
  discountUsd: number | bigint;
  entryFeeUsd: number | bigint;
  oracleAccountTime: number | bigint;
  oracleAccountType: number;
  oracleAccountPrice: number | bigint;
  oracleAccountPriceExponent: number;
  limitPrice: number | bigint;
  limitPriceExponent: number;
  padding: Array<number | bigint>;
};

export function getExecuteLimitWithSwapLogUSDv1Encoder(): FixedSizeEncoder<ExecuteLimitWithSwapLogUSDv1Args> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["tradeId", getI64Encoder()],
    ["entryPrice", getU64Encoder()],
    ["entryPriceExponent", getI32Encoder()],
    ["deltaSizeAmount", getU64Encoder()],
    ["deltaSizeUsd", getU64Encoder()],
    ["reserveCustodyUid", getU8Encoder()],
    ["reservePrice", getU64Encoder()],
    ["reservePriceExponent", getI32Encoder()],
    ["reserveAmount", getU64Encoder()],
    ["deltaCollateralUsd", getU64Encoder()],
    ["feeUsd", getU64Encoder()],
    ["rebateUsd", getU64Encoder()],
    ["discountUsd", getU64Encoder()],
    ["entryFeeUsd", getU64Encoder()],
    ["oracleAccountTime", getI64Encoder()],
    ["oracleAccountType", getU8Encoder()],
    ["oracleAccountPrice", getU64Encoder()],
    ["oracleAccountPriceExponent", getI32Encoder()],
    ["limitPrice", getU64Encoder()],
    ["limitPriceExponent", getI32Encoder()],
    ["padding", getArrayEncoder(getU64Encoder(), { size: 4 })],
  ]);
}

export function getExecuteLimitWithSwapLogUSDv1Decoder(): FixedSizeDecoder<ExecuteLimitWithSwapLogUSDv1> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["tradeId", getI64Decoder()],
    ["entryPrice", getU64Decoder()],
    ["entryPriceExponent", getI32Decoder()],
    ["deltaSizeAmount", getU64Decoder()],
    ["deltaSizeUsd", getU64Decoder()],
    ["reserveCustodyUid", getU8Decoder()],
    ["reservePrice", getU64Decoder()],
    ["reservePriceExponent", getI32Decoder()],
    ["reserveAmount", getU64Decoder()],
    ["deltaCollateralUsd", getU64Decoder()],
    ["feeUsd", getU64Decoder()],
    ["rebateUsd", getU64Decoder()],
    ["discountUsd", getU64Decoder()],
    ["entryFeeUsd", getU64Decoder()],
    ["oracleAccountTime", getI64Decoder()],
    ["oracleAccountType", getU8Decoder()],
    ["oracleAccountPrice", getU64Decoder()],
    ["oracleAccountPriceExponent", getI32Decoder()],
    ["limitPrice", getU64Decoder()],
    ["limitPriceExponent", getI32Decoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 4 })],
  ]);
}

export function getExecuteLimitWithSwapLogUSDv1Codec(): FixedSizeCodec<
  ExecuteLimitWithSwapLogUSDv1Args,
  ExecuteLimitWithSwapLogUSDv1
> {
  return combineCodec(
    getExecuteLimitWithSwapLogUSDv1Encoder(),
    getExecuteLimitWithSwapLogUSDv1Decoder(),
  );
}
