/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum FeesMode {
  Fixed,
  Linear,
}

export type FeesModeArgs = FeesMode;

export function getFeesModeEncoder(): FixedSizeEncoder<FeesModeArgs> {
  return getEnumEncoder(FeesMode);
}

export function getFeesModeDecoder(): FixedSizeDecoder<FeesMode> {
  return getEnumDecoder(FeesMode);
}

export function getFeesModeCodec(): FixedSizeCodec<FeesModeArgs, FeesMode> {
  return combineCodec(getFeesModeEncoder(), getFeesModeDecoder());
}
