/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ForceSettleTriggerOrderLog = {
  admin: Address;
  owner: Address;
  market: Address;
  triggerOrdersCancelled: number;
  padding: Array<bigint>;
};

export type ForceSettleTriggerOrderLogArgs = {
  admin: Address;
  owner: Address;
  market: Address;
  triggerOrdersCancelled: number;
  padding: Array<number | bigint>;
};

export function getForceSettleTriggerOrderLogEncoder(): FixedSizeEncoder<ForceSettleTriggerOrderLogArgs> {
  return getStructEncoder([
    ["admin", getAddressEncoder()],
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["triggerOrdersCancelled", getU8Encoder()],
    ["padding", getArrayEncoder(getU64Encoder(), { size: 4 })],
  ]);
}

export function getForceSettleTriggerOrderLogDecoder(): FixedSizeDecoder<ForceSettleTriggerOrderLog> {
  return getStructDecoder([
    ["admin", getAddressDecoder()],
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["triggerOrdersCancelled", getU8Decoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 4 })],
  ]);
}

export function getForceSettleTriggerOrderLogCodec(): FixedSizeCodec<
  ForceSettleTriggerOrderLogArgs,
  ForceSettleTriggerOrderLog
> {
  return combineCodec(
    getForceSettleTriggerOrderLogEncoder(),
    getForceSettleTriggerOrderLogDecoder(),
  );
}
