/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type LiquidateLogV2 = {
  owner: Address;
  market: Address;
  price: bigint;
  priceExponent: number;
  sizeUsd: bigint;
  sizeAmount: bigint;
  feeAmount: bigint;
};

export type LiquidateLogV2Args = {
  owner: Address;
  market: Address;
  price: number | bigint;
  priceExponent: number;
  sizeUsd: number | bigint;
  sizeAmount: number | bigint;
  feeAmount: number | bigint;
};

export function getLiquidateLogV2Encoder(): FixedSizeEncoder<LiquidateLogV2Args> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["price", getU64Encoder()],
    ["priceExponent", getI32Encoder()],
    ["sizeUsd", getU64Encoder()],
    ["sizeAmount", getU64Encoder()],
    ["feeAmount", getU64Encoder()],
  ]);
}

export function getLiquidateLogV2Decoder(): FixedSizeDecoder<LiquidateLogV2> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["price", getU64Decoder()],
    ["priceExponent", getI32Decoder()],
    ["sizeUsd", getU64Decoder()],
    ["sizeAmount", getU64Decoder()],
    ["feeAmount", getU64Decoder()],
  ]);
}

export function getLiquidateLogV2Codec(): FixedSizeCodec<
  LiquidateLogV2Args,
  LiquidateLogV2
> {
  return combineCodec(getLiquidateLogV2Encoder(), getLiquidateLogV2Decoder());
}
