/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MigrateMarketPositionLog = {
  owner: Address;
  market: Address;
  position: Address;
  entryPrice: bigint;
  entryPriceExponent: number;
  sizeAmount: bigint;
  sizeUsd: bigint;
  collateralAmount: bigint;
  collateralUsd: bigint;
  collateralPrice: bigint;
  collateralPriceExponent: number;
};

export type MigrateMarketPositionLogArgs = {
  owner: Address;
  market: Address;
  position: Address;
  entryPrice: number | bigint;
  entryPriceExponent: number;
  sizeAmount: number | bigint;
  sizeUsd: number | bigint;
  collateralAmount: number | bigint;
  collateralUsd: number | bigint;
  collateralPrice: number | bigint;
  collateralPriceExponent: number;
};

export function getMigrateMarketPositionLogEncoder(): FixedSizeEncoder<MigrateMarketPositionLogArgs> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["position", getAddressEncoder()],
    ["entryPrice", getU64Encoder()],
    ["entryPriceExponent", getI32Encoder()],
    ["sizeAmount", getU64Encoder()],
    ["sizeUsd", getU64Encoder()],
    ["collateralAmount", getU64Encoder()],
    ["collateralUsd", getU64Encoder()],
    ["collateralPrice", getU64Encoder()],
    ["collateralPriceExponent", getI32Encoder()],
  ]);
}

export function getMigrateMarketPositionLogDecoder(): FixedSizeDecoder<MigrateMarketPositionLog> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["position", getAddressDecoder()],
    ["entryPrice", getU64Decoder()],
    ["entryPriceExponent", getI32Decoder()],
    ["sizeAmount", getU64Decoder()],
    ["sizeUsd", getU64Decoder()],
    ["collateralAmount", getU64Decoder()],
    ["collateralUsd", getU64Decoder()],
    ["collateralPrice", getU64Decoder()],
    ["collateralPriceExponent", getI32Decoder()],
  ]);
}

export function getMigrateMarketPositionLogCodec(): FixedSizeCodec<
  MigrateMarketPositionLogArgs,
  MigrateMarketPositionLog
> {
  return combineCodec(
    getMigrateMarketPositionLogEncoder(),
    getMigrateMarketPositionLogDecoder(),
  );
}
