/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type OpenPositionLogV3 = {
  owner: Address;
  market: Address;
  entryPrice: bigint;
  entryPriceExponent: number;
  sizeAmount: bigint;
  sizeUsd: bigint;
  collateralAmount: bigint;
  collateralUsd: bigint;
  feeAmount: bigint;
  feeRebateAmount: bigint;
  oracleAccountTime: bigint;
  oracleAccountType: number;
  oracleAccountPrice: bigint;
  oracleAccountPriceExponent: number;
};

export type OpenPositionLogV3Args = {
  owner: Address;
  market: Address;
  entryPrice: number | bigint;
  entryPriceExponent: number;
  sizeAmount: number | bigint;
  sizeUsd: number | bigint;
  collateralAmount: number | bigint;
  collateralUsd: number | bigint;
  feeAmount: number | bigint;
  feeRebateAmount: number | bigint;
  oracleAccountTime: number | bigint;
  oracleAccountType: number;
  oracleAccountPrice: number | bigint;
  oracleAccountPriceExponent: number;
};

export function getOpenPositionLogV3Encoder(): FixedSizeEncoder<OpenPositionLogV3Args> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["entryPrice", getU64Encoder()],
    ["entryPriceExponent", getI32Encoder()],
    ["sizeAmount", getU64Encoder()],
    ["sizeUsd", getU64Encoder()],
    ["collateralAmount", getU64Encoder()],
    ["collateralUsd", getU64Encoder()],
    ["feeAmount", getU64Encoder()],
    ["feeRebateAmount", getU64Encoder()],
    ["oracleAccountTime", getI64Encoder()],
    ["oracleAccountType", getU8Encoder()],
    ["oracleAccountPrice", getU64Encoder()],
    ["oracleAccountPriceExponent", getI32Encoder()],
  ]);
}

export function getOpenPositionLogV3Decoder(): FixedSizeDecoder<OpenPositionLogV3> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["entryPrice", getU64Decoder()],
    ["entryPriceExponent", getI32Decoder()],
    ["sizeAmount", getU64Decoder()],
    ["sizeUsd", getU64Decoder()],
    ["collateralAmount", getU64Decoder()],
    ["collateralUsd", getU64Decoder()],
    ["feeAmount", getU64Decoder()],
    ["feeRebateAmount", getU64Decoder()],
    ["oracleAccountTime", getI64Decoder()],
    ["oracleAccountType", getU8Decoder()],
    ["oracleAccountPrice", getU64Decoder()],
    ["oracleAccountPriceExponent", getI32Decoder()],
  ]);
}

export function getOpenPositionLogV3Codec(): FixedSizeCodec<
  OpenPositionLogV3Args,
  OpenPositionLogV3
> {
  return combineCodec(
    getOpenPositionLogV3Encoder(),
    getOpenPositionLogV3Decoder(),
  );
}
