/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PricingParams = {
  tradeSpreadMin: bigint;
  tradeSpreadMax: bigint;
  swapSpread: bigint;
  minInitLeverage: number;
  minInitDegenLeverage: number;
  maxInitLeverage: number;
  maxInitDegenLeverage: number;
  maxLeverage: number;
  maxDegenLeverage: number;
  minCollateralUsd: number;
  minDegenCollateralUsd: number;
  delaySeconds: bigint;
  maxUtilization: number;
  degenPositionFactor: number;
  degenExposureFactor: number;
  maxPositionSizeUsd: bigint;
  maxExposureUsd: bigint;
};

export type PricingParamsArgs = {
  tradeSpreadMin: number | bigint;
  tradeSpreadMax: number | bigint;
  swapSpread: number | bigint;
  minInitLeverage: number;
  minInitDegenLeverage: number;
  maxInitLeverage: number;
  maxInitDegenLeverage: number;
  maxLeverage: number;
  maxDegenLeverage: number;
  minCollateralUsd: number;
  minDegenCollateralUsd: number;
  delaySeconds: number | bigint;
  maxUtilization: number;
  degenPositionFactor: number;
  degenExposureFactor: number;
  maxPositionSizeUsd: number | bigint;
  maxExposureUsd: number | bigint;
};

export function getPricingParamsEncoder(): FixedSizeEncoder<PricingParamsArgs> {
  return getStructEncoder([
    ["tradeSpreadMin", getU64Encoder()],
    ["tradeSpreadMax", getU64Encoder()],
    ["swapSpread", getU64Encoder()],
    ["minInitLeverage", getU32Encoder()],
    ["minInitDegenLeverage", getU32Encoder()],
    ["maxInitLeverage", getU32Encoder()],
    ["maxInitDegenLeverage", getU32Encoder()],
    ["maxLeverage", getU32Encoder()],
    ["maxDegenLeverage", getU32Encoder()],
    ["minCollateralUsd", getU32Encoder()],
    ["minDegenCollateralUsd", getU32Encoder()],
    ["delaySeconds", getI64Encoder()],
    ["maxUtilization", getU32Encoder()],
    ["degenPositionFactor", getU16Encoder()],
    ["degenExposureFactor", getU16Encoder()],
    ["maxPositionSizeUsd", getU64Encoder()],
    ["maxExposureUsd", getU64Encoder()],
  ]);
}

export function getPricingParamsDecoder(): FixedSizeDecoder<PricingParams> {
  return getStructDecoder([
    ["tradeSpreadMin", getU64Decoder()],
    ["tradeSpreadMax", getU64Decoder()],
    ["swapSpread", getU64Decoder()],
    ["minInitLeverage", getU32Decoder()],
    ["minInitDegenLeverage", getU32Decoder()],
    ["maxInitLeverage", getU32Decoder()],
    ["maxInitDegenLeverage", getU32Decoder()],
    ["maxLeverage", getU32Decoder()],
    ["maxDegenLeverage", getU32Decoder()],
    ["minCollateralUsd", getU32Decoder()],
    ["minDegenCollateralUsd", getU32Decoder()],
    ["delaySeconds", getI64Decoder()],
    ["maxUtilization", getU32Decoder()],
    ["degenPositionFactor", getU16Decoder()],
    ["degenExposureFactor", getU16Decoder()],
    ["maxPositionSizeUsd", getU64Decoder()],
    ["maxExposureUsd", getU64Decoder()],
  ]);
}

export function getPricingParamsCodec(): FixedSizeCodec<
  PricingParamsArgs,
  PricingParams
> {
  return combineCodec(getPricingParamsEncoder(), getPricingParamsDecoder());
}
