/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ReferralRebateLog = {
  tokenStake: Address;
  owner: Address;
  rebateUsd: bigint;
  volumeUsd: bigint;
  voltagePointsType: number;
  padding: Array<bigint>;
};

export type ReferralRebateLogArgs = {
  tokenStake: Address;
  owner: Address;
  rebateUsd: number | bigint;
  volumeUsd: number | bigint;
  voltagePointsType: number;
  padding: Array<number | bigint>;
};

export function getReferralRebateLogEncoder(): FixedSizeEncoder<ReferralRebateLogArgs> {
  return getStructEncoder([
    ["tokenStake", getAddressEncoder()],
    ["owner", getAddressEncoder()],
    ["rebateUsd", getU64Encoder()],
    ["volumeUsd", getU64Encoder()],
    ["voltagePointsType", getU8Encoder()],
    ["padding", getArrayEncoder(getU64Encoder(), { size: 4 })],
  ]);
}

export function getReferralRebateLogDecoder(): FixedSizeDecoder<ReferralRebateLog> {
  return getStructDecoder([
    ["tokenStake", getAddressDecoder()],
    ["owner", getAddressDecoder()],
    ["rebateUsd", getU64Decoder()],
    ["volumeUsd", getU64Decoder()],
    ["voltagePointsType", getU8Decoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 4 })],
  ]);
}

export function getReferralRebateLogCodec(): FixedSizeCodec<
  ReferralRebateLogArgs,
  ReferralRebateLog
> {
  return combineCodec(
    getReferralRebateLogEncoder(),
    getReferralRebateLogDecoder(),
  );
}
