/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const REBATE_VAULT_DISCRIMINATOR = new Uint8Array([
  207, 58, 186, 112, 64, 20, 188, 212,
]);

export function getRebateVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REBATE_VAULT_DISCRIMINATOR,
  );
}

export type RebateVault = {
  discriminator: ReadonlyUint8Array;
  key: Address;
  tokenAccount: Address;
  isInitialized: boolean;
  allowPayout: boolean;
  bump: number;
  tokenAccountBump: number;
  availableUsd: bigint;
  availableAmount: bigint;
  padding: Array<bigint>;
};

export type RebateVaultArgs = {
  key: Address;
  tokenAccount: Address;
  isInitialized: boolean;
  allowPayout: boolean;
  bump: number;
  tokenAccountBump: number;
  availableUsd: number | bigint;
  availableAmount: number | bigint;
  padding: Array<number | bigint>;
};

/** Gets the encoder for {@link RebateVaultArgs} account data. */
export function getRebateVaultEncoder(): FixedSizeEncoder<RebateVaultArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["key", getAddressEncoder()],
      ["tokenAccount", getAddressEncoder()],
      ["isInitialized", getBooleanEncoder()],
      ["allowPayout", getBooleanEncoder()],
      ["bump", getU8Encoder()],
      ["tokenAccountBump", getU8Encoder()],
      ["availableUsd", getU64Encoder()],
      ["availableAmount", getU64Encoder()],
      ["padding", getArrayEncoder(getU64Encoder(), { size: 4 })],
    ]),
    (value) => ({ ...value, discriminator: REBATE_VAULT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link RebateVault} account data. */
export function getRebateVaultDecoder(): FixedSizeDecoder<RebateVault> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["key", getAddressDecoder()],
    ["tokenAccount", getAddressDecoder()],
    ["isInitialized", getBooleanDecoder()],
    ["allowPayout", getBooleanDecoder()],
    ["bump", getU8Decoder()],
    ["tokenAccountBump", getU8Decoder()],
    ["availableUsd", getU64Decoder()],
    ["availableAmount", getU64Decoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 4 })],
  ]);
}

/** Gets the codec for {@link RebateVault} account data. */
export function getRebateVaultCodec(): FixedSizeCodec<
  RebateVaultArgs,
  RebateVault
> {
  return combineCodec(getRebateVaultEncoder(), getRebateVaultDecoder());
}

export function decodeRebateVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RebateVault, TAddress>;
export function decodeRebateVault<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RebateVault, TAddress>;
export function decodeRebateVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<RebateVault, TAddress> | MaybeAccount<RebateVault, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRebateVaultDecoder(),
  );
}

export async function fetchRebateVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RebateVault, TAddress>> {
  const maybeAccount = await fetchMaybeRebateVault(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRebateVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RebateVault, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRebateVault(maybeAccount);
}

export async function fetchAllRebateVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<RebateVault>[]> {
  const maybeAccounts = await fetchAllMaybeRebateVault(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRebateVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RebateVault>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeRebateVault(maybeAccount));
}

export function getRebateVaultSize(): number {
  return 124;
}
