/**
 * SIGIL_ERROR_CODES — programmatic error discriminants.
 *
 * Convention: `SIGIL_ERROR__<DOMAIN>__<DESCRIPTOR>` (kit-style double-underscore).
 * Matches `@solana/kit` `SOLANA_ERROR__*` convention so contributors fluent in
 * one are immediately fluent in the other.
 *
 * Single canonical discriminant per `SigilError` instance — no dual `.code` /
 * `.sigilCode` surface. Legacy numeric codes (X402 7024-7028) are preserved as
 * `legacyNumericCode` getters on the leaf classes for one-minor migration ramp.
 */

// Shield domain — policy enforcement
export const SIGIL_ERROR__SHIELD__POLICY_DENIED =
  "SIGIL_ERROR__SHIELD__POLICY_DENIED" as const;
export const SIGIL_ERROR__SHIELD__CONFIG_INVALID =
  "SIGIL_ERROR__SHIELD__CONFIG_INVALID" as const;
export const SIGIL_ERROR__SHIELD__RATE_LIMIT_EXCEEDED =
  "SIGIL_ERROR__SHIELD__RATE_LIMIT_EXCEEDED" as const;
export const SIGIL_ERROR__SHIELD__SESSION_BINDING =
  "SIGIL_ERROR__SHIELD__SESSION_BINDING" as const;

// TEE domain — attestation + custody
export const SIGIL_ERROR__TEE__ATTESTATION_FAILED =
  "SIGIL_ERROR__TEE__ATTESTATION_FAILED" as const;
export const SIGIL_ERROR__TEE__CERT_CHAIN_INVALID =
  "SIGIL_ERROR__TEE__CERT_CHAIN_INVALID" as const;
export const SIGIL_ERROR__TEE__PCR_MISMATCH =
  "SIGIL_ERROR__TEE__PCR_MISMATCH" as const;

// Compose domain — DeFi instruction composition
export const SIGIL_ERROR__COMPOSE__MISSING_PARAM =
  "SIGIL_ERROR__COMPOSE__MISSING_PARAM" as const;
export const SIGIL_ERROR__COMPOSE__INVALID_BIGINT =
  "SIGIL_ERROR__COMPOSE__INVALID_BIGINT" as const;
export const SIGIL_ERROR__COMPOSE__UNSUPPORTED_ACTION =
  "SIGIL_ERROR__COMPOSE__UNSUPPORTED_ACTION" as const;

// x402 domain — HTTP 402 payments
export const SIGIL_ERROR__X402__HEADER_MALFORMED =
  "SIGIL_ERROR__X402__HEADER_MALFORMED" as const;
export const SIGIL_ERROR__X402__PAYMENT_FAILED =
  "SIGIL_ERROR__X402__PAYMENT_FAILED" as const;
export const SIGIL_ERROR__X402__UNSUPPORTED =
  "SIGIL_ERROR__X402__UNSUPPORTED" as const;
export const SIGIL_ERROR__X402__DESTINATION_BLOCKED =
  "SIGIL_ERROR__X402__DESTINATION_BLOCKED" as const;
export const SIGIL_ERROR__X402__REPLAY = "SIGIL_ERROR__X402__REPLAY" as const;

// SDK domain — config + runtime + state errors raised from sdk/kit/src
export const SIGIL_ERROR__SDK__INVALID_CONFIG =
  "SIGIL_ERROR__SDK__INVALID_CONFIG" as const;
export const SIGIL_ERROR__SDK__INVALID_PARAMS =
  "SIGIL_ERROR__SDK__INVALID_PARAMS" as const;
export const SIGIL_ERROR__SDK__INVALID_NETWORK =
  "SIGIL_ERROR__SDK__INVALID_NETWORK" as const;
export const SIGIL_ERROR__SDK__INVALID_AMOUNT =
  "SIGIL_ERROR__SDK__INVALID_AMOUNT" as const;
export const SIGIL_ERROR__SDK__INVALID_CAPABILITY =
  "SIGIL_ERROR__SDK__INVALID_CAPABILITY" as const;
export const SIGIL_ERROR__SDK__INVALID_ACTION_TYPE =
  "SIGIL_ERROR__SDK__INVALID_ACTION_TYPE" as const;
export const SIGIL_ERROR__SDK__OWNER_AGENT_COLLISION =
  "SIGIL_ERROR__SDK__OWNER_AGENT_COLLISION" as const;
export const SIGIL_ERROR__SDK__VAULT_NOT_FOUND =
  "SIGIL_ERROR__SDK__VAULT_NOT_FOUND" as const;
export const SIGIL_ERROR__SDK__VAULT_INACTIVE =
  "SIGIL_ERROR__SDK__VAULT_INACTIVE" as const;
export const SIGIL_ERROR__SDK__VAULT_SLOTS_EXHAUSTED =
  "SIGIL_ERROR__SDK__VAULT_SLOTS_EXHAUSTED" as const;
export const SIGIL_ERROR__SDK__POLICY_NOT_FOUND =
  "SIGIL_ERROR__SDK__POLICY_NOT_FOUND" as const;
export const SIGIL_ERROR__SDK__AGENT_NOT_REGISTERED =
  "SIGIL_ERROR__SDK__AGENT_NOT_REGISTERED" as const;
export const SIGIL_ERROR__SDK__AGENT_PAUSED =
  "SIGIL_ERROR__SDK__AGENT_PAUSED" as const;
export const SIGIL_ERROR__SDK__AGENT_ZERO_CAPABILITY =
  "SIGIL_ERROR__SDK__AGENT_ZERO_CAPABILITY" as const;
export const SIGIL_ERROR__SDK__SIGNER_INVALID =
  "SIGIL_ERROR__SDK__SIGNER_INVALID" as const;
export const SIGIL_ERROR__SDK__SIGNATURE_INVALID =
  "SIGIL_ERROR__SDK__SIGNATURE_INVALID" as const;
export const SIGIL_ERROR__SDK__SPL_TOKEN_OP_BLOCKED =
  "SIGIL_ERROR__SDK__SPL_TOKEN_OP_BLOCKED" as const;
export const SIGIL_ERROR__SDK__PROTOCOL_NOT_ALLOWED =
  "SIGIL_ERROR__SDK__PROTOCOL_NOT_ALLOWED" as const;
export const SIGIL_ERROR__SDK__PROTOCOL_NOT_TARGETED =
  "SIGIL_ERROR__SDK__PROTOCOL_NOT_TARGETED" as const;
export const SIGIL_ERROR__SDK__INSTRUCTION_COUNT =
  "SIGIL_ERROR__SDK__INSTRUCTION_COUNT" as const;
export const SIGIL_ERROR__SDK__CAP_EXCEEDED =
  "SIGIL_ERROR__SDK__CAP_EXCEEDED" as const;
export const SIGIL_ERROR__SDK__ATA_NON_CANONICAL =
  "SIGIL_ERROR__SDK__ATA_NON_CANONICAL" as const;
export const SIGIL_ERROR__SDK__ALT_INTEGRITY =
  "SIGIL_ERROR__SDK__ALT_INTEGRITY" as const;
export const SIGIL_ERROR__SDK__ALT_NOT_DEPLOYED =
  "SIGIL_ERROR__SDK__ALT_NOT_DEPLOYED" as const;
export const SIGIL_ERROR__SDK__SEAL_FAILED =
  "SIGIL_ERROR__SDK__SEAL_FAILED" as const;
/** SealHooks#onBeforeBuild returned `{ skipSeal: true }` — clean abort before any RPC. */
export const SIGIL_ERROR__SDK__HOOK_ABORTED =
  "SIGIL_ERROR__SDK__HOOK_ABORTED" as const;
/** A SigilPolicyPlugin rejected the operation via `{ allow: false, reason }`. */
export const SIGIL_ERROR__SDK__PLUGIN_REJECTED =
  "SIGIL_ERROR__SDK__PLUGIN_REJECTED" as const;
/** A SigilVault method that requires an owner signer was called on an agent-only handle. */
export const SIGIL_ERROR__SDK__OWNER_REQUIRED =
  "SIGIL_ERROR__SDK__OWNER_REQUIRED" as const;
export const SIGIL_ERROR__SDK__UNKNOWN = "SIGIL_ERROR__SDK__UNKNOWN" as const;

// RPC domain — network + transaction lifecycle
export const SIGIL_ERROR__RPC__TX_FAILED =
  "SIGIL_ERROR__RPC__TX_FAILED" as const;
export const SIGIL_ERROR__RPC__CONFIRMATION_TIMEOUT =
  "SIGIL_ERROR__RPC__CONFIRMATION_TIMEOUT" as const;
export const SIGIL_ERROR__RPC__SIMULATION_FAILED =
  "SIGIL_ERROR__RPC__SIMULATION_FAILED" as const;
export const SIGIL_ERROR__RPC__DRAIN_DETECTED =
  "SIGIL_ERROR__RPC__DRAIN_DETECTED" as const;
export const SIGIL_ERROR__RPC__TX_TOO_LARGE =
  "SIGIL_ERROR__RPC__TX_TOO_LARGE" as const;
export const SIGIL_ERROR__RPC__RATE_LIMITED =
  "SIGIL_ERROR__RPC__RATE_LIMITED" as const;
export const SIGIL_ERROR__RPC__INSTRUCTION_REQUIRED =
  "SIGIL_ERROR__RPC__INSTRUCTION_REQUIRED" as const;

// Program domain — placeholder for full Anchor 6000-6084 mapping (deferred to follow-up PR)
export const SIGIL_ERROR__PROGRAM__GENERIC =
  "SIGIL_ERROR__PROGRAM__GENERIC" as const;

/** Discriminated union of all error code constants. */
export type SigilErrorCode =
  | typeof SIGIL_ERROR__SHIELD__POLICY_DENIED
  | typeof SIGIL_ERROR__SHIELD__CONFIG_INVALID
  | typeof SIGIL_ERROR__SHIELD__RATE_LIMIT_EXCEEDED
  | typeof SIGIL_ERROR__SHIELD__SESSION_BINDING
  | typeof SIGIL_ERROR__TEE__ATTESTATION_FAILED
  | typeof SIGIL_ERROR__TEE__CERT_CHAIN_INVALID
  | typeof SIGIL_ERROR__TEE__PCR_MISMATCH
  | typeof SIGIL_ERROR__COMPOSE__MISSING_PARAM
  | typeof SIGIL_ERROR__COMPOSE__INVALID_BIGINT
  | typeof SIGIL_ERROR__COMPOSE__UNSUPPORTED_ACTION
  | typeof SIGIL_ERROR__X402__HEADER_MALFORMED
  | typeof SIGIL_ERROR__X402__PAYMENT_FAILED
  | typeof SIGIL_ERROR__X402__UNSUPPORTED
  | typeof SIGIL_ERROR__X402__DESTINATION_BLOCKED
  | typeof SIGIL_ERROR__X402__REPLAY
  | typeof SIGIL_ERROR__SDK__INVALID_CONFIG
  | typeof SIGIL_ERROR__SDK__INVALID_PARAMS
  | typeof SIGIL_ERROR__SDK__INVALID_NETWORK
  | typeof SIGIL_ERROR__SDK__INVALID_AMOUNT
  | typeof SIGIL_ERROR__SDK__INVALID_CAPABILITY
  | typeof SIGIL_ERROR__SDK__INVALID_ACTION_TYPE
  | typeof SIGIL_ERROR__SDK__OWNER_AGENT_COLLISION
  | typeof SIGIL_ERROR__SDK__VAULT_NOT_FOUND
  | typeof SIGIL_ERROR__SDK__VAULT_INACTIVE
  | typeof SIGIL_ERROR__SDK__VAULT_SLOTS_EXHAUSTED
  | typeof SIGIL_ERROR__SDK__POLICY_NOT_FOUND
  | typeof SIGIL_ERROR__SDK__AGENT_NOT_REGISTERED
  | typeof SIGIL_ERROR__SDK__AGENT_PAUSED
  | typeof SIGIL_ERROR__SDK__AGENT_ZERO_CAPABILITY
  | typeof SIGIL_ERROR__SDK__SIGNER_INVALID
  | typeof SIGIL_ERROR__SDK__SIGNATURE_INVALID
  | typeof SIGIL_ERROR__SDK__SPL_TOKEN_OP_BLOCKED
  | typeof SIGIL_ERROR__SDK__PROTOCOL_NOT_ALLOWED
  | typeof SIGIL_ERROR__SDK__PROTOCOL_NOT_TARGETED
  | typeof SIGIL_ERROR__SDK__INSTRUCTION_COUNT
  | typeof SIGIL_ERROR__SDK__CAP_EXCEEDED
  | typeof SIGIL_ERROR__SDK__ATA_NON_CANONICAL
  | typeof SIGIL_ERROR__SDK__ALT_INTEGRITY
  | typeof SIGIL_ERROR__SDK__ALT_NOT_DEPLOYED
  | typeof SIGIL_ERROR__SDK__SEAL_FAILED
  | typeof SIGIL_ERROR__SDK__HOOK_ABORTED
  | typeof SIGIL_ERROR__SDK__PLUGIN_REJECTED
  | typeof SIGIL_ERROR__SDK__OWNER_REQUIRED
  | typeof SIGIL_ERROR__SDK__UNKNOWN
  | typeof SIGIL_ERROR__RPC__TX_FAILED
  | typeof SIGIL_ERROR__RPC__CONFIRMATION_TIMEOUT
  | typeof SIGIL_ERROR__RPC__SIMULATION_FAILED
  | typeof SIGIL_ERROR__RPC__DRAIN_DETECTED
  | typeof SIGIL_ERROR__RPC__TX_TOO_LARGE
  | typeof SIGIL_ERROR__RPC__RATE_LIMITED
  | typeof SIGIL_ERROR__RPC__INSTRUCTION_REQUIRED
  | typeof SIGIL_ERROR__PROGRAM__GENERIC;

/** Per-domain code subsets — used by domain class generic narrowing. */
export type SigilShieldErrorCode =
  | typeof SIGIL_ERROR__SHIELD__POLICY_DENIED
  | typeof SIGIL_ERROR__SHIELD__CONFIG_INVALID
  | typeof SIGIL_ERROR__SHIELD__RATE_LIMIT_EXCEEDED
  | typeof SIGIL_ERROR__SHIELD__SESSION_BINDING;

export type SigilTeeErrorCode =
  | typeof SIGIL_ERROR__TEE__ATTESTATION_FAILED
  | typeof SIGIL_ERROR__TEE__CERT_CHAIN_INVALID
  | typeof SIGIL_ERROR__TEE__PCR_MISMATCH;

export type SigilComposeErrorCode =
  | typeof SIGIL_ERROR__COMPOSE__MISSING_PARAM
  | typeof SIGIL_ERROR__COMPOSE__INVALID_BIGINT
  | typeof SIGIL_ERROR__COMPOSE__UNSUPPORTED_ACTION;

export type SigilX402ErrorCode =
  | typeof SIGIL_ERROR__X402__HEADER_MALFORMED
  | typeof SIGIL_ERROR__X402__PAYMENT_FAILED
  | typeof SIGIL_ERROR__X402__UNSUPPORTED
  | typeof SIGIL_ERROR__X402__DESTINATION_BLOCKED
  | typeof SIGIL_ERROR__X402__REPLAY;

export type SigilSdkErrorCode =
  | typeof SIGIL_ERROR__SDK__INVALID_CONFIG
  | typeof SIGIL_ERROR__SDK__INVALID_PARAMS
  | typeof SIGIL_ERROR__SDK__INVALID_NETWORK
  | typeof SIGIL_ERROR__SDK__INVALID_AMOUNT
  | typeof SIGIL_ERROR__SDK__INVALID_CAPABILITY
  | typeof SIGIL_ERROR__SDK__INVALID_ACTION_TYPE
  | typeof SIGIL_ERROR__SDK__OWNER_AGENT_COLLISION
  | typeof SIGIL_ERROR__SDK__VAULT_NOT_FOUND
  | typeof SIGIL_ERROR__SDK__VAULT_INACTIVE
  | typeof SIGIL_ERROR__SDK__VAULT_SLOTS_EXHAUSTED
  | typeof SIGIL_ERROR__SDK__POLICY_NOT_FOUND
  | typeof SIGIL_ERROR__SDK__AGENT_NOT_REGISTERED
  | typeof SIGIL_ERROR__SDK__AGENT_PAUSED
  | typeof SIGIL_ERROR__SDK__AGENT_ZERO_CAPABILITY
  | typeof SIGIL_ERROR__SDK__SIGNER_INVALID
  | typeof SIGIL_ERROR__SDK__SIGNATURE_INVALID
  | typeof SIGIL_ERROR__SDK__SPL_TOKEN_OP_BLOCKED
  | typeof SIGIL_ERROR__SDK__PROTOCOL_NOT_ALLOWED
  | typeof SIGIL_ERROR__SDK__PROTOCOL_NOT_TARGETED
  | typeof SIGIL_ERROR__SDK__INSTRUCTION_COUNT
  | typeof SIGIL_ERROR__SDK__CAP_EXCEEDED
  | typeof SIGIL_ERROR__SDK__ATA_NON_CANONICAL
  | typeof SIGIL_ERROR__SDK__ALT_INTEGRITY
  | typeof SIGIL_ERROR__SDK__ALT_NOT_DEPLOYED
  | typeof SIGIL_ERROR__SDK__SEAL_FAILED
  | typeof SIGIL_ERROR__SDK__HOOK_ABORTED
  | typeof SIGIL_ERROR__SDK__PLUGIN_REJECTED
  | typeof SIGIL_ERROR__SDK__OWNER_REQUIRED
  | typeof SIGIL_ERROR__SDK__UNKNOWN;

export type SigilRpcErrorCode =
  | typeof SIGIL_ERROR__RPC__TX_FAILED
  | typeof SIGIL_ERROR__RPC__CONFIRMATION_TIMEOUT
  | typeof SIGIL_ERROR__RPC__SIMULATION_FAILED
  | typeof SIGIL_ERROR__RPC__DRAIN_DETECTED
  | typeof SIGIL_ERROR__RPC__TX_TOO_LARGE
  | typeof SIGIL_ERROR__RPC__RATE_LIMITED
  | typeof SIGIL_ERROR__RPC__INSTRUCTION_REQUIRED;

export type SigilProgramErrorCode = typeof SIGIL_ERROR__PROGRAM__GENERIC;
