/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  getBorrowRateParamsDecoder,
  getBorrowRateParamsEncoder,
  getFeesDecoder,
  getFeesEncoder,
  getOracleParamsDecoder,
  getOracleParamsEncoder,
  getPermissionsDecoder,
  getPermissionsEncoder,
  getPricingParamsDecoder,
  getPricingParamsEncoder,
  getTokenRatiosDecoder,
  getTokenRatiosEncoder,
  type BorrowRateParams,
  type BorrowRateParamsArgs,
  type Fees,
  type FeesArgs,
  type OracleParams,
  type OracleParamsArgs,
  type Permissions,
  type PermissionsArgs,
  type PricingParams,
  type PricingParamsArgs,
  type TokenRatios,
  type TokenRatiosArgs,
} from "../types/index.js";

export const ADD_CUSTODY_DISCRIMINATOR = new Uint8Array([
  247, 254, 126, 17, 26, 6, 215, 117,
]);

export function getAddCustodyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ADD_CUSTODY_DISCRIMINATOR);
}

export type AddCustodyInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountCustodyTokenAccount extends string | AccountMeta<string> = string,
  TAccountCustodyTokenMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountCustody extends string
        ? WritableAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyTokenAccount extends string
        ? WritableAccount<TAccountCustodyTokenAccount>
        : TAccountCustodyTokenAccount,
      TAccountCustodyTokenMint extends string
        ? ReadonlyAccount<TAccountCustodyTokenMint>
        : TAccountCustodyTokenMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type AddCustodyInstructionData = {
  discriminator: ReadonlyUint8Array;
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  token22: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: Array<TokenRatios>;
  rewardThreshold: bigint;
  minReserveUsd: bigint;
  limitPriceBufferBps: bigint;
};

export type AddCustodyInstructionDataArgs = {
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  token22: boolean;
  oracle: OracleParamsArgs;
  pricing: PricingParamsArgs;
  permissions: PermissionsArgs;
  fees: FeesArgs;
  borrowRate: BorrowRateParamsArgs;
  ratios: Array<TokenRatiosArgs>;
  rewardThreshold: number | bigint;
  minReserveUsd: number | bigint;
  limitPriceBufferBps: number | bigint;
};

export function getAddCustodyInstructionDataEncoder(): Encoder<AddCustodyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["isStable", getBooleanEncoder()],
      ["depegAdjustment", getBooleanEncoder()],
      ["isVirtual", getBooleanEncoder()],
      ["inversePrice", getBooleanEncoder()],
      ["token22", getBooleanEncoder()],
      ["oracle", getOracleParamsEncoder()],
      ["pricing", getPricingParamsEncoder()],
      ["permissions", getPermissionsEncoder()],
      ["fees", getFeesEncoder()],
      ["borrowRate", getBorrowRateParamsEncoder()],
      ["ratios", getArrayEncoder(getTokenRatiosEncoder())],
      ["rewardThreshold", getU64Encoder()],
      ["minReserveUsd", getU64Encoder()],
      ["limitPriceBufferBps", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_CUSTODY_DISCRIMINATOR }),
  );
}

export function getAddCustodyInstructionDataDecoder(): Decoder<AddCustodyInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["isStable", getBooleanDecoder()],
    ["depegAdjustment", getBooleanDecoder()],
    ["isVirtual", getBooleanDecoder()],
    ["inversePrice", getBooleanDecoder()],
    ["token22", getBooleanDecoder()],
    ["oracle", getOracleParamsDecoder()],
    ["pricing", getPricingParamsDecoder()],
    ["permissions", getPermissionsDecoder()],
    ["fees", getFeesDecoder()],
    ["borrowRate", getBorrowRateParamsDecoder()],
    ["ratios", getArrayDecoder(getTokenRatiosDecoder())],
    ["rewardThreshold", getU64Decoder()],
    ["minReserveUsd", getU64Decoder()],
    ["limitPriceBufferBps", getU64Decoder()],
  ]);
}

export function getAddCustodyInstructionDataCodec(): Codec<
  AddCustodyInstructionDataArgs,
  AddCustodyInstructionData
> {
  return combineCodec(
    getAddCustodyInstructionDataEncoder(),
    getAddCustodyInstructionDataDecoder(),
  );
}

export type AddCustodyAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyTokenAccount extends string = string,
  TAccountCustodyTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  custody?: Address<TAccountCustody>;
  custodyTokenAccount?: Address<TAccountCustodyTokenAccount>;
  custodyTokenMint: Address<TAccountCustodyTokenMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  isStable: AddCustodyInstructionDataArgs["isStable"];
  depegAdjustment: AddCustodyInstructionDataArgs["depegAdjustment"];
  isVirtual: AddCustodyInstructionDataArgs["isVirtual"];
  inversePrice: AddCustodyInstructionDataArgs["inversePrice"];
  token22: AddCustodyInstructionDataArgs["token22"];
  oracle: AddCustodyInstructionDataArgs["oracle"];
  pricing: AddCustodyInstructionDataArgs["pricing"];
  permissions: AddCustodyInstructionDataArgs["permissions"];
  fees: AddCustodyInstructionDataArgs["fees"];
  borrowRate: AddCustodyInstructionDataArgs["borrowRate"];
  ratios: AddCustodyInstructionDataArgs["ratios"];
  rewardThreshold: AddCustodyInstructionDataArgs["rewardThreshold"];
  minReserveUsd: AddCustodyInstructionDataArgs["minReserveUsd"];
  limitPriceBufferBps: AddCustodyInstructionDataArgs["limitPriceBufferBps"];
};

export async function getAddCustodyInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountCustodyTokenAccount extends string,
  TAccountCustodyTokenMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: AddCustodyAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTokenAccount,
    TAccountCustodyTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AddCustodyInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTokenAccount,
    TAccountCustodyTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
    custodyTokenAccount: {
      value: input.custodyTokenAccount ?? null,
      isWritable: true,
    },
    custodyTokenMint: {
      value: input.custodyTokenMint ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.custody.value) {
    accounts.custody.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([99, 117, 115, 116, 111, 100, 121]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("pool", accounts.pool.value),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "custodyTokenMint",
            accounts.custodyTokenMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.custodyTokenAccount.value) {
    accounts.custodyTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            99, 117, 115, 116, 111, 100, 121, 95, 116, 111, 107, 101, 110, 95,
            97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("pool", accounts.pool.value),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "custodyTokenMint",
            accounts.custodyTokenMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("custody", accounts.custody),
      getAccountMeta("custodyTokenAccount", accounts.custodyTokenAccount),
      getAccountMeta("custodyTokenMint", accounts.custodyTokenMint),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getAddCustodyInstructionDataEncoder().encode(
      args as AddCustodyInstructionDataArgs,
    ),
    programAddress,
  } as AddCustodyInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTokenAccount,
    TAccountCustodyTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type AddCustodyInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyTokenAccount extends string = string,
  TAccountCustodyTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  custody: Address<TAccountCustody>;
  custodyTokenAccount: Address<TAccountCustodyTokenAccount>;
  custodyTokenMint: Address<TAccountCustodyTokenMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  isStable: AddCustodyInstructionDataArgs["isStable"];
  depegAdjustment: AddCustodyInstructionDataArgs["depegAdjustment"];
  isVirtual: AddCustodyInstructionDataArgs["isVirtual"];
  inversePrice: AddCustodyInstructionDataArgs["inversePrice"];
  token22: AddCustodyInstructionDataArgs["token22"];
  oracle: AddCustodyInstructionDataArgs["oracle"];
  pricing: AddCustodyInstructionDataArgs["pricing"];
  permissions: AddCustodyInstructionDataArgs["permissions"];
  fees: AddCustodyInstructionDataArgs["fees"];
  borrowRate: AddCustodyInstructionDataArgs["borrowRate"];
  ratios: AddCustodyInstructionDataArgs["ratios"];
  rewardThreshold: AddCustodyInstructionDataArgs["rewardThreshold"];
  minReserveUsd: AddCustodyInstructionDataArgs["minReserveUsd"];
  limitPriceBufferBps: AddCustodyInstructionDataArgs["limitPriceBufferBps"];
};

export function getAddCustodyInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountCustodyTokenAccount extends string,
  TAccountCustodyTokenMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: AddCustodyInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTokenAccount,
    TAccountCustodyTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): AddCustodyInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountCustody,
  TAccountCustodyTokenAccount,
  TAccountCustodyTokenMint,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
    custodyTokenAccount: {
      value: input.custodyTokenAccount ?? null,
      isWritable: true,
    },
    custodyTokenMint: {
      value: input.custodyTokenMint ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("custody", accounts.custody),
      getAccountMeta("custodyTokenAccount", accounts.custodyTokenAccount),
      getAccountMeta("custodyTokenMint", accounts.custodyTokenMint),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getAddCustodyInstructionDataEncoder().encode(
      args as AddCustodyInstructionDataArgs,
    ),
    programAddress,
  } as AddCustodyInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTokenAccount,
    TAccountCustodyTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type ParsedAddCustodyInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    pool: TAccountMetas[4];
    custody: TAccountMetas[5];
    custodyTokenAccount: TAccountMetas[6];
    custodyTokenMint: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    rent: TAccountMetas[10];
  };
  data: AddCustodyInstructionData;
};

export function parseAddCustodyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddCustodyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      custody: getNextAccount(),
      custodyTokenAccount: getNextAccount(),
      custodyTokenMint: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getAddCustodyInstructionDataDecoder().decode(instruction.data),
  };
}
