/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const DEPOSIT_TOKEN_STAKE_DISCRIMINATOR = new Uint8Array([
  105, 77, 29, 66, 28, 35, 183, 10,
]);

export function getDepositTokenStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DEPOSIT_TOKEN_STAKE_DISCRIMINATOR,
  );
}

export type DepositTokenStakeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountFeePayer extends string | AccountMeta<string> = string,
  TAccountFundingTokenAccount extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountTokenVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenStakeAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountFeePayer extends string
        ? WritableSignerAccount<TAccountFeePayer> &
            AccountSignerMeta<TAccountFeePayer>
        : TAccountFeePayer,
      TAccountFundingTokenAccount extends string
        ? WritableAccount<TAccountFundingTokenAccount>
        : TAccountFundingTokenAccount,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountTokenVaultTokenAccount extends string
        ? WritableAccount<TAccountTokenVaultTokenAccount>
        : TAccountTokenVaultTokenAccount,
      TAccountTokenStakeAccount extends string
        ? WritableAccount<TAccountTokenStakeAccount>
        : TAccountTokenStakeAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      ...TRemainingAccounts,
    ]
  >;

export type DepositTokenStakeInstructionData = {
  discriminator: ReadonlyUint8Array;
  depositAmount: bigint;
};

export type DepositTokenStakeInstructionDataArgs = {
  depositAmount: number | bigint;
};

export function getDepositTokenStakeInstructionDataEncoder(): FixedSizeEncoder<DepositTokenStakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["depositAmount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_TOKEN_STAKE_DISCRIMINATOR }),
  );
}

export function getDepositTokenStakeInstructionDataDecoder(): FixedSizeDecoder<DepositTokenStakeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["depositAmount", getU64Decoder()],
  ]);
}

export function getDepositTokenStakeInstructionDataCodec(): FixedSizeCodec<
  DepositTokenStakeInstructionDataArgs,
  DepositTokenStakeInstructionData
> {
  return combineCodec(
    getDepositTokenStakeInstructionDataEncoder(),
    getDepositTokenStakeInstructionDataDecoder(),
  );
}

export type DepositTokenStakeAsyncInput<
  TAccountOwner extends string = string,
  TAccountFeePayer extends string = string,
  TAccountFundingTokenAccount extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountTokenStakeAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountTokenMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  feePayer: TransactionSigner<TAccountFeePayer>;
  fundingTokenAccount: Address<TAccountFundingTokenAccount>;
  perpetuals?: Address<TAccountPerpetuals>;
  tokenVault?: Address<TAccountTokenVault>;
  tokenVaultTokenAccount?: Address<TAccountTokenVaultTokenAccount>;
  tokenStakeAccount?: Address<TAccountTokenStakeAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  tokenMint: Address<TAccountTokenMint>;
  depositAmount: DepositTokenStakeInstructionDataArgs["depositAmount"];
};

export async function getDepositTokenStakeInstructionAsync<
  TAccountOwner extends string,
  TAccountFeePayer extends string,
  TAccountFundingTokenAccount extends string,
  TAccountPerpetuals extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountTokenStakeAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: DepositTokenStakeAsyncInput<
    TAccountOwner,
    TAccountFeePayer,
    TAccountFundingTokenAccount,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountTokenStakeAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DepositTokenStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountFeePayer,
    TAccountFundingTokenAccount,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountTokenStakeAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountTokenMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    feePayer: { value: input.feePayer ?? null, isWritable: true },
    fundingTokenAccount: {
      value: input.fundingTokenAccount ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    tokenStakeAccount: {
      value: input.tokenStakeAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.tokenVault.value) {
    accounts.tokenVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116]),
        ),
      ],
    });
  }
  if (!accounts.tokenVaultTokenAccount.value) {
    accounts.tokenVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116, 95, 116, 111,
            107, 101, 110, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenStakeAccount.value) {
    accounts.tokenStakeAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 115, 116, 97, 107, 101]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "owner",
            accounts.owner.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("feePayer", accounts.feePayer),
      getAccountMeta("fundingTokenAccount", accounts.fundingTokenAccount),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("tokenStakeAccount", accounts.tokenStakeAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("tokenMint", accounts.tokenMint),
    ],
    data: getDepositTokenStakeInstructionDataEncoder().encode(
      args as DepositTokenStakeInstructionDataArgs,
    ),
    programAddress,
  } as DepositTokenStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountFeePayer,
    TAccountFundingTokenAccount,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountTokenStakeAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountTokenMint
  >);
}

export type DepositTokenStakeInput<
  TAccountOwner extends string = string,
  TAccountFeePayer extends string = string,
  TAccountFundingTokenAccount extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountTokenStakeAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountTokenMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  feePayer: TransactionSigner<TAccountFeePayer>;
  fundingTokenAccount: Address<TAccountFundingTokenAccount>;
  perpetuals: Address<TAccountPerpetuals>;
  tokenVault: Address<TAccountTokenVault>;
  tokenVaultTokenAccount: Address<TAccountTokenVaultTokenAccount>;
  tokenStakeAccount: Address<TAccountTokenStakeAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  tokenMint: Address<TAccountTokenMint>;
  depositAmount: DepositTokenStakeInstructionDataArgs["depositAmount"];
};

export function getDepositTokenStakeInstruction<
  TAccountOwner extends string,
  TAccountFeePayer extends string,
  TAccountFundingTokenAccount extends string,
  TAccountPerpetuals extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountTokenStakeAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: DepositTokenStakeInput<
    TAccountOwner,
    TAccountFeePayer,
    TAccountFundingTokenAccount,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountTokenStakeAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): DepositTokenStakeInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountFeePayer,
  TAccountFundingTokenAccount,
  TAccountPerpetuals,
  TAccountTokenVault,
  TAccountTokenVaultTokenAccount,
  TAccountTokenStakeAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountTokenMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    feePayer: { value: input.feePayer ?? null, isWritable: true },
    fundingTokenAccount: {
      value: input.fundingTokenAccount ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    tokenStakeAccount: {
      value: input.tokenStakeAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("feePayer", accounts.feePayer),
      getAccountMeta("fundingTokenAccount", accounts.fundingTokenAccount),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("tokenStakeAccount", accounts.tokenStakeAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("tokenMint", accounts.tokenMint),
    ],
    data: getDepositTokenStakeInstructionDataEncoder().encode(
      args as DepositTokenStakeInstructionDataArgs,
    ),
    programAddress,
  } as DepositTokenStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountFeePayer,
    TAccountFundingTokenAccount,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountTokenStakeAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountTokenMint
  >);
}

export type ParsedDepositTokenStakeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    feePayer: TAccountMetas[1];
    fundingTokenAccount: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    tokenVault: TAccountMetas[4];
    tokenVaultTokenAccount: TAccountMetas[5];
    tokenStakeAccount: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
    eventAuthority: TAccountMetas[9];
    program: TAccountMetas[10];
    tokenMint: TAccountMetas[11];
  };
  data: DepositTokenStakeInstructionData;
};

export function parseDepositTokenStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositTokenStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      feePayer: getNextAccount(),
      fundingTokenAccount: getNextAccount(),
      perpetuals: getNextAccount(),
      tokenVault: getNextAccount(),
      tokenVaultTokenAccount: getNextAccount(),
      tokenStakeAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      tokenMint: getNextAccount(),
    },
    data: getDepositTokenStakeInstructionDataDecoder().decode(instruction.data),
  };
}
