/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  getOraclePriceDecoder,
  getOraclePriceEncoder,
  getPrivilegeDecoder,
  getPrivilegeEncoder,
  type OraclePrice,
  type OraclePriceArgs,
  type Privilege,
  type PrivilegeArgs,
} from "../types/index.js";

export const GET_OPEN_POSITION_QUOTE_DISCRIMINATOR = new Uint8Array([
  41, 125, 167, 65, 176, 136, 144, 58,
]);

export function getGetOpenPositionQuoteDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_OPEN_POSITION_QUOTE_DISCRIMINATOR,
  );
}

export type GetOpenPositionQuoteInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountTargetCustody extends string | AccountMeta<string> = string,
  TAccountTargetOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountCollateralOracleAccount extends string | AccountMeta<string> = string,
  TAccountReceivingCustody extends string | AccountMeta<string> = string,
  TAccountReceivingCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TAccountIxSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountTargetCustody extends string
        ? ReadonlyAccount<TAccountTargetCustody>
        : TAccountTargetCustody,
      TAccountTargetOracleAccount extends string
        ? ReadonlyAccount<TAccountTargetOracleAccount>
        : TAccountTargetOracleAccount,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralOracleAccount extends string
        ? ReadonlyAccount<TAccountCollateralOracleAccount>
        : TAccountCollateralOracleAccount,
      TAccountReceivingCustody extends string
        ? ReadonlyAccount<TAccountReceivingCustody>
        : TAccountReceivingCustody,
      TAccountReceivingCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountReceivingCustodyOracleAccount>
        : TAccountReceivingCustodyOracleAccount,
      TAccountIxSysvar extends string
        ? ReadonlyAccount<TAccountIxSysvar>
        : TAccountIxSysvar,
      ...TRemainingAccounts,
    ]
  >;

export type GetOpenPositionQuoteInstructionData = {
  discriminator: ReadonlyUint8Array;
  amountIn: bigint;
  leverage: bigint;
  privilege: Privilege;
  discountIndex: Option<number>;
  limitPrice: Option<OraclePrice>;
  takeProfitPrice: Option<OraclePrice>;
  stopLossPrice: Option<OraclePrice>;
};

export type GetOpenPositionQuoteInstructionDataArgs = {
  amountIn: number | bigint;
  leverage: number | bigint;
  privilege: PrivilegeArgs;
  discountIndex: OptionOrNullable<number>;
  limitPrice: OptionOrNullable<OraclePriceArgs>;
  takeProfitPrice: OptionOrNullable<OraclePriceArgs>;
  stopLossPrice: OptionOrNullable<OraclePriceArgs>;
};

export function getGetOpenPositionQuoteInstructionDataEncoder(): Encoder<GetOpenPositionQuoteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amountIn", getU64Encoder()],
      ["leverage", getU64Encoder()],
      ["privilege", getPrivilegeEncoder()],
      ["discountIndex", getOptionEncoder(getU8Encoder())],
      ["limitPrice", getOptionEncoder(getOraclePriceEncoder())],
      ["takeProfitPrice", getOptionEncoder(getOraclePriceEncoder())],
      ["stopLossPrice", getOptionEncoder(getOraclePriceEncoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: GET_OPEN_POSITION_QUOTE_DISCRIMINATOR,
    }),
  );
}

export function getGetOpenPositionQuoteInstructionDataDecoder(): Decoder<GetOpenPositionQuoteInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amountIn", getU64Decoder()],
    ["leverage", getU64Decoder()],
    ["privilege", getPrivilegeDecoder()],
    ["discountIndex", getOptionDecoder(getU8Decoder())],
    ["limitPrice", getOptionDecoder(getOraclePriceDecoder())],
    ["takeProfitPrice", getOptionDecoder(getOraclePriceDecoder())],
    ["stopLossPrice", getOptionDecoder(getOraclePriceDecoder())],
  ]);
}

export function getGetOpenPositionQuoteInstructionDataCodec(): Codec<
  GetOpenPositionQuoteInstructionDataArgs,
  GetOpenPositionQuoteInstructionData
> {
  return combineCodec(
    getGetOpenPositionQuoteInstructionDataEncoder(),
    getGetOpenPositionQuoteInstructionDataDecoder(),
  );
}

export type GetOpenPositionQuoteAsyncInput<
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountReceivingCustody extends string = string,
  TAccountReceivingCustodyOracleAccount extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  receivingCustody: Address<TAccountReceivingCustody>;
  receivingCustodyOracleAccount: Address<TAccountReceivingCustodyOracleAccount>;
  ixSysvar?: Address<TAccountIxSysvar>;
  amountIn: GetOpenPositionQuoteInstructionDataArgs["amountIn"];
  leverage: GetOpenPositionQuoteInstructionDataArgs["leverage"];
  privilege: GetOpenPositionQuoteInstructionDataArgs["privilege"];
  discountIndex: GetOpenPositionQuoteInstructionDataArgs["discountIndex"];
  limitPrice: GetOpenPositionQuoteInstructionDataArgs["limitPrice"];
  takeProfitPrice: GetOpenPositionQuoteInstructionDataArgs["takeProfitPrice"];
  stopLossPrice: GetOpenPositionQuoteInstructionDataArgs["stopLossPrice"];
};

export async function getGetOpenPositionQuoteInstructionAsync<
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountReceivingCustody extends string,
  TAccountReceivingCustodyOracleAccount extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: GetOpenPositionQuoteAsyncInput<
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  GetOpenPositionQuoteInstruction<
    TProgramAddress,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountIxSysvar
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    market: { value: input.market ?? null, isWritable: false },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    receivingCustody: {
      value: input.receivingCustody ?? null,
      isWritable: false,
    },
    receivingCustodyOracleAccount: {
      value: input.receivingCustodyOracleAccount ?? null,
      isWritable: false,
    },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta("receivingCustody", accounts.receivingCustody),
      getAccountMeta(
        "receivingCustodyOracleAccount",
        accounts.receivingCustodyOracleAccount,
      ),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getGetOpenPositionQuoteInstructionDataEncoder().encode(
      args as GetOpenPositionQuoteInstructionDataArgs,
    ),
    programAddress,
  } as GetOpenPositionQuoteInstruction<
    TProgramAddress,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountIxSysvar
  >);
}

export type GetOpenPositionQuoteInput<
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountReceivingCustody extends string = string,
  TAccountReceivingCustodyOracleAccount extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  receivingCustody: Address<TAccountReceivingCustody>;
  receivingCustodyOracleAccount: Address<TAccountReceivingCustodyOracleAccount>;
  ixSysvar?: Address<TAccountIxSysvar>;
  amountIn: GetOpenPositionQuoteInstructionDataArgs["amountIn"];
  leverage: GetOpenPositionQuoteInstructionDataArgs["leverage"];
  privilege: GetOpenPositionQuoteInstructionDataArgs["privilege"];
  discountIndex: GetOpenPositionQuoteInstructionDataArgs["discountIndex"];
  limitPrice: GetOpenPositionQuoteInstructionDataArgs["limitPrice"];
  takeProfitPrice: GetOpenPositionQuoteInstructionDataArgs["takeProfitPrice"];
  stopLossPrice: GetOpenPositionQuoteInstructionDataArgs["stopLossPrice"];
};

export function getGetOpenPositionQuoteInstruction<
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountReceivingCustody extends string,
  TAccountReceivingCustodyOracleAccount extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: GetOpenPositionQuoteInput<
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): GetOpenPositionQuoteInstruction<
  TProgramAddress,
  TAccountPerpetuals,
  TAccountPool,
  TAccountMarket,
  TAccountTargetCustody,
  TAccountTargetOracleAccount,
  TAccountCollateralCustody,
  TAccountCollateralOracleAccount,
  TAccountReceivingCustody,
  TAccountReceivingCustodyOracleAccount,
  TAccountIxSysvar
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    market: { value: input.market ?? null, isWritable: false },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    receivingCustody: {
      value: input.receivingCustody ?? null,
      isWritable: false,
    },
    receivingCustodyOracleAccount: {
      value: input.receivingCustodyOracleAccount ?? null,
      isWritable: false,
    },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta("receivingCustody", accounts.receivingCustody),
      getAccountMeta(
        "receivingCustodyOracleAccount",
        accounts.receivingCustodyOracleAccount,
      ),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getGetOpenPositionQuoteInstructionDataEncoder().encode(
      args as GetOpenPositionQuoteInstructionDataArgs,
    ),
    programAddress,
  } as GetOpenPositionQuoteInstruction<
    TProgramAddress,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountIxSysvar
  >);
}

export type ParsedGetOpenPositionQuoteInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    perpetuals: TAccountMetas[0];
    pool: TAccountMetas[1];
    market: TAccountMetas[2];
    targetCustody: TAccountMetas[3];
    targetOracleAccount: TAccountMetas[4];
    collateralCustody: TAccountMetas[5];
    collateralOracleAccount: TAccountMetas[6];
    receivingCustody: TAccountMetas[7];
    receivingCustodyOracleAccount: TAccountMetas[8];
    ixSysvar: TAccountMetas[9];
  };
  data: GetOpenPositionQuoteInstructionData;
};

export function parseGetOpenPositionQuoteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGetOpenPositionQuoteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 10,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      market: getNextAccount(),
      targetCustody: getNextAccount(),
      targetOracleAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralOracleAccount: getNextAccount(),
      receivingCustody: getNextAccount(),
      receivingCustodyOracleAccount: getNextAccount(),
      ixSysvar: getNextAccount(),
    },
    data: getGetOpenPositionQuoteInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
