/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const INIT_REVENUE_TOKEN_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  235, 126, 219, 143, 29, 74, 149, 161,
]);

export function getInitRevenueTokenAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_REVENUE_TOKEN_ACCOUNT_DISCRIMINATOR,
  );
}

export type InitRevenueTokenAccountInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountRewardMint extends string | AccountMeta<string> = string,
  TAccountRevenueTokenAccount extends string | AccountMeta<string> = string,
  TAccountProtocolVault extends string | AccountMeta<string> = string,
  TAccountProtocolTokenAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountRewardMint extends string
        ? ReadonlyAccount<TAccountRewardMint>
        : TAccountRewardMint,
      TAccountRevenueTokenAccount extends string
        ? WritableAccount<TAccountRevenueTokenAccount>
        : TAccountRevenueTokenAccount,
      TAccountProtocolVault extends string
        ? WritableAccount<TAccountProtocolVault>
        : TAccountProtocolVault,
      TAccountProtocolTokenAccount extends string
        ? WritableAccount<TAccountProtocolTokenAccount>
        : TAccountProtocolTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type InitRevenueTokenAccountInstructionData = {
  discriminator: ReadonlyUint8Array;
  feeShareBps: bigint;
};

export type InitRevenueTokenAccountInstructionDataArgs = {
  feeShareBps: number | bigint;
};

export function getInitRevenueTokenAccountInstructionDataEncoder(): FixedSizeEncoder<InitRevenueTokenAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["feeShareBps", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INIT_REVENUE_TOKEN_ACCOUNT_DISCRIMINATOR,
    }),
  );
}

export function getInitRevenueTokenAccountInstructionDataDecoder(): FixedSizeDecoder<InitRevenueTokenAccountInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["feeShareBps", getU64Decoder()],
  ]);
}

export function getInitRevenueTokenAccountInstructionDataCodec(): FixedSizeCodec<
  InitRevenueTokenAccountInstructionDataArgs,
  InitRevenueTokenAccountInstructionData
> {
  return combineCodec(
    getInitRevenueTokenAccountInstructionDataEncoder(),
    getInitRevenueTokenAccountInstructionDataDecoder(),
  );
}

export type InitRevenueTokenAccountAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTokenVault extends string = string,
  TAccountRewardMint extends string = string,
  TAccountRevenueTokenAccount extends string = string,
  TAccountProtocolVault extends string = string,
  TAccountProtocolTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  tokenVault?: Address<TAccountTokenVault>;
  rewardMint: Address<TAccountRewardMint>;
  revenueTokenAccount?: Address<TAccountRevenueTokenAccount>;
  protocolVault?: Address<TAccountProtocolVault>;
  protocolTokenAccount?: Address<TAccountProtocolTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  feeShareBps: InitRevenueTokenAccountInstructionDataArgs["feeShareBps"];
};

export async function getInitRevenueTokenAccountInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountTokenVault extends string,
  TAccountRewardMint extends string,
  TAccountRevenueTokenAccount extends string,
  TAccountProtocolVault extends string,
  TAccountProtocolTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitRevenueTokenAccountAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountRewardMint,
    TAccountRevenueTokenAccount,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitRevenueTokenAccountInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountRewardMint,
    TAccountRevenueTokenAccount,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    revenueTokenAccount: {
      value: input.revenueTokenAccount ?? null,
      isWritable: true,
    },
    protocolVault: { value: input.protocolVault ?? null, isWritable: true },
    protocolTokenAccount: {
      value: input.protocolTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.tokenVault.value) {
    accounts.tokenVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116]),
        ),
      ],
    });
  }
  if (!accounts.revenueTokenAccount.value) {
    accounts.revenueTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            114, 101, 118, 101, 110, 117, 101, 95, 116, 111, 107, 101, 110, 95,
            97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.protocolVault.value) {
    accounts.protocolVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            112, 114, 111, 116, 111, 99, 111, 108, 95, 118, 97, 117, 108, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.protocolTokenAccount.value) {
    accounts.protocolTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            112, 114, 111, 116, 111, 99, 111, 108, 95, 116, 111, 107, 101, 110,
            95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("revenueTokenAccount", accounts.revenueTokenAccount),
      getAccountMeta("protocolVault", accounts.protocolVault),
      getAccountMeta("protocolTokenAccount", accounts.protocolTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitRevenueTokenAccountInstructionDataEncoder().encode(
      args as InitRevenueTokenAccountInstructionDataArgs,
    ),
    programAddress,
  } as InitRevenueTokenAccountInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountRewardMint,
    TAccountRevenueTokenAccount,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type InitRevenueTokenAccountInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTokenVault extends string = string,
  TAccountRewardMint extends string = string,
  TAccountRevenueTokenAccount extends string = string,
  TAccountProtocolVault extends string = string,
  TAccountProtocolTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  tokenVault: Address<TAccountTokenVault>;
  rewardMint: Address<TAccountRewardMint>;
  revenueTokenAccount: Address<TAccountRevenueTokenAccount>;
  protocolVault: Address<TAccountProtocolVault>;
  protocolTokenAccount: Address<TAccountProtocolTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  feeShareBps: InitRevenueTokenAccountInstructionDataArgs["feeShareBps"];
};

export function getInitRevenueTokenAccountInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountTokenVault extends string,
  TAccountRewardMint extends string,
  TAccountRevenueTokenAccount extends string,
  TAccountProtocolVault extends string,
  TAccountProtocolTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitRevenueTokenAccountInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountRewardMint,
    TAccountRevenueTokenAccount,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): InitRevenueTokenAccountInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountTokenVault,
  TAccountRewardMint,
  TAccountRevenueTokenAccount,
  TAccountProtocolVault,
  TAccountProtocolTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    revenueTokenAccount: {
      value: input.revenueTokenAccount ?? null,
      isWritable: true,
    },
    protocolVault: { value: input.protocolVault ?? null, isWritable: true },
    protocolTokenAccount: {
      value: input.protocolTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("revenueTokenAccount", accounts.revenueTokenAccount),
      getAccountMeta("protocolVault", accounts.protocolVault),
      getAccountMeta("protocolTokenAccount", accounts.protocolTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitRevenueTokenAccountInstructionDataEncoder().encode(
      args as InitRevenueTokenAccountInstructionDataArgs,
    ),
    programAddress,
  } as InitRevenueTokenAccountInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountTokenVault,
    TAccountRewardMint,
    TAccountRevenueTokenAccount,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type ParsedInitRevenueTokenAccountInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    tokenVault: TAccountMetas[4];
    rewardMint: TAccountMetas[5];
    revenueTokenAccount: TAccountMetas[6];
    protocolVault: TAccountMetas[7];
    protocolTokenAccount: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
    tokenProgram: TAccountMetas[10];
    rent: TAccountMetas[11];
  };
  data: InitRevenueTokenAccountInstructionData;
};

export function parseInitRevenueTokenAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitRevenueTokenAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      tokenVault: getNextAccount(),
      rewardMint: getNextAccount(),
      revenueTokenAccount: getNextAccount(),
      protocolVault: getNextAccount(),
      protocolTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitRevenueTokenAccountInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
