/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const INIT_STAKING_DISCRIMINATOR = new Uint8Array([
  42, 18, 242, 224, 66, 32, 122, 8,
]);

export function getInitStakingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_STAKING_DISCRIMINATOR,
  );
}

export type InitStakingInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountLpTokenMint extends string | AccountMeta<string> = string,
  TAccountStakedLpTokenAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountCustody extends string
        ? WritableAccount<TAccountCustody>
        : TAccountCustody,
      TAccountLpTokenMint extends string
        ? ReadonlyAccount<TAccountLpTokenMint>
        : TAccountLpTokenMint,
      TAccountStakedLpTokenAccount extends string
        ? WritableAccount<TAccountStakedLpTokenAccount>
        : TAccountStakedLpTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type InitStakingInstructionData = {
  discriminator: ReadonlyUint8Array;
  stakingFeeShareBps: bigint;
};

export type InitStakingInstructionDataArgs = {
  stakingFeeShareBps: number | bigint;
};

export function getInitStakingInstructionDataEncoder(): FixedSizeEncoder<InitStakingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["stakingFeeShareBps", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_STAKING_DISCRIMINATOR }),
  );
}

export function getInitStakingInstructionDataDecoder(): FixedSizeDecoder<InitStakingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["stakingFeeShareBps", getU64Decoder()],
  ]);
}

export function getInitStakingInstructionDataCodec(): FixedSizeCodec<
  InitStakingInstructionDataArgs,
  InitStakingInstructionData
> {
  return combineCodec(
    getInitStakingInstructionDataEncoder(),
    getInitStakingInstructionDataDecoder(),
  );
}

export type InitStakingAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountLpTokenMint extends string = string,
  TAccountStakedLpTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  custody: Address<TAccountCustody>;
  lpTokenMint?: Address<TAccountLpTokenMint>;
  stakedLpTokenAccount?: Address<TAccountStakedLpTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  stakingFeeShareBps: InitStakingInstructionDataArgs["stakingFeeShareBps"];
};

export async function getInitStakingInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountLpTokenMint extends string,
  TAccountStakedLpTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitStakingAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountLpTokenMint,
    TAccountStakedLpTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitStakingInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountLpTokenMint,
    TAccountStakedLpTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
    lpTokenMint: { value: input.lpTokenMint ?? null, isWritable: false },
    stakedLpTokenAccount: {
      value: input.stakedLpTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.lpTokenMint.value) {
    accounts.lpTokenMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            108, 112, 95, 116, 111, 107, 101, 110, 95, 109, 105, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("pool", accounts.pool.value),
        ),
      ],
    });
  }
  if (!accounts.stakedLpTokenAccount.value) {
    accounts.stakedLpTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            115, 116, 97, 107, 101, 100, 95, 108, 112, 95, 116, 111, 107, 101,
            110, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("pool", accounts.pool.value),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "lpTokenMint",
            accounts.lpTokenMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("custody", accounts.custody),
      getAccountMeta("lpTokenMint", accounts.lpTokenMint),
      getAccountMeta("stakedLpTokenAccount", accounts.stakedLpTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitStakingInstructionDataEncoder().encode(
      args as InitStakingInstructionDataArgs,
    ),
    programAddress,
  } as InitStakingInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountLpTokenMint,
    TAccountStakedLpTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type InitStakingInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountLpTokenMint extends string = string,
  TAccountStakedLpTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  custody: Address<TAccountCustody>;
  lpTokenMint: Address<TAccountLpTokenMint>;
  stakedLpTokenAccount: Address<TAccountStakedLpTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  stakingFeeShareBps: InitStakingInstructionDataArgs["stakingFeeShareBps"];
};

export function getInitStakingInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountLpTokenMint extends string,
  TAccountStakedLpTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitStakingInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountLpTokenMint,
    TAccountStakedLpTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): InitStakingInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountCustody,
  TAccountLpTokenMint,
  TAccountStakedLpTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
    lpTokenMint: { value: input.lpTokenMint ?? null, isWritable: false },
    stakedLpTokenAccount: {
      value: input.stakedLpTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("custody", accounts.custody),
      getAccountMeta("lpTokenMint", accounts.lpTokenMint),
      getAccountMeta("stakedLpTokenAccount", accounts.stakedLpTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitStakingInstructionDataEncoder().encode(
      args as InitStakingInstructionDataArgs,
    ),
    programAddress,
  } as InitStakingInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountCustody,
    TAccountLpTokenMint,
    TAccountStakedLpTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type ParsedInitStakingInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    pool: TAccountMetas[4];
    custody: TAccountMetas[5];
    lpTokenMint: TAccountMetas[6];
    stakedLpTokenAccount: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    rent: TAccountMetas[10];
  };
  data: InitStakingInstructionData;
};

export function parseInitStakingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitStakingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      custody: getNextAccount(),
      lpTokenMint: getNextAccount(),
      stakedLpTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitStakingInstructionDataDecoder().decode(instruction.data),
  };
}
