/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const MIGRATE_STAKE_DISCRIMINATOR = new Uint8Array([
  178, 5, 26, 85, 56, 20, 153, 160,
]);

export function getMigrateStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MIGRATE_STAKE_DISCRIMINATOR,
  );
}

export type MigrateStakeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountCompoundingTokenAccount extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountFlpStakeAccount extends string | AccountMeta<string> = string,
  TAccountRewardCustody extends string | AccountMeta<string> = string,
  TAccountRewardCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TAccountPoolStakedLpVault extends string | AccountMeta<string> = string,
  TAccountPoolCompoundingLpVault extends string | AccountMeta<string> = string,
  TAccountLpTokenMint extends string | AccountMeta<string> = string,
  TAccountCompoundingTokenMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountIxSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountCompoundingTokenAccount extends string
        ? WritableAccount<TAccountCompoundingTokenAccount>
        : TAccountCompoundingTokenAccount,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountFlpStakeAccount extends string
        ? WritableAccount<TAccountFlpStakeAccount>
        : TAccountFlpStakeAccount,
      TAccountRewardCustody extends string
        ? WritableAccount<TAccountRewardCustody>
        : TAccountRewardCustody,
      TAccountRewardCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountRewardCustodyOracleAccount>
        : TAccountRewardCustodyOracleAccount,
      TAccountPoolStakedLpVault extends string
        ? WritableAccount<TAccountPoolStakedLpVault>
        : TAccountPoolStakedLpVault,
      TAccountPoolCompoundingLpVault extends string
        ? WritableAccount<TAccountPoolCompoundingLpVault>
        : TAccountPoolCompoundingLpVault,
      TAccountLpTokenMint extends string
        ? WritableAccount<TAccountLpTokenMint>
        : TAccountLpTokenMint,
      TAccountCompoundingTokenMint extends string
        ? WritableAccount<TAccountCompoundingTokenMint>
        : TAccountCompoundingTokenMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountIxSysvar extends string
        ? ReadonlyAccount<TAccountIxSysvar>
        : TAccountIxSysvar,
      ...TRemainingAccounts,
    ]
  >;

export type MigrateStakeInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type MigrateStakeInstructionDataArgs = { amount: number | bigint };

export function getMigrateStakeInstructionDataEncoder(): FixedSizeEncoder<MigrateStakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MIGRATE_STAKE_DISCRIMINATOR }),
  );
}

export function getMigrateStakeInstructionDataDecoder(): FixedSizeDecoder<MigrateStakeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getMigrateStakeInstructionDataCodec(): FixedSizeCodec<
  MigrateStakeInstructionDataArgs,
  MigrateStakeInstructionData
> {
  return combineCodec(
    getMigrateStakeInstructionDataEncoder(),
    getMigrateStakeInstructionDataDecoder(),
  );
}

export type MigrateStakeAsyncInput<
  TAccountOwner extends string = string,
  TAccountCompoundingTokenAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountFlpStakeAccount extends string = string,
  TAccountRewardCustody extends string = string,
  TAccountRewardCustodyOracleAccount extends string = string,
  TAccountPoolStakedLpVault extends string = string,
  TAccountPoolCompoundingLpVault extends string = string,
  TAccountLpTokenMint extends string = string,
  TAccountCompoundingTokenMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  compoundingTokenAccount: Address<TAccountCompoundingTokenAccount>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  flpStakeAccount?: Address<TAccountFlpStakeAccount>;
  rewardCustody: Address<TAccountRewardCustody>;
  rewardCustodyOracleAccount: Address<TAccountRewardCustodyOracleAccount>;
  poolStakedLpVault: Address<TAccountPoolStakedLpVault>;
  poolCompoundingLpVault: Address<TAccountPoolCompoundingLpVault>;
  lpTokenMint: Address<TAccountLpTokenMint>;
  compoundingTokenMint: Address<TAccountCompoundingTokenMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  amount: MigrateStakeInstructionDataArgs["amount"];
};

export async function getMigrateStakeInstructionAsync<
  TAccountOwner extends string,
  TAccountCompoundingTokenAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountFlpStakeAccount extends string,
  TAccountRewardCustody extends string,
  TAccountRewardCustodyOracleAccount extends string,
  TAccountPoolStakedLpVault extends string,
  TAccountPoolCompoundingLpVault extends string,
  TAccountLpTokenMint extends string,
  TAccountCompoundingTokenMint extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: MigrateStakeAsyncInput<
    TAccountOwner,
    TAccountCompoundingTokenAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountFlpStakeAccount,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountPoolStakedLpVault,
    TAccountPoolCompoundingLpVault,
    TAccountLpTokenMint,
    TAccountCompoundingTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MigrateStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountCompoundingTokenAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountFlpStakeAccount,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountPoolStakedLpVault,
    TAccountPoolCompoundingLpVault,
    TAccountLpTokenMint,
    TAccountCompoundingTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    compoundingTokenAccount: {
      value: input.compoundingTokenAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    flpStakeAccount: { value: input.flpStakeAccount ?? null, isWritable: true },
    rewardCustody: { value: input.rewardCustody ?? null, isWritable: true },
    rewardCustodyOracleAccount: {
      value: input.rewardCustodyOracleAccount ?? null,
      isWritable: false,
    },
    poolStakedLpVault: {
      value: input.poolStakedLpVault ?? null,
      isWritable: true,
    },
    poolCompoundingLpVault: {
      value: input.poolCompoundingLpVault ?? null,
      isWritable: true,
    },
    lpTokenMint: { value: input.lpTokenMint ?? null, isWritable: true },
    compoundingTokenMint: {
      value: input.compoundingTokenMint ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.flpStakeAccount.value) {
    accounts.flpStakeAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([115, 116, 97, 107, 101])),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "owner",
            accounts.owner.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("pool", accounts.pool.value),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta(
        "compoundingTokenAccount",
        accounts.compoundingTokenAccount,
      ),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("flpStakeAccount", accounts.flpStakeAccount),
      getAccountMeta("rewardCustody", accounts.rewardCustody),
      getAccountMeta(
        "rewardCustodyOracleAccount",
        accounts.rewardCustodyOracleAccount,
      ),
      getAccountMeta("poolStakedLpVault", accounts.poolStakedLpVault),
      getAccountMeta("poolCompoundingLpVault", accounts.poolCompoundingLpVault),
      getAccountMeta("lpTokenMint", accounts.lpTokenMint),
      getAccountMeta("compoundingTokenMint", accounts.compoundingTokenMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getMigrateStakeInstructionDataEncoder().encode(
      args as MigrateStakeInstructionDataArgs,
    ),
    programAddress,
  } as MigrateStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountCompoundingTokenAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountFlpStakeAccount,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountPoolStakedLpVault,
    TAccountPoolCompoundingLpVault,
    TAccountLpTokenMint,
    TAccountCompoundingTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >);
}

export type MigrateStakeInput<
  TAccountOwner extends string = string,
  TAccountCompoundingTokenAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountFlpStakeAccount extends string = string,
  TAccountRewardCustody extends string = string,
  TAccountRewardCustodyOracleAccount extends string = string,
  TAccountPoolStakedLpVault extends string = string,
  TAccountPoolCompoundingLpVault extends string = string,
  TAccountLpTokenMint extends string = string,
  TAccountCompoundingTokenMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  compoundingTokenAccount: Address<TAccountCompoundingTokenAccount>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  flpStakeAccount: Address<TAccountFlpStakeAccount>;
  rewardCustody: Address<TAccountRewardCustody>;
  rewardCustodyOracleAccount: Address<TAccountRewardCustodyOracleAccount>;
  poolStakedLpVault: Address<TAccountPoolStakedLpVault>;
  poolCompoundingLpVault: Address<TAccountPoolCompoundingLpVault>;
  lpTokenMint: Address<TAccountLpTokenMint>;
  compoundingTokenMint: Address<TAccountCompoundingTokenMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  amount: MigrateStakeInstructionDataArgs["amount"];
};

export function getMigrateStakeInstruction<
  TAccountOwner extends string,
  TAccountCompoundingTokenAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountFlpStakeAccount extends string,
  TAccountRewardCustody extends string,
  TAccountRewardCustodyOracleAccount extends string,
  TAccountPoolStakedLpVault extends string,
  TAccountPoolCompoundingLpVault extends string,
  TAccountLpTokenMint extends string,
  TAccountCompoundingTokenMint extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: MigrateStakeInput<
    TAccountOwner,
    TAccountCompoundingTokenAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountFlpStakeAccount,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountPoolStakedLpVault,
    TAccountPoolCompoundingLpVault,
    TAccountLpTokenMint,
    TAccountCompoundingTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): MigrateStakeInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountCompoundingTokenAccount,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountFlpStakeAccount,
  TAccountRewardCustody,
  TAccountRewardCustodyOracleAccount,
  TAccountPoolStakedLpVault,
  TAccountPoolCompoundingLpVault,
  TAccountLpTokenMint,
  TAccountCompoundingTokenMint,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountIxSysvar
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    compoundingTokenAccount: {
      value: input.compoundingTokenAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    flpStakeAccount: { value: input.flpStakeAccount ?? null, isWritable: true },
    rewardCustody: { value: input.rewardCustody ?? null, isWritable: true },
    rewardCustodyOracleAccount: {
      value: input.rewardCustodyOracleAccount ?? null,
      isWritable: false,
    },
    poolStakedLpVault: {
      value: input.poolStakedLpVault ?? null,
      isWritable: true,
    },
    poolCompoundingLpVault: {
      value: input.poolCompoundingLpVault ?? null,
      isWritable: true,
    },
    lpTokenMint: { value: input.lpTokenMint ?? null, isWritable: true },
    compoundingTokenMint: {
      value: input.compoundingTokenMint ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta(
        "compoundingTokenAccount",
        accounts.compoundingTokenAccount,
      ),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("flpStakeAccount", accounts.flpStakeAccount),
      getAccountMeta("rewardCustody", accounts.rewardCustody),
      getAccountMeta(
        "rewardCustodyOracleAccount",
        accounts.rewardCustodyOracleAccount,
      ),
      getAccountMeta("poolStakedLpVault", accounts.poolStakedLpVault),
      getAccountMeta("poolCompoundingLpVault", accounts.poolCompoundingLpVault),
      getAccountMeta("lpTokenMint", accounts.lpTokenMint),
      getAccountMeta("compoundingTokenMint", accounts.compoundingTokenMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getMigrateStakeInstructionDataEncoder().encode(
      args as MigrateStakeInstructionDataArgs,
    ),
    programAddress,
  } as MigrateStakeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountCompoundingTokenAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountFlpStakeAccount,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountPoolStakedLpVault,
    TAccountPoolCompoundingLpVault,
    TAccountLpTokenMint,
    TAccountCompoundingTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >);
}

export type ParsedMigrateStakeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    compoundingTokenAccount: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    pool: TAccountMetas[4];
    flpStakeAccount: TAccountMetas[5];
    rewardCustody: TAccountMetas[6];
    rewardCustodyOracleAccount: TAccountMetas[7];
    poolStakedLpVault: TAccountMetas[8];
    poolCompoundingLpVault: TAccountMetas[9];
    lpTokenMint: TAccountMetas[10];
    compoundingTokenMint: TAccountMetas[11];
    tokenProgram: TAccountMetas[12];
    eventAuthority: TAccountMetas[13];
    program: TAccountMetas[14];
    ixSysvar: TAccountMetas[15];
  };
  data: MigrateStakeInstructionData;
};

export function parseMigrateStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMigrateStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 16) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 16,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      compoundingTokenAccount: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      flpStakeAccount: getNextAccount(),
      rewardCustody: getNextAccount(),
      rewardCustodyOracleAccount: getNextAccount(),
      poolStakedLpVault: getNextAccount(),
      poolCompoundingLpVault: getNextAccount(),
      lpTokenMint: getNextAccount(),
      compoundingTokenMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      ixSysvar: getNextAccount(),
    },
    data: getMigrateStakeInstructionDataDecoder().decode(instruction.data),
  };
}
