/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const REMOVE_COLLATERAL_DISCRIMINATOR = new Uint8Array([
  86, 222, 130, 86, 92, 20, 72, 65,
]);

export function getRemoveCollateralDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REMOVE_COLLATERAL_DISCRIMINATOR,
  );
}

export type RemoveCollateralInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountReceivingAccount extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountTargetCustody extends string | AccountMeta<string> = string,
  TAccountTargetOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountCollateralOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustodyTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountReceivingTokenProgram extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountIxSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountReceivingMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountReceivingAccount extends string
        ? WritableAccount<TAccountReceivingAccount>
        : TAccountReceivingAccount,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountTargetCustody extends string
        ? ReadonlyAccount<TAccountTargetCustody>
        : TAccountTargetCustody,
      TAccountTargetOracleAccount extends string
        ? ReadonlyAccount<TAccountTargetOracleAccount>
        : TAccountTargetOracleAccount,
      TAccountCollateralCustody extends string
        ? WritableAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralOracleAccount extends string
        ? ReadonlyAccount<TAccountCollateralOracleAccount>
        : TAccountCollateralOracleAccount,
      TAccountCollateralCustodyTokenAccount extends string
        ? WritableAccount<TAccountCollateralCustodyTokenAccount>
        : TAccountCollateralCustodyTokenAccount,
      TAccountReceivingTokenProgram extends string
        ? ReadonlyAccount<TAccountReceivingTokenProgram>
        : TAccountReceivingTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountIxSysvar extends string
        ? ReadonlyAccount<TAccountIxSysvar>
        : TAccountIxSysvar,
      TAccountReceivingMint extends string
        ? ReadonlyAccount<TAccountReceivingMint>
        : TAccountReceivingMint,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveCollateralInstructionData = {
  discriminator: ReadonlyUint8Array;
  collateralDeltaUsd: bigint;
};

export type RemoveCollateralInstructionDataArgs = {
  collateralDeltaUsd: number | bigint;
};

export function getRemoveCollateralInstructionDataEncoder(): FixedSizeEncoder<RemoveCollateralInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["collateralDeltaUsd", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REMOVE_COLLATERAL_DISCRIMINATOR }),
  );
}

export function getRemoveCollateralInstructionDataDecoder(): FixedSizeDecoder<RemoveCollateralInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["collateralDeltaUsd", getU64Decoder()],
  ]);
}

export function getRemoveCollateralInstructionDataCodec(): FixedSizeCodec<
  RemoveCollateralInstructionDataArgs,
  RemoveCollateralInstructionData
> {
  return combineCodec(
    getRemoveCollateralInstructionDataEncoder(),
    getRemoveCollateralInstructionDataDecoder(),
  );
}

export type RemoveCollateralAsyncInput<
  TAccountOwner extends string = string,
  TAccountReceivingAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountCollateralCustodyTokenAccount extends string = string,
  TAccountReceivingTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
  TAccountReceivingMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  receivingAccount: Address<TAccountReceivingAccount>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position?: Address<TAccountPosition>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  collateralCustodyTokenAccount: Address<TAccountCollateralCustodyTokenAccount>;
  receivingTokenProgram: Address<TAccountReceivingTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  receivingMint: Address<TAccountReceivingMint>;
  collateralDeltaUsd: RemoveCollateralInstructionDataArgs["collateralDeltaUsd"];
};

export async function getRemoveCollateralInstructionAsync<
  TAccountOwner extends string,
  TAccountReceivingAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountCollateralCustodyTokenAccount extends string,
  TAccountReceivingTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TAccountReceivingMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RemoveCollateralAsyncInput<
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountReceivingTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountReceivingMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RemoveCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountReceivingTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountReceivingMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    receivingAccount: {
      value: input.receivingAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: true,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustodyTokenAccount: {
      value: input.collateralCustodyTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenProgram: {
      value: input.receivingTokenProgram ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
    receivingMint: { value: input.receivingMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.position.value) {
    accounts.position.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 111, 115, 105, 116, 105, 111, 110]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "owner",
            accounts.owner.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "market",
            accounts.market.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("receivingAccount", accounts.receivingAccount),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta(
        "collateralCustodyTokenAccount",
        accounts.collateralCustodyTokenAccount,
      ),
      getAccountMeta("receivingTokenProgram", accounts.receivingTokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
      getAccountMeta("receivingMint", accounts.receivingMint),
    ],
    data: getRemoveCollateralInstructionDataEncoder().encode(
      args as RemoveCollateralInstructionDataArgs,
    ),
    programAddress,
  } as RemoveCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountReceivingTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountReceivingMint
  >);
}

export type RemoveCollateralInput<
  TAccountOwner extends string = string,
  TAccountReceivingAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountCollateralCustodyTokenAccount extends string = string,
  TAccountReceivingTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
  TAccountReceivingMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  receivingAccount: Address<TAccountReceivingAccount>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  collateralCustodyTokenAccount: Address<TAccountCollateralCustodyTokenAccount>;
  receivingTokenProgram: Address<TAccountReceivingTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  receivingMint: Address<TAccountReceivingMint>;
  collateralDeltaUsd: RemoveCollateralInstructionDataArgs["collateralDeltaUsd"];
};

export function getRemoveCollateralInstruction<
  TAccountOwner extends string,
  TAccountReceivingAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountCollateralCustodyTokenAccount extends string,
  TAccountReceivingTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TAccountReceivingMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RemoveCollateralInput<
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountReceivingTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountReceivingMint
  >,
  config?: { programAddress?: TProgramAddress },
): RemoveCollateralInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountReceivingAccount,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountMarket,
  TAccountTargetCustody,
  TAccountTargetOracleAccount,
  TAccountCollateralCustody,
  TAccountCollateralOracleAccount,
  TAccountCollateralCustodyTokenAccount,
  TAccountReceivingTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountIxSysvar,
  TAccountReceivingMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    receivingAccount: {
      value: input.receivingAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: true,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustodyTokenAccount: {
      value: input.collateralCustodyTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenProgram: {
      value: input.receivingTokenProgram ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
    receivingMint: { value: input.receivingMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("receivingAccount", accounts.receivingAccount),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta(
        "collateralCustodyTokenAccount",
        accounts.collateralCustodyTokenAccount,
      ),
      getAccountMeta("receivingTokenProgram", accounts.receivingTokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
      getAccountMeta("receivingMint", accounts.receivingMint),
    ],
    data: getRemoveCollateralInstructionDataEncoder().encode(
      args as RemoveCollateralInstructionDataArgs,
    ),
    programAddress,
  } as RemoveCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountReceivingTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountReceivingMint
  >);
}

export type ParsedRemoveCollateralInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    receivingAccount: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    pool: TAccountMetas[4];
    position: TAccountMetas[5];
    market: TAccountMetas[6];
    targetCustody: TAccountMetas[7];
    targetOracleAccount: TAccountMetas[8];
    collateralCustody: TAccountMetas[9];
    collateralOracleAccount: TAccountMetas[10];
    collateralCustodyTokenAccount: TAccountMetas[11];
    receivingTokenProgram: TAccountMetas[12];
    eventAuthority: TAccountMetas[13];
    program: TAccountMetas[14];
    ixSysvar: TAccountMetas[15];
    receivingMint: TAccountMetas[16];
  };
  data: RemoveCollateralInstructionData;
};

export function parseRemoveCollateralInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRemoveCollateralInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 17,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      receivingAccount: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      market: getNextAccount(),
      targetCustody: getNextAccount(),
      targetOracleAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralOracleAccount: getNextAccount(),
      collateralCustodyTokenAccount: getNextAccount(),
      receivingTokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      ixSysvar: getNextAccount(),
      receivingMint: getNextAccount(),
    },
    data: getRemoveCollateralInstructionDataDecoder().decode(instruction.data),
  };
}
