/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const WITHDRAW_FEES_DISCRIMINATOR = new Uint8Array([
  198, 212, 171, 109, 144, 215, 174, 89,
]);

export function getWithdrawFeesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    WITHDRAW_FEES_DISCRIMINATOR,
  );
}

export type WithdrawFeesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountProtocolVault extends string | AccountMeta<string> = string,
  TAccountProtocolTokenAccount extends string | AccountMeta<string> = string,
  TAccountReceivingTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountReceivingMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountProtocolVault extends string
        ? WritableAccount<TAccountProtocolVault>
        : TAccountProtocolVault,
      TAccountProtocolTokenAccount extends string
        ? WritableAccount<TAccountProtocolTokenAccount>
        : TAccountProtocolTokenAccount,
      TAccountReceivingTokenAccount extends string
        ? WritableAccount<TAccountReceivingTokenAccount>
        : TAccountReceivingTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountReceivingMint extends string
        ? ReadonlyAccount<TAccountReceivingMint>
        : TAccountReceivingMint,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawFeesInstructionData = { discriminator: ReadonlyUint8Array };

export type WithdrawFeesInstructionDataArgs = {};

export function getWithdrawFeesInstructionDataEncoder(): FixedSizeEncoder<WithdrawFeesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: WITHDRAW_FEES_DISCRIMINATOR }),
  );
}

export function getWithdrawFeesInstructionDataDecoder(): FixedSizeDecoder<WithdrawFeesInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getWithdrawFeesInstructionDataCodec(): FixedSizeCodec<
  WithdrawFeesInstructionDataArgs,
  WithdrawFeesInstructionData
> {
  return combineCodec(
    getWithdrawFeesInstructionDataEncoder(),
    getWithdrawFeesInstructionDataDecoder(),
  );
}

export type WithdrawFeesAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountProtocolVault extends string = string,
  TAccountProtocolTokenAccount extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountReceivingMint extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  protocolVault?: Address<TAccountProtocolVault>;
  protocolTokenAccount?: Address<TAccountProtocolTokenAccount>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  receivingMint: Address<TAccountReceivingMint>;
};

export async function getWithdrawFeesInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountProtocolVault extends string,
  TAccountProtocolTokenAccount extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountReceivingMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: WithdrawFeesAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  WithdrawFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    protocolVault: { value: input.protocolVault ?? null, isWritable: true },
    protocolTokenAccount: {
      value: input.protocolTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    receivingMint: { value: input.receivingMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.protocolVault.value) {
    accounts.protocolVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            112, 114, 111, 116, 111, 99, 111, 108, 95, 118, 97, 117, 108, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.protocolTokenAccount.value) {
    accounts.protocolTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            112, 114, 111, 116, 111, 99, 111, 108, 95, 116, 111, 107, 101, 110,
            95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("protocolVault", accounts.protocolVault),
      getAccountMeta("protocolTokenAccount", accounts.protocolTokenAccount),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("receivingMint", accounts.receivingMint),
    ],
    data: getWithdrawFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as WithdrawFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingMint
  >);
}

export type WithdrawFeesInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountProtocolVault extends string = string,
  TAccountProtocolTokenAccount extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountReceivingMint extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  protocolVault: Address<TAccountProtocolVault>;
  protocolTokenAccount: Address<TAccountProtocolTokenAccount>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  receivingMint: Address<TAccountReceivingMint>;
};

export function getWithdrawFeesInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountProtocolVault extends string,
  TAccountProtocolTokenAccount extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountReceivingMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: WithdrawFeesInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingMint
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawFeesInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountProtocolVault,
  TAccountProtocolTokenAccount,
  TAccountReceivingTokenAccount,
  TAccountTokenProgram,
  TAccountReceivingMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    protocolVault: { value: input.protocolVault ?? null, isWritable: true },
    protocolTokenAccount: {
      value: input.protocolTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    receivingMint: { value: input.receivingMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("protocolVault", accounts.protocolVault),
      getAccountMeta("protocolTokenAccount", accounts.protocolTokenAccount),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("receivingMint", accounts.receivingMint),
    ],
    data: getWithdrawFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as WithdrawFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountProtocolVault,
    TAccountProtocolTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingMint
  >);
}

export type ParsedWithdrawFeesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    protocolVault: TAccountMetas[4];
    protocolTokenAccount: TAccountMetas[5];
    receivingTokenAccount: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    receivingMint: TAccountMetas[8];
  };
  data: WithdrawFeesInstructionData;
};

export function parseWithdrawFeesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWithdrawFeesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      protocolVault: getNextAccount(),
      protocolTokenAccount: getNextAccount(),
      receivingTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      receivingMint: getNextAccount(),
    },
    data: getWithdrawFeesInstructionDataDecoder().decode(instruction.data),
  };
}
