/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const WITHDRAW_INSTANT_FEES_DISCRIMINATOR = new Uint8Array([
  210, 236, 193, 124, 205, 149, 255, 203,
]);

export function getWithdrawInstantFeesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    WITHDRAW_INSTANT_FEES_DISCRIMINATOR,
  );
}

export type WithdrawInstantFeesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountTokenVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountReceivingTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountReceivingTokenMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountTokenVaultTokenAccount extends string
        ? WritableAccount<TAccountTokenVaultTokenAccount>
        : TAccountTokenVaultTokenAccount,
      TAccountReceivingTokenAccount extends string
        ? WritableAccount<TAccountReceivingTokenAccount>
        : TAccountReceivingTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountReceivingTokenMint extends string
        ? ReadonlyAccount<TAccountReceivingTokenMint>
        : TAccountReceivingTokenMint,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawInstantFeesInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type WithdrawInstantFeesInstructionDataArgs = {};

export function getWithdrawInstantFeesInstructionDataEncoder(): FixedSizeEncoder<WithdrawInstantFeesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: WITHDRAW_INSTANT_FEES_DISCRIMINATOR,
    }),
  );
}

export function getWithdrawInstantFeesInstructionDataDecoder(): FixedSizeDecoder<WithdrawInstantFeesInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getWithdrawInstantFeesInstructionDataCodec(): FixedSizeCodec<
  WithdrawInstantFeesInstructionDataArgs,
  WithdrawInstantFeesInstructionData
> {
  return combineCodec(
    getWithdrawInstantFeesInstructionDataEncoder(),
    getWithdrawInstantFeesInstructionDataDecoder(),
  );
}

export type WithdrawInstantFeesAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountReceivingTokenMint extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  perpetuals?: Address<TAccountPerpetuals>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  tokenVault?: Address<TAccountTokenVault>;
  tokenVaultTokenAccount?: Address<TAccountTokenVaultTokenAccount>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  receivingTokenMint: Address<TAccountReceivingTokenMint>;
};

export async function getWithdrawInstantFeesInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountReceivingTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: WithdrawInstantFeesAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  WithdrawInstantFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingTokenMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    receivingTokenMint: {
      value: input.receivingTokenMint ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenVault.value) {
    accounts.tokenVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116]),
        ),
      ],
    });
  }
  if (!accounts.tokenVaultTokenAccount.value) {
    accounts.tokenVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116, 95, 116, 111,
            107, 101, 110, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("receivingTokenMint", accounts.receivingTokenMint),
    ],
    data: getWithdrawInstantFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as WithdrawInstantFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingTokenMint
  >);
}

export type WithdrawInstantFeesInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountReceivingTokenMint extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  perpetuals: Address<TAccountPerpetuals>;
  transferAuthority: Address<TAccountTransferAuthority>;
  tokenVault: Address<TAccountTokenVault>;
  tokenVaultTokenAccount: Address<TAccountTokenVaultTokenAccount>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  receivingTokenMint: Address<TAccountReceivingTokenMint>;
};

export function getWithdrawInstantFeesInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountReceivingTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: WithdrawInstantFeesInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawInstantFeesInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountPerpetuals,
  TAccountTransferAuthority,
  TAccountTokenVault,
  TAccountTokenVaultTokenAccount,
  TAccountReceivingTokenAccount,
  TAccountTokenProgram,
  TAccountReceivingTokenMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    receivingTokenMint: {
      value: input.receivingTokenMint ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("receivingTokenMint", accounts.receivingTokenMint),
    ],
    data: getWithdrawInstantFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as WithdrawInstantFeesInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountReceivingTokenAccount,
    TAccountTokenProgram,
    TAccountReceivingTokenMint
  >);
}

export type ParsedWithdrawInstantFeesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    perpetuals: TAccountMetas[2];
    transferAuthority: TAccountMetas[3];
    tokenVault: TAccountMetas[4];
    tokenVaultTokenAccount: TAccountMetas[5];
    receivingTokenAccount: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    receivingTokenMint: TAccountMetas[8];
  };
  data: WithdrawInstantFeesInstructionData;
};

export function parseWithdrawInstantFeesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWithdrawInstantFeesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      perpetuals: getNextAccount(),
      transferAuthority: getNextAccount(),
      tokenVault: getNextAccount(),
      tokenVaultTokenAccount: getNextAccount(),
      receivingTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      receivingTokenMint: getNextAccount(),
    },
    data: getWithdrawInstantFeesInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
