/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

/** MultisigAccountNotAuthorized: Account is not authorized to sign this instruction */
export const PERPETUALS_ERROR__MULTISIG_ACCOUNT_NOT_AUTHORIZED = 0x1770; // 6000
/** MultisigAlreadySigned: Account has already signed this instruction */
export const PERPETUALS_ERROR__MULTISIG_ALREADY_SIGNED = 0x1771; // 6001
/** MultisigAlreadyExecuted: This instruction has already been executed */
export const PERPETUALS_ERROR__MULTISIG_ALREADY_EXECUTED = 0x1772; // 6002
/** MathOverflow: Overflow in arithmetic operation */
export const PERPETUALS_ERROR__MATH_OVERFLOW = 0x1773; // 6003
/** UnsupportedOracle: Unsupported price oracle */
export const PERPETUALS_ERROR__UNSUPPORTED_ORACLE = 0x1774; // 6004
/** InvalidOracleAccount: Invalid oracle account */
export const PERPETUALS_ERROR__INVALID_ORACLE_ACCOUNT = 0x1775; // 6005
/** InvalidOracleState: Invalid oracle state */
export const PERPETUALS_ERROR__INVALID_ORACLE_STATE = 0x1776; // 6006
/** StaleOraclePrice: Stale oracle price */
export const PERPETUALS_ERROR__STALE_ORACLE_PRICE = 0x1777; // 6007
/** InvalidOraclePrice: Invalid oracle price */
export const PERPETUALS_ERROR__INVALID_ORACLE_PRICE = 0x1778; // 6008
/** InvalidEnvironment: Instruction is not allowed in production */
export const PERPETUALS_ERROR__INVALID_ENVIRONMENT = 0x1779; // 6009
/** InvalidPoolState: Invalid pool state */
export const PERPETUALS_ERROR__INVALID_POOL_STATE = 0x177a; // 6010
/** InvalidCustodyState: Invalid custody state */
export const PERPETUALS_ERROR__INVALID_CUSTODY_STATE = 0x177b; // 6011
/** InvalidMarketState: Invalid Market state */
export const PERPETUALS_ERROR__INVALID_MARKET_STATE = 0x177c; // 6012
/** InvalidCollateralCustody: Invalid collateral custody */
export const PERPETUALS_ERROR__INVALID_COLLATERAL_CUSTODY = 0x177d; // 6013
/** InvalidPositionState: Invalid position state */
export const PERPETUALS_ERROR__INVALID_POSITION_STATE = 0x177e; // 6014
/** InvalidDispensingCustody: Invalid Dispensing Custody */
export const PERPETUALS_ERROR__INVALID_DISPENSING_CUSTODY = 0x177f; // 6015
/** InvalidPerpetualsConfig: Invalid perpetuals config */
export const PERPETUALS_ERROR__INVALID_PERPETUALS_CONFIG = 0x1780; // 6016
/** InvalidPoolConfig: Invalid pool config */
export const PERPETUALS_ERROR__INVALID_POOL_CONFIG = 0x1781; // 6017
/** InvalidCustodyConfig: Invalid custody config */
export const PERPETUALS_ERROR__INVALID_CUSTODY_CONFIG = 0x1782; // 6018
/** InsufficientAmountReturned: Insufficient token amount returned */
export const PERPETUALS_ERROR__INSUFFICIENT_AMOUNT_RETURNED = 0x1783; // 6019
/** MaxPriceSlippage: Price slippage limit exceeded */
export const PERPETUALS_ERROR__MAX_PRICE_SLIPPAGE = 0x1784; // 6020
/** MaxLeverage: Position leverage limit exceeded */
export const PERPETUALS_ERROR__MAX_LEVERAGE = 0x1785; // 6021
/** MaxInitLeverage: Position initial leverage limit exceeded */
export const PERPETUALS_ERROR__MAX_INIT_LEVERAGE = 0x1786; // 6022
/** MinLeverage: Position leverage less than minimum */
export const PERPETUALS_ERROR__MIN_LEVERAGE = 0x1787; // 6023
/** CustodyAmountLimit: Custody amount limit exceeded */
export const PERPETUALS_ERROR__CUSTODY_AMOUNT_LIMIT = 0x1788; // 6024
/** PositionAmountLimit: Position amount limit exceeded */
export const PERPETUALS_ERROR__POSITION_AMOUNT_LIMIT = 0x1789; // 6025
/** TokenRatioOutOfRange: Token ratio out of range */
export const PERPETUALS_ERROR__TOKEN_RATIO_OUT_OF_RANGE = 0x178a; // 6026
/** UnsupportedToken: Token is not supported */
export const PERPETUALS_ERROR__UNSUPPORTED_TOKEN = 0x178b; // 6027
/** UnsupportedCustody: Custody is not supported */
export const PERPETUALS_ERROR__UNSUPPORTED_CUSTODY = 0x178c; // 6028
/** UnsupportedPool: Pool is not supported */
export const PERPETUALS_ERROR__UNSUPPORTED_POOL = 0x178d; // 6029
/** UnsupportedMarket: Market is not supported */
export const PERPETUALS_ERROR__UNSUPPORTED_MARKET = 0x178e; // 6030
/** InstructionNotAllowed: Instruction is not allowed at this time */
export const PERPETUALS_ERROR__INSTRUCTION_NOT_ALLOWED = 0x178f; // 6031
/** MaxUtilization: Token utilization limit exceeded */
export const PERPETUALS_ERROR__MAX_UTILIZATION = 0x1790; // 6032
/** CloseOnlyMode: Close-only mode activated */
export const PERPETUALS_ERROR__CLOSE_ONLY_MODE = 0x1791; // 6033
/** MinCollateral: Minimum collateral limit breached */
export const PERPETUALS_ERROR__MIN_COLLATERAL = 0x1792; // 6034
/** PermissionlessOracleMissingSignature: Permissionless oracle update must be preceded by Ed25519 signature verification instruction */
export const PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MISSING_SIGNATURE = 0x1793; // 6035
/** PermissionlessOracleMalformedEd25519Data: Ed25519 signature verification data does not match expected format */
export const PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MALFORMED_ED25519_DATA = 0x1794; // 6036
/** PermissionlessOracleSignerMismatch: Ed25519 signature was not signed by the oracle authority */
export const PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_SIGNER_MISMATCH = 0x1795; // 6037
/** PermissionlessOracleMessageMismatch: Signed message does not match instruction params */
export const PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MESSAGE_MISMATCH = 0x1796; // 6038
/** ExponentMismatch: Exponent Mismatch betweeen operands */
export const PERPETUALS_ERROR__EXPONENT_MISMATCH = 0x1797; // 6039
/** CloseRatio: Invalid Close Ratio */
export const PERPETUALS_ERROR__CLOSE_RATIO = 0x1798; // 6040
/** InsufficientStakeAmount: Insufficient LP tokens staked */
export const PERPETUALS_ERROR__INSUFFICIENT_STAKE_AMOUNT = 0x1799; // 6041
/** InvalidFeeDeltas: Invalid Fee Deltas */
export const PERPETUALS_ERROR__INVALID_FEE_DELTAS = 0x179a; // 6042
/** InvalidFeeDistributionCustody: Invalid Fee Distrivution Custody */
export const PERPETUALS_ERROR__INVALID_FEE_DISTRIBUTION_CUSTODY = 0x179b; // 6043
/** InvalidCollection: Invalid Collection */
export const PERPETUALS_ERROR__INVALID_COLLECTION = 0x179c; // 6044
/** InvalidOwner: Owner of Token Account does not match */
export const PERPETUALS_ERROR__INVALID_OWNER = 0x179d; // 6045
/** InvalidAccess: Only nft holders or referred users can trade */
export const PERPETUALS_ERROR__INVALID_ACCESS = 0x179e; // 6046
/** TokenStakeAccountMismatch: Token Stake account doesnot match referral account */
export const PERPETUALS_ERROR__TOKEN_STAKE_ACCOUNT_MISMATCH = 0x179f; // 6047
/** MaxDepostsReached: Max deposits reached */
export const PERPETUALS_ERROR__MAX_DEPOSTS_REACHED = 0x17a0; // 6048
/** InvalidStopLossPrice: Invalid Stop Loss price */
export const PERPETUALS_ERROR__INVALID_STOP_LOSS_PRICE = 0x17a1; // 6049
/** InvalidTakeProfitPrice: Invalid Take Profit price */
export const PERPETUALS_ERROR__INVALID_TAKE_PROFIT_PRICE = 0x17a2; // 6050
/** ExposureLimitExceeded: Max exposure limit exceeded for the market */
export const PERPETUALS_ERROR__EXPOSURE_LIMIT_EXCEEDED = 0x17a3; // 6051
/** MaxStopLossOrders: Stop Loss limit exhausted */
export const PERPETUALS_ERROR__MAX_STOP_LOSS_ORDERS = 0x17a4; // 6052
/** MaxTakeProfitOrders: Take Profit limit exhausted */
export const PERPETUALS_ERROR__MAX_TAKE_PROFIT_ORDERS = 0x17a5; // 6053
/** MaxOpenOrder: Open order limit exhausted */
export const PERPETUALS_ERROR__MAX_OPEN_ORDER = 0x17a6; // 6054
/** InvalidOrder: Invalid Order */
export const PERPETUALS_ERROR__INVALID_ORDER = 0x17a7; // 6055
/** InvalidLimitPrice: Invalid Limit price */
export const PERPETUALS_ERROR__INVALID_LIMIT_PRICE = 0x17a8; // 6056
/** MinReserve: Minimum reserve limit breached */
export const PERPETUALS_ERROR__MIN_RESERVE = 0x17a9; // 6057
/** MaxWithdrawTokenRequest: Withdraw Token Request limit exhausted */
export const PERPETUALS_ERROR__MAX_WITHDRAW_TOKEN_REQUEST = 0x17aa; // 6058
/** InvalidRewardDistribution: Invalid Reward Distribution */
export const PERPETUALS_ERROR__INVALID_REWARD_DISTRIBUTION = 0x17ab; // 6059
/** LpPriceOutOfBounds: Liquidity Token price is out of bounds */
export const PERPETUALS_ERROR__LP_PRICE_OUT_OF_BOUNDS = 0x17ac; // 6060
/** InsufficientRebateReserves: Insufficient rebate reserves */
export const PERPETUALS_ERROR__INSUFFICIENT_REBATE_RESERVES = 0x17ad; // 6061
/** OraclePenaltyAlreadySet: Oracle penalty already set on this position */
export const PERPETUALS_ERROR__ORACLE_PENALTY_ALREADY_SET = 0x17ae; // 6062
/** InvalidLazerMessage: Invalid Lazer message */
export const PERPETUALS_ERROR__INVALID_LAZER_MESSAGE = 0x17af; // 6063
/** InvalidLazerPayload: Invalid Lazer payload */
export const PERPETUALS_ERROR__INVALID_LAZER_PAYLOAD = 0x17b0; // 6064
/** InvalidLazerChannel: Invalid Lazer channel */
export const PERPETUALS_ERROR__INVALID_LAZER_CHANNEL = 0x17b1; // 6065
/** InvalidLazerTimestamp: Invalid Lazer timestamp */
export const PERPETUALS_ERROR__INVALID_LAZER_TIMESTAMP = 0x17b2; // 6066
/** InvalidWithdrawal: Invalid amount for withdrawal */
export const PERPETUALS_ERROR__INVALID_WITHDRAWAL = 0x17b3; // 6067
/** InvalidWithdrawRequestId: Invalid withdraw request ID */
export const PERPETUALS_ERROR__INVALID_WITHDRAW_REQUEST_ID = 0x17b4; // 6068
/** InvalidWhitelistAccount: Invalid whitelist account */
export const PERPETUALS_ERROR__INVALID_WHITELIST_ACCOUNT = 0x17b5; // 6069
/** BackupPriceDeviation: Backup price out of bounds */
export const PERPETUALS_ERROR__BACKUP_PRICE_DEVIATION = 0x17b6; // 6070
/** OracleConfidenceOutOfBounds: Oracle confidence out of bounds */
export const PERPETUALS_ERROR__ORACLE_CONFIDENCE_OUT_OF_BOUNDS = 0x17b7; // 6071

export type PerpetualsError =
  | typeof PERPETUALS_ERROR__BACKUP_PRICE_DEVIATION
  | typeof PERPETUALS_ERROR__CLOSE_ONLY_MODE
  | typeof PERPETUALS_ERROR__CLOSE_RATIO
  | typeof PERPETUALS_ERROR__CUSTODY_AMOUNT_LIMIT
  | typeof PERPETUALS_ERROR__EXPONENT_MISMATCH
  | typeof PERPETUALS_ERROR__EXPOSURE_LIMIT_EXCEEDED
  | typeof PERPETUALS_ERROR__INSTRUCTION_NOT_ALLOWED
  | typeof PERPETUALS_ERROR__INSUFFICIENT_AMOUNT_RETURNED
  | typeof PERPETUALS_ERROR__INSUFFICIENT_REBATE_RESERVES
  | typeof PERPETUALS_ERROR__INSUFFICIENT_STAKE_AMOUNT
  | typeof PERPETUALS_ERROR__INVALID_ACCESS
  | typeof PERPETUALS_ERROR__INVALID_COLLATERAL_CUSTODY
  | typeof PERPETUALS_ERROR__INVALID_COLLECTION
  | typeof PERPETUALS_ERROR__INVALID_CUSTODY_CONFIG
  | typeof PERPETUALS_ERROR__INVALID_CUSTODY_STATE
  | typeof PERPETUALS_ERROR__INVALID_DISPENSING_CUSTODY
  | typeof PERPETUALS_ERROR__INVALID_ENVIRONMENT
  | typeof PERPETUALS_ERROR__INVALID_FEE_DELTAS
  | typeof PERPETUALS_ERROR__INVALID_FEE_DISTRIBUTION_CUSTODY
  | typeof PERPETUALS_ERROR__INVALID_LAZER_CHANNEL
  | typeof PERPETUALS_ERROR__INVALID_LAZER_MESSAGE
  | typeof PERPETUALS_ERROR__INVALID_LAZER_PAYLOAD
  | typeof PERPETUALS_ERROR__INVALID_LAZER_TIMESTAMP
  | typeof PERPETUALS_ERROR__INVALID_LIMIT_PRICE
  | typeof PERPETUALS_ERROR__INVALID_MARKET_STATE
  | typeof PERPETUALS_ERROR__INVALID_ORACLE_ACCOUNT
  | typeof PERPETUALS_ERROR__INVALID_ORACLE_PRICE
  | typeof PERPETUALS_ERROR__INVALID_ORACLE_STATE
  | typeof PERPETUALS_ERROR__INVALID_ORDER
  | typeof PERPETUALS_ERROR__INVALID_OWNER
  | typeof PERPETUALS_ERROR__INVALID_PERPETUALS_CONFIG
  | typeof PERPETUALS_ERROR__INVALID_POOL_CONFIG
  | typeof PERPETUALS_ERROR__INVALID_POOL_STATE
  | typeof PERPETUALS_ERROR__INVALID_POSITION_STATE
  | typeof PERPETUALS_ERROR__INVALID_REWARD_DISTRIBUTION
  | typeof PERPETUALS_ERROR__INVALID_STOP_LOSS_PRICE
  | typeof PERPETUALS_ERROR__INVALID_TAKE_PROFIT_PRICE
  | typeof PERPETUALS_ERROR__INVALID_WHITELIST_ACCOUNT
  | typeof PERPETUALS_ERROR__INVALID_WITHDRAWAL
  | typeof PERPETUALS_ERROR__INVALID_WITHDRAW_REQUEST_ID
  | typeof PERPETUALS_ERROR__LP_PRICE_OUT_OF_BOUNDS
  | typeof PERPETUALS_ERROR__MATH_OVERFLOW
  | typeof PERPETUALS_ERROR__MAX_DEPOSTS_REACHED
  | typeof PERPETUALS_ERROR__MAX_INIT_LEVERAGE
  | typeof PERPETUALS_ERROR__MAX_LEVERAGE
  | typeof PERPETUALS_ERROR__MAX_OPEN_ORDER
  | typeof PERPETUALS_ERROR__MAX_PRICE_SLIPPAGE
  | typeof PERPETUALS_ERROR__MAX_STOP_LOSS_ORDERS
  | typeof PERPETUALS_ERROR__MAX_TAKE_PROFIT_ORDERS
  | typeof PERPETUALS_ERROR__MAX_UTILIZATION
  | typeof PERPETUALS_ERROR__MAX_WITHDRAW_TOKEN_REQUEST
  | typeof PERPETUALS_ERROR__MIN_COLLATERAL
  | typeof PERPETUALS_ERROR__MIN_LEVERAGE
  | typeof PERPETUALS_ERROR__MIN_RESERVE
  | typeof PERPETUALS_ERROR__MULTISIG_ACCOUNT_NOT_AUTHORIZED
  | typeof PERPETUALS_ERROR__MULTISIG_ALREADY_EXECUTED
  | typeof PERPETUALS_ERROR__MULTISIG_ALREADY_SIGNED
  | typeof PERPETUALS_ERROR__ORACLE_CONFIDENCE_OUT_OF_BOUNDS
  | typeof PERPETUALS_ERROR__ORACLE_PENALTY_ALREADY_SET
  | typeof PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MALFORMED_ED25519_DATA
  | typeof PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MESSAGE_MISMATCH
  | typeof PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MISSING_SIGNATURE
  | typeof PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_SIGNER_MISMATCH
  | typeof PERPETUALS_ERROR__POSITION_AMOUNT_LIMIT
  | typeof PERPETUALS_ERROR__STALE_ORACLE_PRICE
  | typeof PERPETUALS_ERROR__TOKEN_RATIO_OUT_OF_RANGE
  | typeof PERPETUALS_ERROR__TOKEN_STAKE_ACCOUNT_MISMATCH
  | typeof PERPETUALS_ERROR__UNSUPPORTED_CUSTODY
  | typeof PERPETUALS_ERROR__UNSUPPORTED_MARKET
  | typeof PERPETUALS_ERROR__UNSUPPORTED_ORACLE
  | typeof PERPETUALS_ERROR__UNSUPPORTED_POOL
  | typeof PERPETUALS_ERROR__UNSUPPORTED_TOKEN;

let perpetualsErrorMessages: Record<PerpetualsError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  perpetualsErrorMessages = {
    [PERPETUALS_ERROR__BACKUP_PRICE_DEVIATION]: `Backup price out of bounds`,
    [PERPETUALS_ERROR__CLOSE_ONLY_MODE]: `Close-only mode activated`,
    [PERPETUALS_ERROR__CLOSE_RATIO]: `Invalid Close Ratio`,
    [PERPETUALS_ERROR__CUSTODY_AMOUNT_LIMIT]: `Custody amount limit exceeded`,
    [PERPETUALS_ERROR__EXPONENT_MISMATCH]: `Exponent Mismatch betweeen operands`,
    [PERPETUALS_ERROR__EXPOSURE_LIMIT_EXCEEDED]: `Max exposure limit exceeded for the market`,
    [PERPETUALS_ERROR__INSTRUCTION_NOT_ALLOWED]: `Instruction is not allowed at this time`,
    [PERPETUALS_ERROR__INSUFFICIENT_AMOUNT_RETURNED]: `Insufficient token amount returned`,
    [PERPETUALS_ERROR__INSUFFICIENT_REBATE_RESERVES]: `Insufficient rebate reserves`,
    [PERPETUALS_ERROR__INSUFFICIENT_STAKE_AMOUNT]: `Insufficient LP tokens staked`,
    [PERPETUALS_ERROR__INVALID_ACCESS]: `Only nft holders or referred users can trade`,
    [PERPETUALS_ERROR__INVALID_COLLATERAL_CUSTODY]: `Invalid collateral custody`,
    [PERPETUALS_ERROR__INVALID_COLLECTION]: `Invalid Collection`,
    [PERPETUALS_ERROR__INVALID_CUSTODY_CONFIG]: `Invalid custody config`,
    [PERPETUALS_ERROR__INVALID_CUSTODY_STATE]: `Invalid custody state`,
    [PERPETUALS_ERROR__INVALID_DISPENSING_CUSTODY]: `Invalid Dispensing Custody`,
    [PERPETUALS_ERROR__INVALID_ENVIRONMENT]: `Instruction is not allowed in production`,
    [PERPETUALS_ERROR__INVALID_FEE_DELTAS]: `Invalid Fee Deltas`,
    [PERPETUALS_ERROR__INVALID_FEE_DISTRIBUTION_CUSTODY]: `Invalid Fee Distrivution Custody`,
    [PERPETUALS_ERROR__INVALID_LAZER_CHANNEL]: `Invalid Lazer channel`,
    [PERPETUALS_ERROR__INVALID_LAZER_MESSAGE]: `Invalid Lazer message`,
    [PERPETUALS_ERROR__INVALID_LAZER_PAYLOAD]: `Invalid Lazer payload`,
    [PERPETUALS_ERROR__INVALID_LAZER_TIMESTAMP]: `Invalid Lazer timestamp`,
    [PERPETUALS_ERROR__INVALID_LIMIT_PRICE]: `Invalid Limit price`,
    [PERPETUALS_ERROR__INVALID_MARKET_STATE]: `Invalid Market state`,
    [PERPETUALS_ERROR__INVALID_ORACLE_ACCOUNT]: `Invalid oracle account`,
    [PERPETUALS_ERROR__INVALID_ORACLE_PRICE]: `Invalid oracle price`,
    [PERPETUALS_ERROR__INVALID_ORACLE_STATE]: `Invalid oracle state`,
    [PERPETUALS_ERROR__INVALID_ORDER]: `Invalid Order`,
    [PERPETUALS_ERROR__INVALID_OWNER]: `Owner of Token Account does not match`,
    [PERPETUALS_ERROR__INVALID_PERPETUALS_CONFIG]: `Invalid perpetuals config`,
    [PERPETUALS_ERROR__INVALID_POOL_CONFIG]: `Invalid pool config`,
    [PERPETUALS_ERROR__INVALID_POOL_STATE]: `Invalid pool state`,
    [PERPETUALS_ERROR__INVALID_POSITION_STATE]: `Invalid position state`,
    [PERPETUALS_ERROR__INVALID_REWARD_DISTRIBUTION]: `Invalid Reward Distribution`,
    [PERPETUALS_ERROR__INVALID_STOP_LOSS_PRICE]: `Invalid Stop Loss price`,
    [PERPETUALS_ERROR__INVALID_TAKE_PROFIT_PRICE]: `Invalid Take Profit price`,
    [PERPETUALS_ERROR__INVALID_WHITELIST_ACCOUNT]: `Invalid whitelist account`,
    [PERPETUALS_ERROR__INVALID_WITHDRAWAL]: `Invalid amount for withdrawal`,
    [PERPETUALS_ERROR__INVALID_WITHDRAW_REQUEST_ID]: `Invalid withdraw request ID`,
    [PERPETUALS_ERROR__LP_PRICE_OUT_OF_BOUNDS]: `Liquidity Token price is out of bounds`,
    [PERPETUALS_ERROR__MATH_OVERFLOW]: `Overflow in arithmetic operation`,
    [PERPETUALS_ERROR__MAX_DEPOSTS_REACHED]: `Max deposits reached`,
    [PERPETUALS_ERROR__MAX_INIT_LEVERAGE]: `Position initial leverage limit exceeded`,
    [PERPETUALS_ERROR__MAX_LEVERAGE]: `Position leverage limit exceeded`,
    [PERPETUALS_ERROR__MAX_OPEN_ORDER]: `Open order limit exhausted`,
    [PERPETUALS_ERROR__MAX_PRICE_SLIPPAGE]: `Price slippage limit exceeded`,
    [PERPETUALS_ERROR__MAX_STOP_LOSS_ORDERS]: `Stop Loss limit exhausted`,
    [PERPETUALS_ERROR__MAX_TAKE_PROFIT_ORDERS]: `Take Profit limit exhausted`,
    [PERPETUALS_ERROR__MAX_UTILIZATION]: `Token utilization limit exceeded`,
    [PERPETUALS_ERROR__MAX_WITHDRAW_TOKEN_REQUEST]: `Withdraw Token Request limit exhausted`,
    [PERPETUALS_ERROR__MIN_COLLATERAL]: `Minimum collateral limit breached`,
    [PERPETUALS_ERROR__MIN_LEVERAGE]: `Position leverage less than minimum`,
    [PERPETUALS_ERROR__MIN_RESERVE]: `Minimum reserve limit breached`,
    [PERPETUALS_ERROR__MULTISIG_ACCOUNT_NOT_AUTHORIZED]: `Account is not authorized to sign this instruction`,
    [PERPETUALS_ERROR__MULTISIG_ALREADY_EXECUTED]: `This instruction has already been executed`,
    [PERPETUALS_ERROR__MULTISIG_ALREADY_SIGNED]: `Account has already signed this instruction`,
    [PERPETUALS_ERROR__ORACLE_CONFIDENCE_OUT_OF_BOUNDS]: `Oracle confidence out of bounds`,
    [PERPETUALS_ERROR__ORACLE_PENALTY_ALREADY_SET]: `Oracle penalty already set on this position`,
    [PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MALFORMED_ED25519_DATA]: `Ed25519 signature verification data does not match expected format`,
    [PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MESSAGE_MISMATCH]: `Signed message does not match instruction params`,
    [PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_MISSING_SIGNATURE]: `Permissionless oracle update must be preceded by Ed25519 signature verification instruction`,
    [PERPETUALS_ERROR__PERMISSIONLESS_ORACLE_SIGNER_MISMATCH]: `Ed25519 signature was not signed by the oracle authority`,
    [PERPETUALS_ERROR__POSITION_AMOUNT_LIMIT]: `Position amount limit exceeded`,
    [PERPETUALS_ERROR__STALE_ORACLE_PRICE]: `Stale oracle price`,
    [PERPETUALS_ERROR__TOKEN_RATIO_OUT_OF_RANGE]: `Token ratio out of range`,
    [PERPETUALS_ERROR__TOKEN_STAKE_ACCOUNT_MISMATCH]: `Token Stake account doesnot match referral account`,
    [PERPETUALS_ERROR__UNSUPPORTED_CUSTODY]: `Custody is not supported`,
    [PERPETUALS_ERROR__UNSUPPORTED_MARKET]: `Market is not supported`,
    [PERPETUALS_ERROR__UNSUPPORTED_ORACLE]: `Unsupported price oracle`,
    [PERPETUALS_ERROR__UNSUPPORTED_POOL]: `Pool is not supported`,
    [PERPETUALS_ERROR__UNSUPPORTED_TOKEN]: `Token is not supported`,
  };
}

export function getPerpetualsErrorMessage(code: PerpetualsError): string {
  if (process.env.NODE_ENV !== "production") {
    return (perpetualsErrorMessages as Record<PerpetualsError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isPerpetualsError<TProgramErrorCode extends PerpetualsError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    PERPETUALS_PROGRAM_ADDRESS,
    code,
  );
}
