// codama.mjs — Generate Kit-native clients from Anchor IDLs
//
// Usage:
//   node codama.mjs                     # Generate Phalnx (default)
//   node codama.mjs --protocol=phalnx   # Generate Phalnx explicitly
//   node codama.mjs --protocol=flash-trade  # Generate Flash Trade
//   node codama.mjs --protocol=kamino       # Generate Kamino
//   node codama.mjs --all                   # Generate all protocols

import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import { createFromRoot } from "codama";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdtempSync, cpSync, rmSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Protocol Registry ──────────────────────────────────────────────────────

const PROTOCOLS = {
  phalnx: {
    idlPath: join(__dirname, "..", "..", "target", "idl", "phalnx.json"),
    outputDir: join(__dirname, "src", "generated"),
    generateEventMap: true,
  },
  "flash-trade": {
    idlPath: join(__dirname, "idls", "perpetuals.json"),
    outputDir: join(__dirname, "src", "generated", "protocols", "flash-trade"),
    generateEventMap: false,
  },
  kamino: {
    idlPath: join(__dirname, "idls", "kamino-lending.json"),
    outputDir: join(__dirname, "src", "generated", "protocols", "kamino"),
    generateEventMap: false,
  },
};

// ─── CLI Parsing ─────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const allFlag = args.includes("--all");
const protocolArg = args.find((a) => a.startsWith("--protocol="))?.split("=")[1];

let protocolsToGenerate;
if (allFlag) {
  protocolsToGenerate = Object.keys(PROTOCOLS);
} else if (protocolArg) {
  if (!PROTOCOLS[protocolArg]) {
    console.error(`Unknown protocol: ${protocolArg}. Available: ${Object.keys(PROTOCOLS).join(", ")}`);
    process.exit(1);
  }
  protocolsToGenerate = [protocolArg];
} else {
  // Default: phalnx only (backwards compatible)
  protocolsToGenerate = ["phalnx"];
}

// ─── Generation ──────────────────────────────────────────────────────────────

for (const protocolName of protocolsToGenerate) {
  const config = PROTOCOLS[protocolName];

  if (!existsSync(config.idlPath)) {
    console.error(`IDL not found: ${config.idlPath}`);
    process.exit(1);
  }

  console.log(`\n─── Generating ${protocolName} ───`);

  const anchorIdl = JSON.parse(readFileSync(config.idlPath, "utf-8"));
  const codama = createFromRoot(rootNodeFromAnchor(anchorIdl));

  // Render to temp dir, then copy src/generated/ to output dir
  const tempDir = mkdtempSync(join(tmpdir(), `codama-${protocolName}-`));
  await codama.accept(renderVisitor(tempDir));

  // For protocol sub-dirs, ensure parent exists
  rmSync(config.outputDir, { recursive: true, force: true });
  const parentDir = dirname(config.outputDir);
  if (!existsSync(parentDir)) {
    mkdirSync(parentDir, { recursive: true });
  }
  cpSync(join(tempDir, "src", "generated"), config.outputDir, { recursive: true });
  rmSync(tempDir, { recursive: true, force: true });

  const ixCount = anchorIdl.instructions?.length ?? 0;
  const acctCount = anchorIdl.accounts?.length ?? 0;
  console.log(`  Generated: ${ixCount} instructions, ${acctCount} accounts → ${config.outputDir}`);

  // ─── Event discriminator map (Phalnx only) ──────────────────────────────
  if (config.generateEventMap) {
    const events = anchorIdl.events ?? [];
    if (events.length > 0) {
      const entries = events.map((evt) => {
        const disc = createHash("sha256")
          .update(`event:${evt.name}`)
          .digest()
          .subarray(0, 8)
          .toString("hex");
        return `  "${disc}": "${evt.name}",`;
      });

      const content = `// AUTO-GENERATED by codama.mjs — do not edit manually.
// Re-run \`pnpm run codama\` after any Rust event changes.
//
// Source: target/idl/phalnx.json (${events.length} events)
// Discriminator = SHA256("event:<EventName>")[0..8]

export const EVENT_DISCRIMINATOR_MAP: Record<string, string> = {
${entries.join("\n")}
};
`;

      const eventMapPath = join(config.outputDir, "event-discriminators.ts");
      writeFileSync(eventMapPath, content, "utf-8");
      console.log(`  Event discriminator map: ${events.length} events`);
    }
  }
}

console.log("\nDone.");
