/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const MULTISIG_DISCRIMINATOR = new Uint8Array([
  224, 116, 121, 186, 68, 161, 79, 236,
]);

export function getMultisigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MULTISIG_DISCRIMINATOR);
}

export type Multisig = {
  discriminator: ReadonlyUint8Array;
  numSigners: number;
  numSigned: number;
  minSignatures: number;
  instructionAccountsLen: number;
  instructionDataLen: number;
  instructionHash: bigint;
  signers: Array<Address>;
  signed: ReadonlyUint8Array;
  bump: number;
};

export type MultisigArgs = {
  numSigners: number;
  numSigned: number;
  minSignatures: number;
  instructionAccountsLen: number;
  instructionDataLen: number;
  instructionHash: number | bigint;
  signers: Array<Address>;
  signed: ReadonlyUint8Array;
  bump: number;
};

/** Gets the encoder for {@link MultisigArgs} account data. */
export function getMultisigEncoder(): FixedSizeEncoder<MultisigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["numSigners", getU8Encoder()],
      ["numSigned", getU8Encoder()],
      ["minSignatures", getU8Encoder()],
      ["instructionAccountsLen", getU8Encoder()],
      ["instructionDataLen", getU16Encoder()],
      ["instructionHash", getU64Encoder()],
      ["signers", getArrayEncoder(getAddressEncoder(), { size: 6 })],
      ["signed", fixEncoderSize(getBytesEncoder(), 6)],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MULTISIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Multisig} account data. */
export function getMultisigDecoder(): FixedSizeDecoder<Multisig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["numSigners", getU8Decoder()],
    ["numSigned", getU8Decoder()],
    ["minSignatures", getU8Decoder()],
    ["instructionAccountsLen", getU8Decoder()],
    ["instructionDataLen", getU16Decoder()],
    ["instructionHash", getU64Decoder()],
    ["signers", getArrayDecoder(getAddressDecoder(), { size: 6 })],
    ["signed", fixDecoderSize(getBytesDecoder(), 6)],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Multisig} account data. */
export function getMultisigCodec(): FixedSizeCodec<MultisigArgs, Multisig> {
  return combineCodec(getMultisigEncoder(), getMultisigDecoder());
}

export function decodeMultisig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Multisig, TAddress>;
export function decodeMultisig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Multisig, TAddress>;
export function decodeMultisig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Multisig, TAddress> | MaybeAccount<Multisig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMultisigDecoder(),
  );
}

export async function fetchMultisig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Multisig, TAddress>> {
  const maybeAccount = await fetchMaybeMultisig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMultisig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Multisig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMultisig(maybeAccount);
}

export async function fetchAllMultisig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Multisig>[]> {
  const maybeAccounts = await fetchAllMaybeMultisig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMultisig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Multisig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMultisig(maybeAccount));
}

export function getMultisigSize(): number {
  return 221;
}
