/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getLimitOrderDecoder,
  getLimitOrderEncoder,
  getTriggerOrderDecoder,
  getTriggerOrderEncoder,
  type LimitOrder,
  type LimitOrderArgs,
  type TriggerOrder,
  type TriggerOrderArgs,
} from "../types/index.js";

export const ORDER_DISCRIMINATOR = new Uint8Array([
  134, 173, 223, 185, 77, 86, 28, 51,
]);

export function getOrderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ORDER_DISCRIMINATOR);
}

export type Order = {
  discriminator: ReadonlyUint8Array;
  owner: Address;
  market: Address;
  limitOrders: Array<LimitOrder>;
  takeProfitOrders: Array<TriggerOrder>;
  stopLossOrders: Array<TriggerOrder>;
  isInitialised: boolean;
  isActive: boolean;
  openSl: number;
  openTp: number;
  inactiveSl: number;
  inactiveTp: number;
  activeOrders: number;
  bump: number;
  referenceTimestamp: bigint;
  executionCount: bigint;
  padding: Array<bigint>;
};

export type OrderArgs = {
  owner: Address;
  market: Address;
  limitOrders: Array<LimitOrderArgs>;
  takeProfitOrders: Array<TriggerOrderArgs>;
  stopLossOrders: Array<TriggerOrderArgs>;
  isInitialised: boolean;
  isActive: boolean;
  openSl: number;
  openTp: number;
  inactiveSl: number;
  inactiveTp: number;
  activeOrders: number;
  bump: number;
  referenceTimestamp: number | bigint;
  executionCount: number | bigint;
  padding: Array<number | bigint>;
};

/** Gets the encoder for {@link OrderArgs} account data. */
export function getOrderEncoder(): FixedSizeEncoder<OrderArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["owner", getAddressEncoder()],
      ["market", getAddressEncoder()],
      ["limitOrders", getArrayEncoder(getLimitOrderEncoder(), { size: 5 })],
      [
        "takeProfitOrders",
        getArrayEncoder(getTriggerOrderEncoder(), { size: 5 }),
      ],
      [
        "stopLossOrders",
        getArrayEncoder(getTriggerOrderEncoder(), { size: 5 }),
      ],
      ["isInitialised", getBooleanEncoder()],
      ["isActive", getBooleanEncoder()],
      ["openSl", getU8Encoder()],
      ["openTp", getU8Encoder()],
      ["inactiveSl", getU8Encoder()],
      ["inactiveTp", getU8Encoder()],
      ["activeOrders", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["referenceTimestamp", getI64Encoder()],
      ["executionCount", getU64Encoder()],
      ["padding", getArrayEncoder(getU64Encoder(), { size: 6 })],
    ]),
    (value) => ({ ...value, discriminator: ORDER_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Order} account data. */
export function getOrderDecoder(): FixedSizeDecoder<Order> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["limitOrders", getArrayDecoder(getLimitOrderDecoder(), { size: 5 })],
    [
      "takeProfitOrders",
      getArrayDecoder(getTriggerOrderDecoder(), { size: 5 }),
    ],
    ["stopLossOrders", getArrayDecoder(getTriggerOrderDecoder(), { size: 5 })],
    ["isInitialised", getBooleanDecoder()],
    ["isActive", getBooleanDecoder()],
    ["openSl", getU8Decoder()],
    ["openTp", getU8Decoder()],
    ["inactiveSl", getU8Decoder()],
    ["inactiveTp", getU8Decoder()],
    ["activeOrders", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["referenceTimestamp", getI64Decoder()],
    ["executionCount", getU64Decoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 6 })],
  ]);
}

/** Gets the codec for {@link Order} account data. */
export function getOrderCodec(): FixedSizeCodec<OrderArgs, Order> {
  return combineCodec(getOrderEncoder(), getOrderDecoder());
}

export function decodeOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Order, TAddress>;
export function decodeOrder<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Order, TAddress>;
export function decodeOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Order, TAddress> | MaybeAccount<Order, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOrderDecoder(),
  );
}

export async function fetchOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Order, TAddress>> {
  const maybeAccount = await fetchMaybeOrder(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Order, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOrder(maybeAccount);
}

export async function fetchAllOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Order>[]> {
  const maybeAccounts = await fetchAllMaybeOrder(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Order>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeOrder(maybeAccount));
}

export function getOrderSize(): number {
  return 624;
}
