/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const COLLECT_REBATE_DISCRIMINATOR = new Uint8Array([
  211, 159, 122, 61, 195, 246, 132, 15,
]);

export function getCollectRebateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    COLLECT_REBATE_DISCRIMINATOR,
  );
}

export type CollectRebateInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountReceivingTokenAccount extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountRebateVault extends string | AccountMeta<string> = string,
  TAccountRebateTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenStakeAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountReceivingTokenMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountReceivingTokenAccount extends string
        ? WritableAccount<TAccountReceivingTokenAccount>
        : TAccountReceivingTokenAccount,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountRebateVault extends string
        ? WritableAccount<TAccountRebateVault>
        : TAccountRebateVault,
      TAccountRebateTokenAccount extends string
        ? WritableAccount<TAccountRebateTokenAccount>
        : TAccountRebateTokenAccount,
      TAccountTokenStakeAccount extends string
        ? WritableAccount<TAccountTokenStakeAccount>
        : TAccountTokenStakeAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountReceivingTokenMint extends string
        ? ReadonlyAccount<TAccountReceivingTokenMint>
        : TAccountReceivingTokenMint,
      ...TRemainingAccounts,
    ]
  >;

export type CollectRebateInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CollectRebateInstructionDataArgs = {};

export function getCollectRebateInstructionDataEncoder(): FixedSizeEncoder<CollectRebateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: COLLECT_REBATE_DISCRIMINATOR }),
  );
}

export function getCollectRebateInstructionDataDecoder(): FixedSizeDecoder<CollectRebateInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCollectRebateInstructionDataCodec(): FixedSizeCodec<
  CollectRebateInstructionDataArgs,
  CollectRebateInstructionData
> {
  return combineCodec(
    getCollectRebateInstructionDataEncoder(),
    getCollectRebateInstructionDataDecoder(),
  );
}

export type CollectRebateAsyncInput<
  TAccountOwner extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountRebateVault extends string = string,
  TAccountRebateTokenAccount extends string = string,
  TAccountTokenStakeAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountReceivingTokenMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  perpetuals?: Address<TAccountPerpetuals>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  rebateVault?: Address<TAccountRebateVault>;
  rebateTokenAccount?: Address<TAccountRebateTokenAccount>;
  tokenStakeAccount?: Address<TAccountTokenStakeAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  receivingTokenMint: Address<TAccountReceivingTokenMint>;
};

export async function getCollectRebateInstructionAsync<
  TAccountOwner extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountRebateVault extends string,
  TAccountRebateTokenAccount extends string,
  TAccountTokenStakeAccount extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountReceivingTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: CollectRebateAsyncInput<
    TAccountOwner,
    TAccountReceivingTokenAccount,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenStakeAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountReceivingTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CollectRebateInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingTokenAccount,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenStakeAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountReceivingTokenMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    rebateVault: { value: input.rebateVault ?? null, isWritable: true },
    rebateTokenAccount: {
      value: input.rebateTokenAccount ?? null,
      isWritable: true,
    },
    tokenStakeAccount: {
      value: input.tokenStakeAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    receivingTokenMint: {
      value: input.receivingTokenMint ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.rebateVault.value) {
    accounts.rebateVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            114, 101, 98, 97, 116, 101, 95, 118, 97, 117, 108, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.rebateTokenAccount.value) {
    accounts.rebateTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            114, 101, 98, 97, 116, 101, 95, 116, 111, 107, 101, 110, 95, 97, 99,
            99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenStakeAccount.value) {
    accounts.tokenStakeAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 115, 116, 97, 107, 101]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "owner",
            accounts.owner.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("rebateVault", accounts.rebateVault),
      getAccountMeta("rebateTokenAccount", accounts.rebateTokenAccount),
      getAccountMeta("tokenStakeAccount", accounts.tokenStakeAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("receivingTokenMint", accounts.receivingTokenMint),
    ],
    data: getCollectRebateInstructionDataEncoder().encode({}),
    programAddress,
  } as CollectRebateInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingTokenAccount,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenStakeAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountReceivingTokenMint
  >);
}

export type CollectRebateInput<
  TAccountOwner extends string = string,
  TAccountReceivingTokenAccount extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountRebateVault extends string = string,
  TAccountRebateTokenAccount extends string = string,
  TAccountTokenStakeAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountReceivingTokenMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  receivingTokenAccount: Address<TAccountReceivingTokenAccount>;
  perpetuals: Address<TAccountPerpetuals>;
  transferAuthority: Address<TAccountTransferAuthority>;
  rebateVault: Address<TAccountRebateVault>;
  rebateTokenAccount: Address<TAccountRebateTokenAccount>;
  tokenStakeAccount: Address<TAccountTokenStakeAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  receivingTokenMint: Address<TAccountReceivingTokenMint>;
};

export function getCollectRebateInstruction<
  TAccountOwner extends string,
  TAccountReceivingTokenAccount extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountRebateVault extends string,
  TAccountRebateTokenAccount extends string,
  TAccountTokenStakeAccount extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountReceivingTokenMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: CollectRebateInput<
    TAccountOwner,
    TAccountReceivingTokenAccount,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenStakeAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountReceivingTokenMint
  >,
  config?: { programAddress?: TProgramAddress },
): CollectRebateInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountReceivingTokenAccount,
  TAccountPerpetuals,
  TAccountTransferAuthority,
  TAccountRebateVault,
  TAccountRebateTokenAccount,
  TAccountTokenStakeAccount,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountReceivingTokenMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    receivingTokenAccount: {
      value: input.receivingTokenAccount ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    rebateVault: { value: input.rebateVault ?? null, isWritable: true },
    rebateTokenAccount: {
      value: input.rebateTokenAccount ?? null,
      isWritable: true,
    },
    tokenStakeAccount: {
      value: input.tokenStakeAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    receivingTokenMint: {
      value: input.receivingTokenMint ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("receivingTokenAccount", accounts.receivingTokenAccount),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("rebateVault", accounts.rebateVault),
      getAccountMeta("rebateTokenAccount", accounts.rebateTokenAccount),
      getAccountMeta("tokenStakeAccount", accounts.tokenStakeAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("receivingTokenMint", accounts.receivingTokenMint),
    ],
    data: getCollectRebateInstructionDataEncoder().encode({}),
    programAddress,
  } as CollectRebateInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingTokenAccount,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenStakeAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountReceivingTokenMint
  >);
}

export type ParsedCollectRebateInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    receivingTokenAccount: TAccountMetas[1];
    perpetuals: TAccountMetas[2];
    transferAuthority: TAccountMetas[3];
    rebateVault: TAccountMetas[4];
    rebateTokenAccount: TAccountMetas[5];
    tokenStakeAccount: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    eventAuthority: TAccountMetas[8];
    program: TAccountMetas[9];
    receivingTokenMint: TAccountMetas[10];
  };
  data: CollectRebateInstructionData;
};

export function parseCollectRebateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCollectRebateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      receivingTokenAccount: getNextAccount(),
      perpetuals: getNextAccount(),
      transferAuthority: getNextAccount(),
      rebateVault: getNextAccount(),
      rebateTokenAccount: getNextAccount(),
      tokenStakeAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      receivingTokenMint: getNextAccount(),
    },
    data: getCollectRebateInstructionDataDecoder().decode(instruction.data),
  };
}
