/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  getOraclePriceDecoder,
  getOraclePriceEncoder,
  getPrivilegeDecoder,
  getPrivilegeEncoder,
  type OraclePrice,
  type OraclePriceArgs,
  type Privilege,
  type PrivilegeArgs,
} from "../types/index.js";

export const INCREASE_SIZE_DISCRIMINATOR = new Uint8Array([
  107, 13, 141, 238, 152, 165, 96, 87,
]);

export function getIncreaseSizeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INCREASE_SIZE_DISCRIMINATOR,
  );
}

export type IncreaseSizeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountTargetCustody extends string | AccountMeta<string> = string,
  TAccountTargetOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountCollateralOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustodyTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountCollateralTokenProgram extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountIxSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountCollateralMint extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountTargetCustody extends string
        ? ReadonlyAccount<TAccountTargetCustody>
        : TAccountTargetCustody,
      TAccountTargetOracleAccount extends string
        ? ReadonlyAccount<TAccountTargetOracleAccount>
        : TAccountTargetOracleAccount,
      TAccountCollateralCustody extends string
        ? WritableAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralOracleAccount extends string
        ? ReadonlyAccount<TAccountCollateralOracleAccount>
        : TAccountCollateralOracleAccount,
      TAccountCollateralCustodyTokenAccount extends string
        ? WritableAccount<TAccountCollateralCustodyTokenAccount>
        : TAccountCollateralCustodyTokenAccount,
      TAccountCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountCollateralTokenProgram>
        : TAccountCollateralTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountIxSysvar extends string
        ? ReadonlyAccount<TAccountIxSysvar>
        : TAccountIxSysvar,
      TAccountCollateralMint extends string
        ? ReadonlyAccount<TAccountCollateralMint>
        : TAccountCollateralMint,
      ...TRemainingAccounts,
    ]
  >;

export type IncreaseSizeInstructionData = {
  discriminator: ReadonlyUint8Array;
  priceWithSlippage: OraclePrice;
  sizeDelta: bigint;
  privilege: Privilege;
};

export type IncreaseSizeInstructionDataArgs = {
  priceWithSlippage: OraclePriceArgs;
  sizeDelta: number | bigint;
  privilege: PrivilegeArgs;
};

export function getIncreaseSizeInstructionDataEncoder(): FixedSizeEncoder<IncreaseSizeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["priceWithSlippage", getOraclePriceEncoder()],
      ["sizeDelta", getU64Encoder()],
      ["privilege", getPrivilegeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INCREASE_SIZE_DISCRIMINATOR }),
  );
}

export function getIncreaseSizeInstructionDataDecoder(): FixedSizeDecoder<IncreaseSizeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["priceWithSlippage", getOraclePriceDecoder()],
    ["sizeDelta", getU64Decoder()],
    ["privilege", getPrivilegeDecoder()],
  ]);
}

export function getIncreaseSizeInstructionDataCodec(): FixedSizeCodec<
  IncreaseSizeInstructionDataArgs,
  IncreaseSizeInstructionData
> {
  return combineCodec(
    getIncreaseSizeInstructionDataEncoder(),
    getIncreaseSizeInstructionDataDecoder(),
  );
}

export type IncreaseSizeAsyncInput<
  TAccountOwner extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountCollateralCustodyTokenAccount extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
  TAccountCollateralMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position?: Address<TAccountPosition>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  collateralCustodyTokenAccount: Address<TAccountCollateralCustodyTokenAccount>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  collateralMint: Address<TAccountCollateralMint>;
  priceWithSlippage: IncreaseSizeInstructionDataArgs["priceWithSlippage"];
  sizeDelta: IncreaseSizeInstructionDataArgs["sizeDelta"];
  privilege: IncreaseSizeInstructionDataArgs["privilege"];
};

export async function getIncreaseSizeInstructionAsync<
  TAccountOwner extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountCollateralCustodyTokenAccount extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TAccountCollateralMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: IncreaseSizeAsyncInput<
    TAccountOwner,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountCollateralTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountCollateralMint
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  IncreaseSizeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountCollateralTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountCollateralMint
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: true,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustodyTokenAccount: {
      value: input.collateralCustodyTokenAccount ?? null,
      isWritable: true,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.position.value) {
    accounts.position.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 111, 115, 105, 116, 105, 111, 110]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "owner",
            accounts.owner.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "market",
            accounts.market.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta(
        "collateralCustodyTokenAccount",
        accounts.collateralCustodyTokenAccount,
      ),
      getAccountMeta("collateralTokenProgram", accounts.collateralTokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
      getAccountMeta("collateralMint", accounts.collateralMint),
    ],
    data: getIncreaseSizeInstructionDataEncoder().encode(
      args as IncreaseSizeInstructionDataArgs,
    ),
    programAddress,
  } as IncreaseSizeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountCollateralTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountCollateralMint
  >);
}

export type IncreaseSizeInput<
  TAccountOwner extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountTargetOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralOracleAccount extends string = string,
  TAccountCollateralCustodyTokenAccount extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
  TAccountCollateralMint extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  targetOracleAccount: Address<TAccountTargetOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralOracleAccount: Address<TAccountCollateralOracleAccount>;
  collateralCustodyTokenAccount: Address<TAccountCollateralCustodyTokenAccount>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
  collateralMint: Address<TAccountCollateralMint>;
  priceWithSlippage: IncreaseSizeInstructionDataArgs["priceWithSlippage"];
  sizeDelta: IncreaseSizeInstructionDataArgs["sizeDelta"];
  privilege: IncreaseSizeInstructionDataArgs["privilege"];
};

export function getIncreaseSizeInstruction<
  TAccountOwner extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountTargetOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralOracleAccount extends string,
  TAccountCollateralCustodyTokenAccount extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TAccountCollateralMint extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: IncreaseSizeInput<
    TAccountOwner,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountCollateralTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountCollateralMint
  >,
  config?: { programAddress?: TProgramAddress },
): IncreaseSizeInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountMarket,
  TAccountTargetCustody,
  TAccountTargetOracleAccount,
  TAccountCollateralCustody,
  TAccountCollateralOracleAccount,
  TAccountCollateralCustodyTokenAccount,
  TAccountCollateralTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountIxSysvar,
  TAccountCollateralMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    targetOracleAccount: {
      value: input.targetOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: true,
    },
    collateralOracleAccount: {
      value: input.collateralOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustodyTokenAccount: {
      value: input.collateralCustodyTokenAccount ?? null,
      isWritable: true,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("owner", accounts.owner),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("targetOracleAccount", accounts.targetOracleAccount),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta(
        "collateralOracleAccount",
        accounts.collateralOracleAccount,
      ),
      getAccountMeta(
        "collateralCustodyTokenAccount",
        accounts.collateralCustodyTokenAccount,
      ),
      getAccountMeta("collateralTokenProgram", accounts.collateralTokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
      getAccountMeta("collateralMint", accounts.collateralMint),
    ],
    data: getIncreaseSizeInstructionDataEncoder().encode(
      args as IncreaseSizeInstructionDataArgs,
    ),
    programAddress,
  } as IncreaseSizeInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountTargetOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralOracleAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountCollateralTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar,
    TAccountCollateralMint
  >);
}

export type ParsedIncreaseSizeInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    transferAuthority: TAccountMetas[1];
    perpetuals: TAccountMetas[2];
    pool: TAccountMetas[3];
    position: TAccountMetas[4];
    market: TAccountMetas[5];
    targetCustody: TAccountMetas[6];
    targetOracleAccount: TAccountMetas[7];
    collateralCustody: TAccountMetas[8];
    collateralOracleAccount: TAccountMetas[9];
    collateralCustodyTokenAccount: TAccountMetas[10];
    collateralTokenProgram: TAccountMetas[11];
    eventAuthority: TAccountMetas[12];
    program: TAccountMetas[13];
    ixSysvar: TAccountMetas[14];
    collateralMint: TAccountMetas[15];
  };
  data: IncreaseSizeInstructionData;
};

export function parseIncreaseSizeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedIncreaseSizeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 16) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 16,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      market: getNextAccount(),
      targetCustody: getNextAccount(),
      targetOracleAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralOracleAccount: getNextAccount(),
      collateralCustodyTokenAccount: getNextAccount(),
      collateralTokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      ixSysvar: getNextAccount(),
      collateralMint: getNextAccount(),
    },
    data: getIncreaseSizeInstructionDataDecoder().decode(instruction.data),
  };
}
