/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  getTokenPermissionsDecoder,
  getTokenPermissionsEncoder,
  type TokenPermissions,
  type TokenPermissionsArgs,
} from "../types/index.js";

export const INIT_TOKEN_VAULT_DISCRIMINATOR = new Uint8Array([
  203, 26, 194, 169, 252, 226, 179, 180,
]);

export function getInitTokenVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_TOKEN_VAULT_DISCRIMINATOR,
  );
}

export type InitTokenVaultInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountFundingTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountTokenVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountFundingTokenAccount extends string
        ? WritableAccount<TAccountFundingTokenAccount>
        : TAccountFundingTokenAccount,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountTokenVaultTokenAccount extends string
        ? WritableAccount<TAccountTokenVaultTokenAccount>
        : TAccountTokenVaultTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type InitTokenVaultInstructionData = {
  discriminator: ReadonlyUint8Array;
  tokenPermissions: TokenPermissions;
  amount: bigint;
  withdrawTimeLimit: bigint;
  withdrawInstantFee: bigint;
  stakeLevel: Array<bigint>;
};

export type InitTokenVaultInstructionDataArgs = {
  tokenPermissions: TokenPermissionsArgs;
  amount: number | bigint;
  withdrawTimeLimit: number | bigint;
  withdrawInstantFee: number | bigint;
  stakeLevel: Array<number | bigint>;
};

export function getInitTokenVaultInstructionDataEncoder(): FixedSizeEncoder<InitTokenVaultInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["tokenPermissions", getTokenPermissionsEncoder()],
      ["amount", getU64Encoder()],
      ["withdrawTimeLimit", getI64Encoder()],
      ["withdrawInstantFee", getU64Encoder()],
      ["stakeLevel", getArrayEncoder(getU64Encoder(), { size: 6 })],
    ]),
    (value) => ({ ...value, discriminator: INIT_TOKEN_VAULT_DISCRIMINATOR }),
  );
}

export function getInitTokenVaultInstructionDataDecoder(): FixedSizeDecoder<InitTokenVaultInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["tokenPermissions", getTokenPermissionsDecoder()],
    ["amount", getU64Decoder()],
    ["withdrawTimeLimit", getI64Decoder()],
    ["withdrawInstantFee", getU64Decoder()],
    ["stakeLevel", getArrayDecoder(getU64Decoder(), { size: 6 })],
  ]);
}

export function getInitTokenVaultInstructionDataCodec(): FixedSizeCodec<
  InitTokenVaultInstructionDataArgs,
  InitTokenVaultInstructionData
> {
  return combineCodec(
    getInitTokenVaultInstructionDataEncoder(),
    getInitTokenVaultInstructionDataDecoder(),
  );
}

export type InitTokenVaultAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountFundingTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  perpetuals?: Address<TAccountPerpetuals>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  fundingTokenAccount: Address<TAccountFundingTokenAccount>;
  tokenMint: Address<TAccountTokenMint>;
  tokenVault?: Address<TAccountTokenVault>;
  tokenVaultTokenAccount?: Address<TAccountTokenVaultTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  tokenPermissions: InitTokenVaultInstructionDataArgs["tokenPermissions"];
  amount: InitTokenVaultInstructionDataArgs["amount"];
  withdrawTimeLimit: InitTokenVaultInstructionDataArgs["withdrawTimeLimit"];
  withdrawInstantFee: InitTokenVaultInstructionDataArgs["withdrawInstantFee"];
  stakeLevel: InitTokenVaultInstructionDataArgs["stakeLevel"];
};

export async function getInitTokenVaultInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountFundingTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitTokenVaultAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountFundingTokenAccount,
    TAccountTokenMint,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitTokenVaultInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountFundingTokenAccount,
    TAccountTokenMint,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    fundingTokenAccount: {
      value: input.fundingTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenVault.value) {
    accounts.tokenVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116]),
        ),
      ],
    });
  }
  if (!accounts.tokenVaultTokenAccount.value) {
    accounts.tokenVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116, 95, 116, 111,
            107, 101, 110, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("fundingTokenAccount", accounts.fundingTokenAccount),
      getAccountMeta("tokenMint", accounts.tokenMint),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitTokenVaultInstructionDataEncoder().encode(
      args as InitTokenVaultInstructionDataArgs,
    ),
    programAddress,
  } as InitTokenVaultInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountFundingTokenAccount,
    TAccountTokenMint,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type InitTokenVaultInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountFundingTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTokenVaultTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  perpetuals: Address<TAccountPerpetuals>;
  transferAuthority: Address<TAccountTransferAuthority>;
  fundingTokenAccount: Address<TAccountFundingTokenAccount>;
  tokenMint: Address<TAccountTokenMint>;
  tokenVault: Address<TAccountTokenVault>;
  tokenVaultTokenAccount: Address<TAccountTokenVaultTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  tokenPermissions: InitTokenVaultInstructionDataArgs["tokenPermissions"];
  amount: InitTokenVaultInstructionDataArgs["amount"];
  withdrawTimeLimit: InitTokenVaultInstructionDataArgs["withdrawTimeLimit"];
  withdrawInstantFee: InitTokenVaultInstructionDataArgs["withdrawInstantFee"];
  stakeLevel: InitTokenVaultInstructionDataArgs["stakeLevel"];
};

export function getInitTokenVaultInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountPerpetuals extends string,
  TAccountTransferAuthority extends string,
  TAccountFundingTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountTokenVault extends string,
  TAccountTokenVaultTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InitTokenVaultInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountFundingTokenAccount,
    TAccountTokenMint,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): InitTokenVaultInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountPerpetuals,
  TAccountTransferAuthority,
  TAccountFundingTokenAccount,
  TAccountTokenMint,
  TAccountTokenVault,
  TAccountTokenVaultTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    fundingTokenAccount: {
      value: input.fundingTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    tokenVaultTokenAccount: {
      value: input.tokenVaultTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("fundingTokenAccount", accounts.fundingTokenAccount),
      getAccountMeta("tokenMint", accounts.tokenMint),
      getAccountMeta("tokenVault", accounts.tokenVault),
      getAccountMeta("tokenVaultTokenAccount", accounts.tokenVaultTokenAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitTokenVaultInstructionDataEncoder().encode(
      args as InitTokenVaultInstructionDataArgs,
    ),
    programAddress,
  } as InitTokenVaultInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountPerpetuals,
    TAccountTransferAuthority,
    TAccountFundingTokenAccount,
    TAccountTokenMint,
    TAccountTokenVault,
    TAccountTokenVaultTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type ParsedInitTokenVaultInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    perpetuals: TAccountMetas[2];
    transferAuthority: TAccountMetas[3];
    fundingTokenAccount: TAccountMetas[4];
    tokenMint: TAccountMetas[5];
    tokenVault: TAccountMetas[6];
    tokenVaultTokenAccount: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    rent: TAccountMetas[10];
  };
  data: InitTokenVaultInstructionData;
};

export function parseInitTokenVaultInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitTokenVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      perpetuals: getNextAccount(),
      transferAuthority: getNextAccount(),
      fundingTokenAccount: getNextAccount(),
      tokenMint: getNextAccount(),
      tokenVault: getNextAccount(),
      tokenVaultTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitTokenVaultInstructionDataDecoder().decode(instruction.data),
  };
}
