/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const REFRESH_POSITIONS_STATUS_DISCRIMINATOR = new Uint8Array([
  128, 146, 70, 109, 88, 250, 26, 53,
]);

export function getRefreshPositionsStatusDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REFRESH_POSITIONS_STATUS_DISCRIMINATOR,
  );
}

export type RefreshPositionsStatusInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      ...TRemainingAccounts,
    ]
  >;

export type RefreshPositionsStatusInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type RefreshPositionsStatusInstructionDataArgs = {};

export function getRefreshPositionsStatusInstructionDataEncoder(): FixedSizeEncoder<RefreshPositionsStatusInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: REFRESH_POSITIONS_STATUS_DISCRIMINATOR,
    }),
  );
}

export function getRefreshPositionsStatusInstructionDataDecoder(): FixedSizeDecoder<RefreshPositionsStatusInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRefreshPositionsStatusInstructionDataCodec(): FixedSizeCodec<
  RefreshPositionsStatusInstructionDataArgs,
  RefreshPositionsStatusInstructionData
> {
  return combineCodec(
    getRefreshPositionsStatusInstructionDataEncoder(),
    getRefreshPositionsStatusInstructionDataDecoder(),
  );
}

export type RefreshPositionsStatusAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
};

export async function getRefreshPositionsStatusInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RefreshPositionsStatusAsyncInput<TAccountAdmin, TAccountMultisig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RefreshPositionsStatusInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
    ],
    data: getRefreshPositionsStatusInstructionDataEncoder().encode({}),
    programAddress,
  } as RefreshPositionsStatusInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig
  >);
}

export type RefreshPositionsStatusInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
};

export function getRefreshPositionsStatusInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RefreshPositionsStatusInput<TAccountAdmin, TAccountMultisig>,
  config?: { programAddress?: TProgramAddress },
): RefreshPositionsStatusInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    multisig: { value: input.multisig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
    ],
    data: getRefreshPositionsStatusInstructionDataEncoder().encode({}),
    programAddress,
  } as RefreshPositionsStatusInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig
  >);
}

export type ParsedRefreshPositionsStatusInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
  };
  data: RefreshPositionsStatusInstructionData;
};

export function parseRefreshPositionsStatusInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRefreshPositionsStatusInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), multisig: getNextAccount() },
    data: getRefreshPositionsStatusInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
