/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const REMOVE_MARKET_DISCRIMINATOR = new Uint8Array([
  138, 35, 250, 163, 200, 202, 40, 110,
]);

export function getRemoveMarketDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REMOVE_MARKET_DISCRIMINATOR,
  );
}

export type RemoveMarketInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountTargetCustody extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMultisig extends string
        ? WritableAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransferAuthority extends string
        ? WritableAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountTargetCustody extends string
        ? ReadonlyAccount<TAccountTargetCustody>
        : TAccountTargetCustody,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveMarketInstructionData = { discriminator: ReadonlyUint8Array };

export type RemoveMarketInstructionDataArgs = {};

export function getRemoveMarketInstructionDataEncoder(): FixedSizeEncoder<RemoveMarketInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REMOVE_MARKET_DISCRIMINATOR }),
  );
}

export function getRemoveMarketInstructionDataDecoder(): FixedSizeDecoder<RemoveMarketInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRemoveMarketInstructionDataCodec(): FixedSizeCodec<
  RemoveMarketInstructionDataArgs,
  RemoveMarketInstructionData
> {
  return combineCodec(
    getRemoveMarketInstructionDataEncoder(),
    getRemoveMarketInstructionDataDecoder(),
  );
}

export type RemoveMarketAsyncInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig?: Address<TAccountMultisig>;
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  collateralCustody: Address<TAccountCollateralCustody>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getRemoveMarketInstructionAsync<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountCollateralCustody extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RemoveMarketAsyncInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountCollateralCustody,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RemoveMarketInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountCollateralCustody,
    TAccountSystemProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.multisig.value) {
    accounts.multisig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getRemoveMarketInstructionDataEncoder().encode({}),
    programAddress,
  } as RemoveMarketInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountCollateralCustody,
    TAccountSystemProgram,
    TAccountTokenProgram
  >);
}

export type RemoveMarketInput<
  TAccountAdmin extends string = string,
  TAccountMultisig extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountMarket extends string = string,
  TAccountTargetCustody extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  multisig: Address<TAccountMultisig>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  market: Address<TAccountMarket>;
  targetCustody: Address<TAccountTargetCustody>;
  collateralCustody: Address<TAccountCollateralCustody>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getRemoveMarketInstruction<
  TAccountAdmin extends string,
  TAccountMultisig extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountMarket extends string,
  TAccountTargetCustody extends string,
  TAccountCollateralCustody extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: RemoveMarketInput<
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountCollateralCustody,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RemoveMarketInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMultisig,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountMarket,
  TAccountTargetCustody,
  TAccountCollateralCustody,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    multisig: { value: input.multisig ?? null, isWritable: true },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    targetCustody: { value: input.targetCustody ?? null, isWritable: false },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("multisig", accounts.multisig),
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("market", accounts.market),
      getAccountMeta("targetCustody", accounts.targetCustody),
      getAccountMeta("collateralCustody", accounts.collateralCustody),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getRemoveMarketInstructionDataEncoder().encode({}),
    programAddress,
  } as RemoveMarketInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMultisig,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountMarket,
    TAccountTargetCustody,
    TAccountCollateralCustody,
    TAccountSystemProgram,
    TAccountTokenProgram
  >);
}

export type ParsedRemoveMarketInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    multisig: TAccountMetas[1];
    transferAuthority: TAccountMetas[2];
    perpetuals: TAccountMetas[3];
    pool: TAccountMetas[4];
    market: TAccountMetas[5];
    targetCustody: TAccountMetas[6];
    collateralCustody: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
  };
  data: RemoveMarketInstructionData;
};

export function parseRemoveMarketInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRemoveMarketInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 10,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      multisig: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      market: getNextAccount(),
      targetCustody: getNextAccount(),
      collateralCustody: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getRemoveMarketInstructionDataDecoder().decode(instruction.data),
  };
}
