/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const SET_INTERNAL_LAZER_PRICE_DISCRIMINATOR = new Uint8Array([
  56, 112, 153, 62, 193, 123, 193, 115,
]);

export function getSetInternalLazerPriceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_INTERNAL_LAZER_PRICE_DISCRIMINATOR,
  );
}

export type SetInternalLazerPriceInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountPythStorage extends string | AccountMeta<string> = string,
  TAccountPythTreasury extends string | AccountMeta<string> = string,
  TAccountPythLazerProgram extends string | AccountMeta<string> =
    "pytd2yyk641x7ak7mkaasSJVXh6YYZnC7wTmtgAyxPt",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountPythStorage extends string
        ? ReadonlyAccount<TAccountPythStorage>
        : TAccountPythStorage,
      TAccountPythTreasury extends string
        ? WritableAccount<TAccountPythTreasury>
        : TAccountPythTreasury,
      TAccountPythLazerProgram extends string
        ? ReadonlyAccount<TAccountPythLazerProgram>
        : TAccountPythLazerProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SetInternalLazerPriceInstructionData = {
  discriminator: ReadonlyUint8Array;
  messageData: ReadonlyUint8Array;
};

export type SetInternalLazerPriceInstructionDataArgs = {
  messageData: ReadonlyUint8Array;
};

export function getSetInternalLazerPriceInstructionDataEncoder(): Encoder<SetInternalLazerPriceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["messageData", addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_INTERNAL_LAZER_PRICE_DISCRIMINATOR,
    }),
  );
}

export function getSetInternalLazerPriceInstructionDataDecoder(): Decoder<SetInternalLazerPriceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["messageData", addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getSetInternalLazerPriceInstructionDataCodec(): Codec<
  SetInternalLazerPriceInstructionDataArgs,
  SetInternalLazerPriceInstructionData
> {
  return combineCodec(
    getSetInternalLazerPriceInstructionDataEncoder(),
    getSetInternalLazerPriceInstructionDataDecoder(),
  );
}

export type SetInternalLazerPriceInput<
  TAccountPayer extends string = string,
  TAccountPythStorage extends string = string,
  TAccountPythTreasury extends string = string,
  TAccountPythLazerProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  pythStorage: Address<TAccountPythStorage>;
  pythTreasury: Address<TAccountPythTreasury>;
  pythLazerProgram?: Address<TAccountPythLazerProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  messageData: SetInternalLazerPriceInstructionDataArgs["messageData"];
};

export function getSetInternalLazerPriceInstruction<
  TAccountPayer extends string,
  TAccountPythStorage extends string,
  TAccountPythTreasury extends string,
  TAccountPythLazerProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: SetInternalLazerPriceInput<
    TAccountPayer,
    TAccountPythStorage,
    TAccountPythTreasury,
    TAccountPythLazerProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SetInternalLazerPriceInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountPythStorage,
  TAccountPythTreasury,
  TAccountPythLazerProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    pythStorage: { value: input.pythStorage ?? null, isWritable: false },
    pythTreasury: { value: input.pythTreasury ?? null, isWritable: true },
    pythLazerProgram: {
      value: input.pythLazerProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.pythLazerProgram.value) {
    accounts.pythLazerProgram.value =
      "pytd2yyk641x7ak7mkaasSJVXh6YYZnC7wTmtgAyxPt" as Address<"pytd2yyk641x7ak7mkaasSJVXh6YYZnC7wTmtgAyxPt">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("pythStorage", accounts.pythStorage),
      getAccountMeta("pythTreasury", accounts.pythTreasury),
      getAccountMeta("pythLazerProgram", accounts.pythLazerProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getSetInternalLazerPriceInstructionDataEncoder().encode(
      args as SetInternalLazerPriceInstructionDataArgs,
    ),
    programAddress,
  } as SetInternalLazerPriceInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountPythStorage,
    TAccountPythTreasury,
    TAccountPythLazerProgram,
    TAccountSystemProgram
  >);
}

export type ParsedSetInternalLazerPriceInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    pythStorage: TAccountMetas[1];
    pythTreasury: TAccountMetas[2];
    pythLazerProgram: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: SetInternalLazerPriceInstructionData;
};

export function parseSetInternalLazerPriceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetInternalLazerPriceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      pythStorage: getNextAccount(),
      pythTreasury: getNextAccount(),
      pythLazerProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getSetInternalLazerPriceInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
