/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs/index.js";

export const SETTLE_REBATES_DISCRIMINATOR = new Uint8Array([
  12, 192, 237, 255, 81, 68, 17, 193,
]);

export function getSettleRebatesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SETTLE_REBATES_DISCRIMINATOR,
  );
}

export type SettleRebatesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountRewardCustody extends string | AccountMeta<string> = string,
  TAccountRewardCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TAccountRewardCustodyTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountRebateVault extends string | AccountMeta<string> = string,
  TAccountRebateTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> =
    "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn",
  TAccountIxSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountRewardCustody extends string
        ? WritableAccount<TAccountRewardCustody>
        : TAccountRewardCustody,
      TAccountRewardCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountRewardCustodyOracleAccount>
        : TAccountRewardCustodyOracleAccount,
      TAccountRewardCustodyTokenAccount extends string
        ? WritableAccount<TAccountRewardCustodyTokenAccount>
        : TAccountRewardCustodyTokenAccount,
      TAccountRebateVault extends string
        ? WritableAccount<TAccountRebateVault>
        : TAccountRebateVault,
      TAccountRebateTokenAccount extends string
        ? WritableAccount<TAccountRebateTokenAccount>
        : TAccountRebateTokenAccount,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountIxSysvar extends string
        ? ReadonlyAccount<TAccountIxSysvar>
        : TAccountIxSysvar,
      ...TRemainingAccounts,
    ]
  >;

export type SettleRebatesInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type SettleRebatesInstructionDataArgs = {};

export function getSettleRebatesInstructionDataEncoder(): FixedSizeEncoder<SettleRebatesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SETTLE_REBATES_DISCRIMINATOR }),
  );
}

export function getSettleRebatesInstructionDataDecoder(): FixedSizeDecoder<SettleRebatesInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSettleRebatesInstructionDataCodec(): FixedSizeCodec<
  SettleRebatesInstructionDataArgs,
  SettleRebatesInstructionData
> {
  return combineCodec(
    getSettleRebatesInstructionDataEncoder(),
    getSettleRebatesInstructionDataDecoder(),
  );
}

export type SettleRebatesAsyncInput<
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountRewardCustody extends string = string,
  TAccountRewardCustodyOracleAccount extends string = string,
  TAccountRewardCustodyTokenAccount extends string = string,
  TAccountRebateVault extends string = string,
  TAccountRebateTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  transferAuthority?: Address<TAccountTransferAuthority>;
  perpetuals?: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  rewardCustody: Address<TAccountRewardCustody>;
  rewardCustodyOracleAccount: Address<TAccountRewardCustodyOracleAccount>;
  rewardCustodyTokenAccount: Address<TAccountRewardCustodyTokenAccount>;
  rebateVault?: Address<TAccountRebateVault>;
  rebateTokenAccount: Address<TAccountRebateTokenAccount>;
  tokenMint: Address<TAccountTokenMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
};

export async function getSettleRebatesInstructionAsync<
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountRewardCustody extends string,
  TAccountRewardCustodyOracleAccount extends string,
  TAccountRewardCustodyTokenAccount extends string,
  TAccountRebateVault extends string,
  TAccountRebateTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: SettleRebatesAsyncInput<
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountRewardCustodyTokenAccount,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SettleRebatesInstruction<
    TProgramAddress,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountRewardCustodyTokenAccount,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    rewardCustody: { value: input.rewardCustody ?? null, isWritable: true },
    rewardCustodyOracleAccount: {
      value: input.rewardCustodyOracleAccount ?? null,
      isWritable: false,
    },
    rewardCustodyTokenAccount: {
      value: input.rewardCustodyTokenAccount ?? null,
      isWritable: true,
    },
    rebateVault: { value: input.rebateVault ?? null, isWritable: true },
    rebateTokenAccount: {
      value: input.rebateTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.transferAuthority.value) {
    accounts.transferAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 97, 110, 115, 102, 101, 114, 95, 97, 117, 116, 104, 111,
            114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.perpetuals.value) {
    accounts.perpetuals.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 101, 114, 112, 101, 116, 117, 97, 108, 115]),
        ),
      ],
    });
  }
  if (!accounts.rebateVault.value) {
    accounts.rebateVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            114, 101, 98, 97, 116, 101, 95, 118, 97, 117, 108, 116,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("rewardCustody", accounts.rewardCustody),
      getAccountMeta(
        "rewardCustodyOracleAccount",
        accounts.rewardCustodyOracleAccount,
      ),
      getAccountMeta(
        "rewardCustodyTokenAccount",
        accounts.rewardCustodyTokenAccount,
      ),
      getAccountMeta("rebateVault", accounts.rebateVault),
      getAccountMeta("rebateTokenAccount", accounts.rebateTokenAccount),
      getAccountMeta("tokenMint", accounts.tokenMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getSettleRebatesInstructionDataEncoder().encode({}),
    programAddress,
  } as SettleRebatesInstruction<
    TProgramAddress,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountRewardCustodyTokenAccount,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >);
}

export type SettleRebatesInput<
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountRewardCustody extends string = string,
  TAccountRewardCustodyOracleAccount extends string = string,
  TAccountRewardCustodyTokenAccount extends string = string,
  TAccountRebateVault extends string = string,
  TAccountRebateTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
  TAccountIxSysvar extends string = string,
> = {
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  rewardCustody: Address<TAccountRewardCustody>;
  rewardCustodyOracleAccount: Address<TAccountRewardCustodyOracleAccount>;
  rewardCustodyTokenAccount: Address<TAccountRewardCustodyTokenAccount>;
  rebateVault: Address<TAccountRebateVault>;
  rebateTokenAccount: Address<TAccountRebateTokenAccount>;
  tokenMint: Address<TAccountTokenMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program?: Address<TAccountProgram>;
  ixSysvar?: Address<TAccountIxSysvar>;
};

export function getSettleRebatesInstruction<
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountRewardCustody extends string,
  TAccountRewardCustodyOracleAccount extends string,
  TAccountRewardCustodyTokenAccount extends string,
  TAccountRebateVault extends string,
  TAccountRebateTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TAccountIxSysvar extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: SettleRebatesInput<
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountRewardCustodyTokenAccount,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >,
  config?: { programAddress?: TProgramAddress },
): SettleRebatesInstruction<
  TProgramAddress,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountRewardCustody,
  TAccountRewardCustodyOracleAccount,
  TAccountRewardCustodyTokenAccount,
  TAccountRebateVault,
  TAccountRebateTokenAccount,
  TAccountTokenMint,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram,
  TAccountIxSysvar
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    rewardCustody: { value: input.rewardCustody ?? null, isWritable: true },
    rewardCustodyOracleAccount: {
      value: input.rewardCustodyOracleAccount ?? null,
      isWritable: false,
    },
    rewardCustodyTokenAccount: {
      value: input.rewardCustodyTokenAccount ?? null,
      isWritable: true,
    },
    rebateVault: { value: input.rebateVault ?? null, isWritable: true },
    rebateTokenAccount: {
      value: input.rebateTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    ixSysvar: { value: input.ixSysvar ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn" as Address<"FLASH6Lo6h3iasJKWDs2F8TkW2UKf3s15C8PMGuVfgBn">;
  }
  if (!accounts.ixSysvar.value) {
    accounts.ixSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("transferAuthority", accounts.transferAuthority),
      getAccountMeta("perpetuals", accounts.perpetuals),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("rewardCustody", accounts.rewardCustody),
      getAccountMeta(
        "rewardCustodyOracleAccount",
        accounts.rewardCustodyOracleAccount,
      ),
      getAccountMeta(
        "rewardCustodyTokenAccount",
        accounts.rewardCustodyTokenAccount,
      ),
      getAccountMeta("rebateVault", accounts.rebateVault),
      getAccountMeta("rebateTokenAccount", accounts.rebateTokenAccount),
      getAccountMeta("tokenMint", accounts.tokenMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
      getAccountMeta("ixSysvar", accounts.ixSysvar),
    ],
    data: getSettleRebatesInstructionDataEncoder().encode({}),
    programAddress,
  } as SettleRebatesInstruction<
    TProgramAddress,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountRewardCustody,
    TAccountRewardCustodyOracleAccount,
    TAccountRewardCustodyTokenAccount,
    TAccountRebateVault,
    TAccountRebateTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram,
    TAccountIxSysvar
  >);
}

export type ParsedSettleRebatesInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    transferAuthority: TAccountMetas[0];
    perpetuals: TAccountMetas[1];
    pool: TAccountMetas[2];
    rewardCustody: TAccountMetas[3];
    rewardCustodyOracleAccount: TAccountMetas[4];
    rewardCustodyTokenAccount: TAccountMetas[5];
    rebateVault: TAccountMetas[6];
    rebateTokenAccount: TAccountMetas[7];
    tokenMint: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    eventAuthority: TAccountMetas[10];
    program: TAccountMetas[11];
    ixSysvar: TAccountMetas[12];
  };
  data: SettleRebatesInstructionData;
};

export function parseSettleRebatesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSettleRebatesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 13) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 13,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      rewardCustody: getNextAccount(),
      rewardCustodyOracleAccount: getNextAccount(),
      rewardCustodyTokenAccount: getNextAccount(),
      rebateVault: getNextAccount(),
      rebateTokenAccount: getNextAccount(),
      tokenMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
      ixSysvar: getNextAccount(),
    },
    data: getSettleRebatesInstructionDataDecoder().decode(instruction.data),
  };
}
