/**
 * Composer Generator — Protocol Onboarding Pipeline
 *
 * Generates a compose-dispatch skeleton following the flash-compose.ts pattern.
 * Output: a self-contained TypeScript module with a frozen dispatch map,
 * per-action stub functions, and the protocol-specific dispatch wrapper.
 *
 * Each stub includes a TODO comment — the developer fills in account resolution
 * and Codama instruction builder calls during implementation.
 */

import type { AnnotationConfig, ParsedInstruction } from "../types.js";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function pascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

function camelCase(kebab: string): string {
  const parts = kebab.split("-");
  return parts[0] + parts.slice(1).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
}

/**
 * Convert an sdkName (camelCase) to a Codama getter function name.
 * e.g. "openPosition" -> "getOpenPositionInstruction"
 */
function codamaGetterName(sdkName: string): string {
  return `get${sdkName[0].toUpperCase() + sdkName.slice(1)}Instruction`;
}

/**
 * Convert an sdkName to a compose function name.
 * e.g. "openPosition" -> "composeOpenPosition"
 */
function composeFnName(sdkName: string): string {
  return `compose${sdkName[0].toUpperCase() + sdkName.slice(1)}`;
}

// ─── Generator ───────────────────────────────────────────────────────────────

export function generateComposer(
  config: AnnotationConfig,
  parsed: ParsedInstruction[],
): string {
  const { protocol } = config;
  const pascal = pascalCase(protocol.id);
  const camel = camelCase(protocol.id);
  const errorClassName = `${pascal}ComposeError`;
  const dispatchFnName = `dispatch${pascal}Compose`;
  const actionsConst = `${pascal.toUpperCase()}_ACTIONS`;

  // ─── Codama import lines (one per instruction) ─────────────────────────

  const codamaImports = parsed.map((ix) => {
    const getter = codamaGetterName(ix.sdkName);
    // Use the idlName for the file path since Codama generates from IDL names
    return `import { ${getter} } from "../generated/protocols/${protocol.id}/instructions/${ix.idlName}.js";`;
  });

  // ─── Per-action compose stub functions ─────────────────────────────────

  const composeFunctions = parsed.map((ix) => {
    const fnName = composeFnName(ix.sdkName);
    const ctxPrefix = ix.isSpending ? "ctx" : "_ctx";
    const paramsPrefix = ix.accounts.length > 0 || ix.fields.length > 0 ? "params" : "_params";

    // Build a list of notable fields as a comment hint
    const fieldHints = ix.fields
      .filter((f) => f.constrainable)
      .map((f) => f.name)
      .join(", ");
    const accountHints = ix.accounts.map((a) => a.name).join(", ");

    let docComment = `/**\n * ${ix.sdkName} — ActionType.${ix.actionType} (${ix.isSpending ? "spending" : "non-spending"})`;
    if (fieldHints) docComment += `\n * Constrainable fields: ${fieldHints}`;
    if (accountHints) docComment += `\n * Constrainable accounts: ${accountHints}`;
    docComment += `\n * Data size: ${ix.dataSize} bytes\n */`;

    return `${docComment}
async function ${fnName}(
  ${ctxPrefix}: ProtocolContext,
  ${paramsPrefix}: Record<string, unknown>,
): Promise<ProtocolComposeResult> {
  // TODO: implement account resolution and instruction building
  // Use ${codamaGetterName(ix.sdkName)}() from the generated protocol client.
  throw new ${errorClassName}(
    COMPOSE_ERROR_CODES.UNSUPPORTED_ACTION,
    "${ix.sdkName} compose not yet implemented",
  );
}`;
  });

  // ─── Dispatch map entries ──────────────────────────────────────────────

  const dispatchEntries = parsed.map((ix) => {
    return `  ${ix.sdkName}: ${composeFnName(ix.sdkName)},`;
  });

  // ─── Assemble output ──────────────────────────────────────────────────

  return `/**
 * ${protocol.displayName} compose functions — Kit-native via Codama pre-generated builders.
 *
 * Generated by the protocol onboarding pipeline.
 * Zero runtime dependency on external protocol SDKs.
 *
 * Program: ${protocol.programAddress}
 * Actions: ${parsed.length}
 *
 * Each compose function is a stub — fill in account resolution and
 * Codama instruction builder calls during implementation.
 */

import type { Address, Instruction } from "@solana/kit";
import type { ProtocolContext, ProtocolComposeResult } from "./protocol-handler.js";
import {
  COMPOSE_ERROR_CODES,
  ComposeError,
  createSafeBigInt,
  createRequireField,
  addressAsSigner,
} from "./compose-errors.js";

// ─── Generated Instruction Builders ─────────────────────────────────────────

${codamaImports.join("\n")}

// ─── Protocol-Specific Error Class ──────────────────────────────────────────

export class ${errorClassName} extends ComposeError {
  constructor(code: string, message: string) {
    super("${protocol.id}", code, message);
    this.name = "${errorClassName}";
  }
}

// ─── Param Validation ───────────────────────────────────────────────────────

const requireField = createRequireField(
  (field) => new ${errorClassName}(COMPOSE_ERROR_CODES.MISSING_PARAM, \`Missing required parameter: \${field}\`),
);

const safeBigInt = createSafeBigInt(
  (field, value) => new ${errorClassName}(COMPOSE_ERROR_CODES.INVALID_BIGINT, \`Invalid numeric value for \${field}: \${String(value)}\`),
);

// ─── Compose Functions ──────────────────────────────────────────────────────

${composeFunctions.join("\n\n")}

// ─── Dispatcher ─────────────────────────────────────────────────────────────

type ${pascal}ActionHandler = (
  ctx: ProtocolContext,
  params: Record<string, unknown>,
) => Promise<ProtocolComposeResult>;

const ${actionsConst}: Readonly<Record<string, ${pascal}ActionHandler>> = Object.freeze({
${dispatchEntries.join("\n")}
});

/**
 * Dispatch a ${protocol.displayName} action to the correct compose function.
 * Called by ${pascal}Handler.compose().
 */
export async function ${dispatchFnName}(
  ctx: ProtocolContext,
  action: string,
  params: Record<string, unknown>,
): Promise<ProtocolComposeResult> {
  if (!Object.hasOwn(${actionsConst}, action)) {
    throw new ${errorClassName}(
      COMPOSE_ERROR_CODES.UNSUPPORTED_ACTION,
      \`Unsupported action: \${action}. Supported: \${Object.keys(${actionsConst}).join(", ")}\`,
    );
  }
  return ${actionsConst}[action as keyof typeof ${actionsConst}](ctx, params);
}
`;
}
