/**
 * Protocol Onboarding Pipeline — Schema Generator
 *
 * Generates a ProtocolSchema file matching the pattern of:
 *   sdk/kit/src/constraints/protocols/flash-trade-schema.ts
 *   sdk/kit/src/constraints/protocols/kamino-schema.ts
 *
 * 100% automatable — no hand-edit markers needed.
 */

import type { AnnotationConfig, ParsedInstruction } from "../types.js";

function pascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

function upperSnake(kebab: string): string {
  return kebab.toUpperCase().replace(/-/g, "_");
}

function formatDiscriminator(disc: Uint8Array): string {
  return `new Uint8Array([${Array.from(disc).join(", ")}])`;
}

/**
 * Generate a complete schema TypeScript file.
 */
export function generateSchema(
  config: AnnotationConfig,
  parsed: ParsedInstruction[],
): string {
  const proto = config.protocol;
  const UPPER = upperSnake(proto.id);
  const Pascal = pascalCase(proto.id);

  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * ${proto.displayName} Protocol Schema — Instruction Layouts`);
  lines.push(` *`);
  lines.push(` * Auto-generated by scripts/add-protocol.ts from ${proto.idlFile}`);
  lines.push(` * All discriminators, field offsets, and account indices are sourced from`);
  lines.push(` * Codama-generated types in sdk/kit/src/generated/protocols/${proto.id}/.`);
  lines.push(` */`);
  lines.push(``);

  // Imports
  lines.push(`import type { Address } from "@solana/kit";`);
  lines.push(`import type { InstructionSchema, ProtocolSchema } from "../types.js";`);
  lines.push(``);

  // Program constant
  lines.push(`export const ${UPPER}_PROGRAM: Address =`);
  lines.push(`  "${proto.programAddress}" as Address;`);
  lines.push(``);

  // Instruction schemas
  lines.push(`// ─── Instruction Schemas ────────────────────────────────────────────────────`);
  lines.push(``);

  for (const ix of parsed) {
    lines.push(`const ${ix.sdkName}: InstructionSchema = {`);
    lines.push(`  name: "${ix.sdkName}",`);
    lines.push(`  discriminator: ${formatDiscriminator(ix.discriminator)},`);

    // Fields
    if (ix.fields.length === 0) {
      lines.push(`  fields: [], // no constrainable fields`);
    } else {
      lines.push(`  fields: [`);
      for (const f of ix.fields) {
        const fieldType = mapToSchemaFieldType(f.type, f.size);
        lines.push(
          `    { name: "${f.schemaFieldName}", offset: ${f.offset}, type: "${fieldType}", size: ${f.size} },`,
        );
      }
      lines.push(`  ],`);
    }

    // Accounts
    if (ix.accounts.length === 0) {
      lines.push(`  accounts: {},`);
    } else {
      const acctEntries = ix.accounts
        .map((a) => `${a.name}: ${a.index}`)
        .join(", ");
      lines.push(`  accounts: { ${acctEntries} },`);
    }

    // Data size
    const sizeComment = computeSizeComment(ix);
    lines.push(`  dataSize: ${ix.dataSize},${sizeComment}`);
    lines.push(`};`);
    lines.push(``);
  }

  // Protocol Schema map
  lines.push(`// ─── Protocol Schema ────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`const instructions = new Map<string, InstructionSchema>();`);
  lines.push(`for (const ix of [`);
  for (const ix of parsed) {
    lines.push(`  ${ix.sdkName},`);
  }
  lines.push(`]) {`);
  lines.push(`  instructions.set(ix.name, ix);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const ${UPPER}_SCHEMA: ProtocolSchema = {`);
  lines.push(`  protocolId: "${proto.id}",`);
  lines.push(`  programAddress: ${UPPER}_PROGRAM,`);
  lines.push(`  instructions,`);
  lines.push(`};`);
  lines.push(``);

  // Action categories
  lines.push(`// ─── Action Categories ──────────────────────────────────────────────────────`);
  lines.push(``);

  if (config.actionCategories) {
    for (const [category, actions] of Object.entries(config.actionCategories)) {
      const constName = categoryToConstName(category, UPPER);
      const comment = categoryComment(category);
      lines.push(`/** ${comment} */`);
      lines.push(`export const ${constName} = [`);
      for (const action of actions) {
        lines.push(`  "${action}",`);
      }
      lines.push(`] as const;`);
      lines.push(``);
    }
  }

  return lines.join("\n");
}

/**
 * Map our internal type string to FieldType for the schema.
 */
function mapToSchemaFieldType(type: string, size: number): string {
  switch (type) {
    case "u8":
    case "bool":
      return size === 1 ? "u8" : type;
    case "u16":
      return "u16";
    case "u32":
      return "u32";
    case "u64":
      return "u64";
    case "i64":
      return "i64";
    case "pubkey":
      return "pubkey";
    default:
      // Fallback based on size
      if (size === 1) return "u8";
      if (size === 2) return "u16";
      if (size === 4) return "u32";
      if (size === 8) return "u64";
      return "u64";
  }
}

function computeSizeComment(ix: ParsedInstruction): string {
  // Build a breakdown like: // 8+12+8+8+1
  const parts: string[] = ["8"]; // discriminator
  const argSizes = ix.allArgs
    .filter((a) => a.offset >= 8 && a.size > 0)
    .map((a) => String(a.size));
  if (argSizes.length > 0) {
    parts.push(...argSizes);
    return ` // ${parts.join("+")}`;
  }
  return "";
}

function categoryToConstName(category: string, upper: string): string {
  // spending → {UPPER}_SPENDING_ACTIONS
  const catUpper = category.replace(/([A-Z])/g, "_$1").toUpperCase();
  return `${upper}_${catUpper}_ACTIONS`;
}

function categoryComment(category: string): string {
  switch (category) {
    case "spending":
      return "Actions that can open or increase exposure (spending)";
    case "riskReducing":
      return "Actions that reduce exposure or are risk-reducing";
    case "sizeConstrained":
      return "Actions with a size field (for maxPositionSize)";
    case "collateralConstrained":
      return "Actions with a collateral field (for maxCollateral)";
    case "orderSize":
      return "Actions with order size fields (for maxOrderSize)";
    default:
      return `${category} actions`;
  }
}
