#!/usr/bin/env -S node --import tsx
/**
 * check-surface.ts — public API surface snapshot tool (Phase 9 Batch G,
 * ISC-136).
 *
 * Lightweight alternative to `@microsoft/api-extractor` (which would pull
 * in ~3 MB of devDeps). Builds the dist + walks every `export` line in
 * the published bundle, emitting a sorted manifest to `etc/kit.api.txt`.
 * PR reviewers diff this file to catch unintended surface changes.
 *
 * Usage:
 *   pnpm -C sdk/kit check-surface         # writes etc/kit.api.txt
 *   pnpm -C sdk/kit check-surface --check # exits non-zero if drift
 *
 * Strategy: parse the `dist/index.d.ts` re-export tree (and the subpath
 * entry points listed in package.json `exports`) for `export { ... }` and
 * `export type { ... }` declarations. Names are sorted, deduped, and
 * grouped by subpath. The TypeScript declarations are the authoritative
 * surface — they reflect what consumers actually see, not what the source
 * may transitively re-export but mangle through `dist/` re-rooting.
 *
 * This is deliberately approximate. It doesn't reify the type signatures
 * — only the names. That's enough to catch the failure mode we care about
 * ("a barrel re-export changed silently") and cheap enough to run in CI
 * without an extractor toolchain.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath((import.meta as { url: string }).url);
const __dirname = dirname(__filename);

const KIT_ROOT = resolve(__dirname, "..");
const OUT_PATH = resolve(KIT_ROOT, "etc/kit.api.txt");
const CHECK_MODE = process.argv.includes("--check");

interface SubpathSpec {
  label: string;
  declFile: string;
}

function loadSubpaths(): SubpathSpec[] {
  const pkg = JSON.parse(
    readFileSync(resolve(KIT_ROOT, "package.json"), "utf8"),
  ) as {
    exports?: Record<string, { types?: string }>;
  };
  const out: SubpathSpec[] = [];
  for (const [label, entry] of Object.entries(pkg.exports ?? {})) {
    const types = entry.types;
    if (!types) continue;
    out.push({
      label,
      declFile: resolve(KIT_ROOT, types),
    });
  }
  return out.sort((a, b) => a.label.localeCompare(b.label));
}

const EXPORT_RE =
  /export\s+(?:type\s+)?\{\s*([\s\S]*?)\s*\}\s*(?:from\s*["'][^"']+["'])?/g;

function extractExports(declSrc: string): string[] {
  const names = new Set<string>();
  for (const match of declSrc.matchAll(EXPORT_RE)) {
    const inner = match[1];
    if (!inner) continue;
    for (const raw of inner.split(",")) {
      const name = raw
        .trim()
        .split(/\s+as\s+/)
        .pop()!
        .trim();
      if (name.length > 0 && /^[A-Za-z_$][\w$]*$/.test(name)) {
        names.add(name);
      }
    }
  }
  return [...names].sort((a, b) => a.localeCompare(b));
}

function buildManifest(): string {
  const subpaths = loadSubpaths();
  const lines: string[] = [
    "# @usesigil/kit — public API surface snapshot",
    "# AUTO-GENERATED by sdk/kit/scripts/check-surface.ts",
    "# Run `pnpm -C sdk/kit check-surface` to refresh.",
    "# Run `pnpm -C sdk/kit check-surface --check` in CI to detect drift.",
    "",
  ];
  for (const sub of subpaths) {
    if (!existsSync(sub.declFile)) {
      lines.push(`## ${sub.label}`);
      lines.push("MISSING — run `pnpm build` first.");
      lines.push("");
      continue;
    }
    const src = readFileSync(sub.declFile, "utf8");
    const names = extractExports(src);
    lines.push(`## ${sub.label}`);
    if (names.length === 0) {
      lines.push("(no named exports detected)");
    } else {
      for (const n of names) {
        lines.push(`- ${n}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

function main(): void {
  const manifest = buildManifest();
  mkdirSync(dirname(OUT_PATH), { recursive: true });

  if (CHECK_MODE) {
    const existing = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, "utf8") : "";
    if (existing === manifest) {
      // eslint-disable-next-line no-console
      console.log("check-surface: ✓ no drift");
      return;
    }
    // eslint-disable-next-line no-console
    console.error(
      "check-surface: ✗ kit.api.txt is out of date. " +
        "Run `pnpm -C sdk/kit check-surface` and commit the diff.",
    );
    process.exit(1);
  }

  writeFileSync(OUT_PATH, manifest);
  // eslint-disable-next-line no-console
  console.log(`check-surface: wrote manifest to ${OUT_PATH}`);
}

main();
