#!/usr/bin/env -S node --import tsx
/**
 * gen-error-map.ts — generate the ON_CHAIN_ERROR_MAP shell from the IDL.
 *
 * Reads `target/idl/sigil.json`, extracts every error variant, and emits
 * `sdk/kit/src/errors/agent-errors.generated.ts` containing a frozen
 * `Record<number, { name: string; msg?: string }>` of the IDL's view of
 * the error surface.
 *
 * The HAND-MAINTAINED `ON_CHAIN_ERROR_MAP` in `sdk/kit/src/agent-errors.ts`
 * carries the rich `{ category, retryable, recovery_actions[], ... }`
 * shape (which the IDL cannot express). The drift gate at
 * `tests/error-map-drift.test.ts` compares the two sources and fails CI
 * if a code lands in the IDL without a corresponding hand-maintained
 * entry — closing the H-NEW-2 silent-miss class identified in the
 * Phase 0-5 audit.
 *
 * Phase 9 Batch D (ISC-51, ISC-52, ISC-54, ISC-104).
 *
 * Usage:
 *   pnpm -C sdk/kit codegen:errors
 *   # or directly: node --import tsx scripts/gen-error-map.ts
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// `import.meta.url` is intentional — this script is ESM-only and runs via
// `node --import tsx`. The TS lint warning about ES2020 module target is a
// kit tsconfig concern, not a runtime issue.
const __filename = fileURLToPath((import.meta as { url: string }).url);
const __dirname = dirname(__filename);

const IDL_PATH = resolve(__dirname, "../../../target/idl/sigil.json");
const OUT_PATH = resolve(__dirname, "../src/errors/agent-errors.generated.ts");

interface IdlError {
  code: number;
  name: string;
  msg?: string;
}

function main(): void {
  const raw = readFileSync(IDL_PATH, "utf8");
  const idl = JSON.parse(raw) as { errors?: IdlError[] };
  const errors = idl.errors ?? [];

  if (errors.length === 0) {
    throw new Error(
      `gen-error-map: no errors[] array in ${IDL_PATH}. Did the IDL change shape?`,
    );
  }

  // Sort by code so the output is deterministic across regen runs.
  errors.sort((a, b) => a.code - b.code);

  const lines: string[] = [
    "// AUTO-GENERATED by sdk/kit/scripts/gen-error-map.ts — DO NOT EDIT.",
    "// Regenerate via `pnpm -C sdk/kit codegen:errors` after IDL changes.",
    "//",
    "// Source: agent-middleware/target/idl/sigil.json",
    `// Generated: ${new Date().toISOString()}`,
    `// Codes: ${errors.length} (min ${errors[0]!.code}, max ${errors[errors.length - 1]!.code})`,
    "",
    "/** Pure IDL projection of every Anchor error variant. */",
    "export interface IdlErrorEntry {",
    "  readonly code: number;",
    "  readonly name: string;",
    "  readonly msg?: string;",
    "}",
    "",
    "/**",
    " * Auto-generated map of every Sigil on-chain error code declared in",
    " * the IDL. The hand-maintained ON_CHAIN_ERROR_MAP in",
    " * `../agent-errors.ts` adds category, retryable, recovery_actions[],",
    " * etc. — this map exists purely to drive the drift gate at",
    " * `tests/error-map-drift.test.ts`.",
    " */",
    "export const IDL_ERROR_MAP: Readonly<Record<number, IdlErrorEntry>> =",
    "  Object.freeze({",
    ...errors.map((e) => {
      const msgFragment =
        e.msg === undefined ? "" : `, msg: ${JSON.stringify(e.msg)}`;
      return `    ${e.code}: { code: ${e.code}, name: ${JSON.stringify(e.name)}${msgFragment} },`;
    }),
    "  });",
    "",
    "/** Total error-code count derived from the IDL at generation time. */",
    `export const IDL_ERROR_COUNT = ${errors.length};`,
    "",
    "/** Lowest IDL error code. */",
    `export const IDL_ERROR_MIN = ${errors[0]!.code};`,
    "",
    "/** Highest IDL error code. */",
    `export const IDL_ERROR_MAX = ${errors[errors.length - 1]!.code};`,
    "",
  ];

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, lines.join("\n"));

  // eslint-disable-next-line no-console
  console.log(`gen-error-map: wrote ${errors.length} entries to ${OUT_PATH}`);
}

main();
