#!/usr/bin/env tsx
/**
 * CI drift-check between the canonical IDL error list and the TypeScript
 * assertion-map used by `expectSigilError`.
 *
 * Source of truth:   target/idl/sigil.json (errors[])
 * Consumer:          sdk/kit/src/testing/errors/names.generated.ts (SIGIL_ERRORS)
 *
 * Fails CI (exit 1) if:
 *   - any IDL error is missing from the TS map
 *   - any TS entry references a stale error that no longer exists in the IDL
 *   - any name↔code mapping disagrees between the two
 *   - any duplicate code is found in either
 *
 * Implementation follows ALEX's Round-3 amendment: parse the IDL JSON
 * (which is ground truth for Anchor at build time), not a regex over
 * `programs/sigil/src/errors.rs` — the latter silently misses #[cfg]
 * and macro-wrapped variants.
 *
 * Failure output follows YULIA's Round-3 spec: informative, with
 * file:line anchors so agent-driven fixes are actionable.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(__dirname, "..");
const IDL_PATH = resolve(repoRoot, "target/idl/sigil.json");
const TS_PATH = resolve(
  repoRoot,
  "sdk/kit/src/testing/errors/names.generated.ts",
);
// LiteSVM tests can't import @usesigil/kit/testing (ESM boundary vs CJS
// ts-mocha). Their helpers live as an inlined copy at this path. We verify
// here that its SIGIL_ERRORS table stays in sync with the generated map.
const SHIM_PATH = resolve(repoRoot, "tests/helpers/strict-errors.ts");

interface IdlError {
  code: number;
  name: string;
  msg?: string;
}

function readIdlErrors(): IdlError[] {
  let raw: string;
  try {
    raw = readFileSync(IDL_PATH, "utf8");
  } catch (err) {
    console.error(
      `[drift-check] FAIL: cannot read IDL at ${IDL_PATH}\n` +
        `  Did you run \`anchor build --no-idl && git checkout -- target/idl\`?\n` +
        `  Underlying: ${(err as Error).message}`,
    );
    process.exit(2);
  }

  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    console.error(
      `[drift-check] FAIL: IDL is not valid JSON: ${(err as Error).message}`,
    );
    process.exit(2);
  }

  const errors = (json as { errors?: unknown }).errors;
  if (!Array.isArray(errors)) {
    console.error(
      `[drift-check] FAIL: IDL has no \`errors\` array — regenerate via Anchor build.`,
    );
    process.exit(2);
  }

  return errors as IdlError[];
}

/**
 * Extract `{ name: code }` pairs from the TypeScript map.
 *
 * Parses lines of the form `  VaultNotActive: 6000,` inside the
 * `SIGIL_ERRORS = { ... } as const;` object. Deliberately simple —
 * the file is autogenerated so the shape is stable.
 */
function readTsMap(path: string = TS_PATH): {
  entries: Map<string, { code: number; line: number }>;
  lineCount: number;
} {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    console.error(
      `[drift-check] FAIL: cannot read TS map at ${path}\n` +
        `  Underlying: ${(err as Error).message}`,
    );
    process.exit(2);
  }

  const lines = raw.split("\n");
  const entries = new Map<string, { code: number; line: number }>();

  let inSigilBlock = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.includes("export const SIGIL_ERRORS")) {
      inSigilBlock = true;
      continue;
    }
    if (inSigilBlock && line.trim().startsWith("}")) {
      break;
    }
    if (!inSigilBlock) continue;

    const match = line.match(/^\s*(\w+):\s*(\d+),/);
    if (match) {
      entries.set(match[1], { code: Number(match[2]), line: i + 1 });
    }
  }

  return { entries, lineCount: lines.length };
}

function main(): void {
  const idlErrors = readIdlErrors();
  const { entries: tsEntries } = readTsMap();

  const idlByName = new Map<string, number>();
  const idlCodeDupes = new Map<number, string[]>();
  for (const e of idlErrors) {
    idlByName.set(e.name, e.code);
    const existing = idlCodeDupes.get(e.code) ?? [];
    existing.push(e.name);
    idlCodeDupes.set(e.code, existing);
  }

  const tsCodeDupes = new Map<number, string[]>();
  for (const [name, { code }] of tsEntries) {
    const existing = tsCodeDupes.get(code) ?? [];
    existing.push(name);
    tsCodeDupes.set(code, existing);
  }

  const missingInTs: string[] = [];
  const staleInTs: string[] = [];
  const codeMismatch: string[] = [];

  for (const [name, code] of idlByName) {
    const tsEntry = tsEntries.get(name);
    if (!tsEntry) {
      missingInTs.push(`${name} (${code})`);
      continue;
    }
    if (tsEntry.code !== code) {
      codeMismatch.push(
        `${name}: IDL says ${code}, TS says ${tsEntry.code} (${TS_PATH}:${tsEntry.line})`,
      );
    }
  }

  for (const [name, { code, line }] of tsEntries) {
    if (!idlByName.has(name)) {
      staleInTs.push(`${name} (${code}) at ${TS_PATH}:${line}`);
    }
  }

  const idlDupeNames: string[] = [];
  for (const [code, names] of idlCodeDupes) {
    if (names.length > 1) {
      idlDupeNames.push(
        `IDL code ${code} maps to multiple names: ${names.join(", ")}`,
      );
    }
  }

  const tsDupeNames: string[] = [];
  for (const [code, names] of tsCodeDupes) {
    if (names.length > 1) {
      tsDupeNames.push(
        `TS code ${code} maps to multiple names: ${names.join(", ")}`,
      );
    }
  }

  const issues =
    missingInTs.length +
    staleInTs.length +
    codeMismatch.length +
    idlDupeNames.length +
    tsDupeNames.length;

  // Also verify the LiteSVM shim is in sync with the generated map.
  const { entries: shimEntries } = readTsMap(SHIM_PATH);
  const shimMissing: string[] = [];
  const shimMismatch: string[] = [];
  for (const [name, { code }] of tsEntries) {
    const shimEntry = shimEntries.get(name);
    if (!shimEntry) {
      shimMissing.push(`${name} (${code})`);
    } else if (shimEntry.code !== code) {
      shimMismatch.push(
        `${name}: generated says ${code}, shim says ${shimEntry.code} (${SHIM_PATH}:${shimEntry.line})`,
      );
    }
  }
  const shimStale: string[] = [];
  for (const [name, { code, line }] of shimEntries) {
    if (!tsEntries.has(name)) {
      shimStale.push(`${name} (${code}) at ${SHIM_PATH}:${line}`);
    }
  }
  const shimIssues =
    shimMissing.length + shimMismatch.length + shimStale.length;

  if (issues === 0 && shimIssues === 0) {
    console.log(
      `[drift-check] OK: ${idlByName.size} Sigil errors match across ` +
        `IDL, generated TS, and LiteSVM shim.`,
    );
    process.exit(0);
  }

  console.error(`[drift-check] FAIL: Rust IDL ↔ TypeScript error map mismatch`);
  if (missingInTs.length) {
    console.error(`\n  Missing in SIGIL_ERRORS (ts):`);
    for (const m of missingInTs) console.error(`    - ${m}`);
  }
  if (staleInTs.length) {
    console.error(`\n  Stale in SIGIL_ERRORS (ts) — not in IDL:`);
    for (const s of staleInTs) console.error(`    - ${s}`);
  }
  if (codeMismatch.length) {
    console.error(`\n  Code mismatch:`);
    for (const c of codeMismatch) console.error(`    - ${c}`);
  }
  if (idlDupeNames.length) {
    console.error(`\n  Duplicates in IDL:`);
    for (const d of idlDupeNames) console.error(`    - ${d}`);
  }
  if (tsDupeNames.length) {
    console.error(`\n  Duplicates in TS:`);
    for (const d of tsDupeNames) console.error(`    - ${d}`);
  }
  if (shimMissing.length) {
    console.error(`\n  Missing in LiteSVM shim SIGIL_ERRORS:`);
    for (const m of shimMissing) console.error(`    - ${m}`);
  }
  if (shimStale.length) {
    console.error(`\n  Stale in LiteSVM shim — no longer in generated:`);
    for (const s of shimStale) console.error(`    - ${s}`);
  }
  if (shimMismatch.length) {
    console.error(`\n  Generated ↔ LiteSVM shim mismatch:`);
    for (const m of shimMismatch) console.error(`    - ${m}`);
  }
  console.error(
    `\n  Fix: regenerate via \`pnpm run gen:error-types\` (updates ` +
      `${TS_PATH}), then copy the SIGIL_ERRORS block into ${SHIM_PATH} ` +
      `by hand.`,
  );
  console.error(
    `\n  Source anchors: ${IDL_PATH} (IDL) ↔ ${TS_PATH} (generated) ` +
      `↔ ${SHIM_PATH} (shim).`,
  );

  process.exit(1);
}

main();
