/**
 * Anchor CPI event log parser for Sigil.
 *
 * Parses "Program data: " log lines from transaction logs to extract
 * Anchor events. Uses the IDL-provided event discriminators (first 8 bytes
 * of SHA256 of "event:<EventName>").
 *
 * The discriminator map is auto-generated by codama.mjs from the IDL.
 * Run `pnpm run codama` after any Rust event changes.
 */

import { EVENT_DISCRIMINATOR_MAP } from "./generated/event-discriminators.js";
import {
  getActionAuthorizedDecoder,
  getSessionFinalizedDecoder,
  getFeesCollectedDecoder,
  getFundsDepositedDecoder,
  getFundsWithdrawnDecoder,
  getAgentTransferExecutedDecoder,
  getVaultCreatedDecoder,
  getVaultFrozenDecoder,
  getVaultReactivatedDecoder,
  getVaultClosedDecoder,
  getAgentRegisteredDecoder,
  getAgentRevokedDecoder,
  getAgentPausedEventDecoder,
  getAgentUnpausedEventDecoder,
  getAgentSpendLimitCheckedDecoder,
  getEscrowCreatedDecoder,
  getEscrowSettledDecoder,
  getEscrowRefundedDecoder,
  getPolicyChangeQueuedDecoder,
  getPolicyChangeAppliedDecoder,
  getPolicyChangeCancelledDecoder,
  getConstraintsChangeQueuedDecoder,
  getConstraintsChangeAppliedDecoder,
  getConstraintsChangeCancelledDecoder,
  getInstructionConstraintsCreatedDecoder,
  getAgentPermissionsChangeQueuedDecoder,
  getAgentPermissionsChangeAppliedDecoder,
  getAgentPermissionsChangeCancelledDecoder,
  getCloseConstraintsQueuedDecoder,
  getCloseConstraintsAppliedDecoder,
  getCloseConstraintsCancelledDecoder,
  getDelegationRevokedDecoder,
  getPositionsSyncedDecoder,
  getPdaAllocatedDecoder,
  getPdaExtendedDecoder,
  getPostAssertionCheckedDecoder,
  getPostAssertionsCreatedDecoder,
  getPostAssertionsClosedDecoder,
} from "./generated/types/index.js";

/** All known Sigil event names */
export type SigilEventName = (typeof EVENT_DISCRIMINATOR_MAP)[string];

/** Parsed event from transaction logs */
export interface SigilEvent {
  /** Event name (e.g. "VaultCreated", "ActionAuthorized") */
  name: SigilEventName;
  /** Raw event data bytes (after discriminator) */
  data: Uint8Array;
}

/**
 * Parse Sigil Anchor events from transaction logs.
 *
 * Anchor emits events as "Program data: <base64>" log lines.
 * The first 8 bytes are the event discriminator (SHA256 prefix).
 *
 * @param logs - Array of log strings from a transaction
 * @returns Array of parsed events with name and raw data
 */
export function parseSigilEvents(logs: string[]): SigilEvent[] {
  const events: SigilEvent[] = [];
  const PROGRAM_DATA_PREFIX = "Program data: ";

  for (const log of logs) {
    if (!log.includes(PROGRAM_DATA_PREFIX)) continue;

    const dataStart = log.indexOf(PROGRAM_DATA_PREFIX);
    if (dataStart === -1) continue;

    const base64Data = log.slice(dataStart + PROGRAM_DATA_PREFIX.length);

    try {
      const bytes = base64ToBytes(base64Data);
      if (bytes.length < 8) continue;

      // First 8 bytes = discriminator
      const discHex = bytesToHex(bytes.slice(0, 8));
      const eventName = EVENT_DISCRIMINATOR_MAP[discHex];

      if (eventName) {
        events.push({
          name: eventName,
          data: bytes.slice(8),
        });
      }
    } catch {
      // Skip unparseable log lines
    }
  }

  return events;
}

/**
 * Extract events of a specific type from transaction logs.
 */
export function filterEvents(
  logs: string[],
  eventName: SigilEventName,
): SigilEvent[] {
  return parseSigilEvents(logs).filter((e) => e.name === eventName);
}

/** Get all known event names */
export function getEventNames(): SigilEventName[] {
  return Object.values(EVENT_DISCRIMINATOR_MAP);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function base64ToBytes(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ─── Event Decoder Map ──────────────────────────────────────────────────────

// Decoders cached at module level — avoids re-creating struct decoders on every call
const EVENT_DECODER_MAP: Record<
  string,
  { decode: (data: Uint8Array) => unknown }
> = {
  ActionAuthorized: getActionAuthorizedDecoder(),
  SessionFinalized: getSessionFinalizedDecoder(),
  FeesCollected: getFeesCollectedDecoder(),
  FundsDeposited: getFundsDepositedDecoder(),
  FundsWithdrawn: getFundsWithdrawnDecoder(),
  AgentTransferExecuted: getAgentTransferExecutedDecoder(),
  VaultCreated: getVaultCreatedDecoder(),
  VaultFrozen: getVaultFrozenDecoder(),
  VaultReactivated: getVaultReactivatedDecoder(),
  VaultClosed: getVaultClosedDecoder(),
  AgentRegistered: getAgentRegisteredDecoder(),
  AgentRevoked: getAgentRevokedDecoder(),
  AgentPausedEvent: getAgentPausedEventDecoder(),
  AgentUnpausedEvent: getAgentUnpausedEventDecoder(),
  AgentSpendLimitChecked: getAgentSpendLimitCheckedDecoder(),
  EscrowCreated: getEscrowCreatedDecoder(),
  EscrowSettled: getEscrowSettledDecoder(),
  EscrowRefunded: getEscrowRefundedDecoder(),
  PolicyChangeQueued: getPolicyChangeQueuedDecoder(),
  PolicyChangeApplied: getPolicyChangeAppliedDecoder(),
  PolicyChangeCancelled: getPolicyChangeCancelledDecoder(),
  ConstraintsChangeQueued: getConstraintsChangeQueuedDecoder(),
  ConstraintsChangeApplied: getConstraintsChangeAppliedDecoder(),
  ConstraintsChangeCancelled: getConstraintsChangeCancelledDecoder(),
  InstructionConstraintsCreated: getInstructionConstraintsCreatedDecoder(),
  AgentPermissionsChangeQueued: getAgentPermissionsChangeQueuedDecoder(),
  AgentPermissionsChangeApplied: getAgentPermissionsChangeAppliedDecoder(),
  AgentPermissionsChangeCancelled: getAgentPermissionsChangeCancelledDecoder(),
  CloseConstraintsQueued: getCloseConstraintsQueuedDecoder(),
  CloseConstraintsApplied: getCloseConstraintsAppliedDecoder(),
  CloseConstraintsCancelled: getCloseConstraintsCancelledDecoder(),
  DelegationRevoked: getDelegationRevokedDecoder(),
  PositionsSynced: getPositionsSyncedDecoder(),
  PdaAllocated: getPdaAllocatedDecoder(),
  PdaExtended: getPdaExtendedDecoder(),
  PostAssertionChecked: getPostAssertionCheckedDecoder(),
  PostAssertionsCreated: getPostAssertionsCreatedDecoder(),
  PostAssertionsClosed: getPostAssertionsClosedDecoder(),
};

// Validate decoder map completeness at module init — catches drift when events are added/removed
const discriminatorEventNames = new Set(Object.values(EVENT_DISCRIMINATOR_MAP));
const decoderEventNames = new Set(Object.keys(EVENT_DECODER_MAP));
for (const name of discriminatorEventNames) {
  if (!decoderEventNames.has(name)) {
    throw new Error(
      `EVENT_DECODER_MAP missing entry for "${name}". ` +
        `Update EVENT_DECODER_MAP in events.ts after adding new events.`,
    );
  }
}
for (const name of decoderEventNames) {
  if (!discriminatorEventNames.has(name)) {
    throw new Error(
      `EVENT_DECODER_MAP has stale entry "${name}" not in EVENT_DISCRIMINATOR_MAP. ` +
        `Remove it from EVENT_DECODER_MAP in events.ts.`,
    );
  }
}

// ─── Event Decoding ─────────────────────────────────────────────────────────

/** Decoded event with typed fields */
export interface DecodedSigilEvent {
  name: SigilEventName;
  /** Raw bytes preserved for debugging */
  data: Uint8Array;
  /** Decoded fields, or null if decoding fails */
  fields: Record<string, unknown> | null;
}

/**
 * Decode a parsed Sigil event's raw bytes into typed fields.
 *
 * Returns `fields: null` if the event name is unknown or decoding fails
 * (e.g. events from older program versions with different layouts).
 */
export function decodeSigilEvent(event: SigilEvent): DecodedSigilEvent {
  const decoder = EVENT_DECODER_MAP[event.name];
  if (!decoder) {
    return { name: event.name, data: event.data, fields: null };
  }
  try {
    const fields = decoder.decode(event.data) as Record<string, unknown>;
    return { name: event.name, data: event.data, fields };
  } catch {
    return { name: event.name, data: event.data, fields: null };
  }
}

/**
 * Parse and decode Sigil events from transaction logs in one step.
 */
export function parseAndDecodeSigilEvents(logs: string[]): DecodedSigilEvent[] {
  return parseSigilEvents(logs).map(decodeSigilEvent);
}
