/**
 * Kit Adapter Barrel — single-file @solana/kit import surface.
 *
 * PR 2.C (H11-KITADAPT): All SDK source files import from this barrel
 * instead of directly from `@solana/kit`. When Kit ships a major version
 * (v7, v8) or Anchor migrates to a new Codama output, the migration diff
 * is confined to this one file + the generated code — not 52 files across
 * the SDK.
 *
 * Rules:
 *   1. Only THIS file imports from `@solana/kit` (and `@solana/errors` for
 *      the typed-error predicates added in PR 1.B).
 *   2. All other `sdk/kit/src/**` files import from `./kit-adapter.js`
 *      (or the appropriate relative path `../kit-adapter.js` etc.).
 *   3. Test files (`tests/**`) MAY import directly from `@solana/kit` —
 *      they are not shipped and don't affect migration surface.
 *   4. Generated files (`src/generated/**`) import from `@solana/kit`
 *      directly — they are regenerated by Codama, not hand-maintained.
 *
 * Add new symbols here as needed. If Kit renames or removes one, fix it
 * here once and the entire SDK compiles.
 */

// ─── Type re-exports (tree-shake safe — type-only) ──────────────────────────
export type {
  Address,
  AddressesByLookupTableAddress,
  Base64EncodedBytes,
  Base64EncodedWireTransaction,
  Commitment,
  Instruction,
  KeyPairSigner,
  ReadonlyUint8Array,
  Rpc,
  SolanaRpcApi,
  TransactionSigner,
} from "@solana/kit";

// ─── Value re-exports (tree-shake safe — named exports) ─────────────────────
export {
  AccountRole,
  addSignersToTransactionMessage,
  appendTransactionMessageInstruction,
  appendTransactionMessageInstructions,
  compileTransaction,
  compressTransactionMessageUsingAddressLookupTables,
  createKeyPairSignerFromBytes,
  createNoopSigner,
  createSolanaRpc,
  createTransactionMessage,
  fetchAddressesForLookupTables,
  fetchEncodedAccounts,
  generateKeyPairSigner,
  getAddressDecoder,
  getAddressEncoder,
  getBase58Decoder,
  getBase64EncodedWireTransaction,
  getCompiledTransactionMessageDecoder,
  getProgramDerivedAddress,
  getU64Decoder,
  isSome,
  pipe,
  setTransactionMessageFeePayer,
  setTransactionMessageLifetimeUsingBlockhash,
  signTransactionMessageWithSigners,
} from "@solana/kit";
