/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getOraclePriceDecoder,
  getOraclePriceEncoder,
  type OraclePrice,
  type OraclePriceArgs,
} from "./index.js";

export type ClosePositionQuoteData = {
  receiveTokenAmount: bigint;
  receiveTokenAmountUsd: bigint;
  markPrice: OraclePrice;
  entryPrice: OraclePrice;
  existingLiquidationPrice: OraclePrice;
  newLiquidationPrice: OraclePrice;
  existingSize: bigint;
  newSize: bigint;
  existingCollateral: bigint;
  newCollateral: bigint;
  existingLeverage: bigint;
  newLeverage: bigint;
  settledPnlUsd: bigint;
  isProfitable: boolean;
  profitUsd: bigint;
  lossUsd: bigint;
  fees: bigint;
  feesBeforeDiscount: bigint;
  exitFeeUsd: bigint;
  exitFeeBeforeDiscountUsd: bigint;
  lockAndUnsettledFeeUsd: bigint;
  priceImpactUsd: bigint;
  isSolvent: boolean;
  swapRequired: boolean;
  swapPossible: boolean;
  isPartialClose: boolean;
};

export type ClosePositionQuoteDataArgs = {
  receiveTokenAmount: number | bigint;
  receiveTokenAmountUsd: number | bigint;
  markPrice: OraclePriceArgs;
  entryPrice: OraclePriceArgs;
  existingLiquidationPrice: OraclePriceArgs;
  newLiquidationPrice: OraclePriceArgs;
  existingSize: number | bigint;
  newSize: number | bigint;
  existingCollateral: number | bigint;
  newCollateral: number | bigint;
  existingLeverage: number | bigint;
  newLeverage: number | bigint;
  settledPnlUsd: number | bigint;
  isProfitable: boolean;
  profitUsd: number | bigint;
  lossUsd: number | bigint;
  fees: number | bigint;
  feesBeforeDiscount: number | bigint;
  exitFeeUsd: number | bigint;
  exitFeeBeforeDiscountUsd: number | bigint;
  lockAndUnsettledFeeUsd: number | bigint;
  priceImpactUsd: number | bigint;
  isSolvent: boolean;
  swapRequired: boolean;
  swapPossible: boolean;
  isPartialClose: boolean;
};

export function getClosePositionQuoteDataEncoder(): FixedSizeEncoder<ClosePositionQuoteDataArgs> {
  return getStructEncoder([
    ["receiveTokenAmount", getU64Encoder()],
    ["receiveTokenAmountUsd", getU64Encoder()],
    ["markPrice", getOraclePriceEncoder()],
    ["entryPrice", getOraclePriceEncoder()],
    ["existingLiquidationPrice", getOraclePriceEncoder()],
    ["newLiquidationPrice", getOraclePriceEncoder()],
    ["existingSize", getU64Encoder()],
    ["newSize", getU64Encoder()],
    ["existingCollateral", getU64Encoder()],
    ["newCollateral", getU64Encoder()],
    ["existingLeverage", getU64Encoder()],
    ["newLeverage", getU64Encoder()],
    ["settledPnlUsd", getU64Encoder()],
    ["isProfitable", getBooleanEncoder()],
    ["profitUsd", getU64Encoder()],
    ["lossUsd", getU64Encoder()],
    ["fees", getU64Encoder()],
    ["feesBeforeDiscount", getU64Encoder()],
    ["exitFeeUsd", getU64Encoder()],
    ["exitFeeBeforeDiscountUsd", getU64Encoder()],
    ["lockAndUnsettledFeeUsd", getU64Encoder()],
    ["priceImpactUsd", getU64Encoder()],
    ["isSolvent", getBooleanEncoder()],
    ["swapRequired", getBooleanEncoder()],
    ["swapPossible", getBooleanEncoder()],
    ["isPartialClose", getBooleanEncoder()],
  ]);
}

export function getClosePositionQuoteDataDecoder(): FixedSizeDecoder<ClosePositionQuoteData> {
  return getStructDecoder([
    ["receiveTokenAmount", getU64Decoder()],
    ["receiveTokenAmountUsd", getU64Decoder()],
    ["markPrice", getOraclePriceDecoder()],
    ["entryPrice", getOraclePriceDecoder()],
    ["existingLiquidationPrice", getOraclePriceDecoder()],
    ["newLiquidationPrice", getOraclePriceDecoder()],
    ["existingSize", getU64Decoder()],
    ["newSize", getU64Decoder()],
    ["existingCollateral", getU64Decoder()],
    ["newCollateral", getU64Decoder()],
    ["existingLeverage", getU64Decoder()],
    ["newLeverage", getU64Decoder()],
    ["settledPnlUsd", getU64Decoder()],
    ["isProfitable", getBooleanDecoder()],
    ["profitUsd", getU64Decoder()],
    ["lossUsd", getU64Decoder()],
    ["fees", getU64Decoder()],
    ["feesBeforeDiscount", getU64Decoder()],
    ["exitFeeUsd", getU64Decoder()],
    ["exitFeeBeforeDiscountUsd", getU64Decoder()],
    ["lockAndUnsettledFeeUsd", getU64Decoder()],
    ["priceImpactUsd", getU64Decoder()],
    ["isSolvent", getBooleanDecoder()],
    ["swapRequired", getBooleanDecoder()],
    ["swapPossible", getBooleanDecoder()],
    ["isPartialClose", getBooleanDecoder()],
  ]);
}

export function getClosePositionQuoteDataCodec(): FixedSizeCodec<
  ClosePositionQuoteDataArgs,
  ClosePositionQuoteData
> {
  return combineCodec(
    getClosePositionQuoteDataEncoder(),
    getClosePositionQuoteDataDecoder(),
  );
}
