/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type CompoundingStats = {
  activeAmount: bigint;
  totalSupply: bigint;
  rewardSnapshot: bigint;
  feeShareBps: bigint;
  lastCompoundTime: bigint;
};

export type CompoundingStatsArgs = {
  activeAmount: number | bigint;
  totalSupply: number | bigint;
  rewardSnapshot: number | bigint;
  feeShareBps: number | bigint;
  lastCompoundTime: number | bigint;
};

export function getCompoundingStatsEncoder(): FixedSizeEncoder<CompoundingStatsArgs> {
  return getStructEncoder([
    ["activeAmount", getU64Encoder()],
    ["totalSupply", getU64Encoder()],
    ["rewardSnapshot", getU128Encoder()],
    ["feeShareBps", getU64Encoder()],
    ["lastCompoundTime", getI64Encoder()],
  ]);
}

export function getCompoundingStatsDecoder(): FixedSizeDecoder<CompoundingStats> {
  return getStructDecoder([
    ["activeAmount", getU64Decoder()],
    ["totalSupply", getU64Decoder()],
    ["rewardSnapshot", getU128Decoder()],
    ["feeShareBps", getU64Decoder()],
    ["lastCompoundTime", getI64Decoder()],
  ]);
}

export function getCompoundingStatsCodec(): FixedSizeCodec<
  CompoundingStatsArgs,
  CompoundingStats
> {
  return combineCodec(
    getCompoundingStatsEncoder(),
    getCompoundingStatsDecoder(),
  );
}
