/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum Privilege {
  None,
  Stake,
  Referral,
}

export type PrivilegeArgs = Privilege;

export function getPrivilegeEncoder(): FixedSizeEncoder<PrivilegeArgs> {
  return getEnumEncoder(Privilege);
}

export function getPrivilegeDecoder(): FixedSizeDecoder<Privilege> {
  return getEnumDecoder(Privilege);
}

export function getPrivilegeCodec(): FixedSizeCodec<PrivilegeArgs, Privilege> {
  return combineCodec(getPrivilegeEncoder(), getPrivilegeDecoder());
}
