/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type RemoveCompoundingLiquidityLog = {
  poolName: string;
  owner: Address;
  custodyUid: bigint;
  compoundingAmountIn: bigint;
  amountOut: bigint;
  feeAmount: bigint;
  rewardPerLpStaked: bigint;
  compoundingPriceUsd: bigint;
  tokenOutPrice: bigint;
  tokenOutPriceExponent: number;
};

export type RemoveCompoundingLiquidityLogArgs = {
  poolName: string;
  owner: Address;
  custodyUid: number | bigint;
  compoundingAmountIn: number | bigint;
  amountOut: number | bigint;
  feeAmount: number | bigint;
  rewardPerLpStaked: number | bigint;
  compoundingPriceUsd: number | bigint;
  tokenOutPrice: number | bigint;
  tokenOutPriceExponent: number;
};

export function getRemoveCompoundingLiquidityLogEncoder(): Encoder<RemoveCompoundingLiquidityLogArgs> {
  return getStructEncoder([
    ["poolName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["owner", getAddressEncoder()],
    ["custodyUid", getU64Encoder()],
    ["compoundingAmountIn", getU64Encoder()],
    ["amountOut", getU64Encoder()],
    ["feeAmount", getU64Encoder()],
    ["rewardPerLpStaked", getU64Encoder()],
    ["compoundingPriceUsd", getU64Encoder()],
    ["tokenOutPrice", getU64Encoder()],
    ["tokenOutPriceExponent", getI32Encoder()],
  ]);
}

export function getRemoveCompoundingLiquidityLogDecoder(): Decoder<RemoveCompoundingLiquidityLog> {
  return getStructDecoder([
    ["poolName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["owner", getAddressDecoder()],
    ["custodyUid", getU64Decoder()],
    ["compoundingAmountIn", getU64Decoder()],
    ["amountOut", getU64Decoder()],
    ["feeAmount", getU64Decoder()],
    ["rewardPerLpStaked", getU64Decoder()],
    ["compoundingPriceUsd", getU64Decoder()],
    ["tokenOutPrice", getU64Decoder()],
    ["tokenOutPriceExponent", getI32Decoder()],
  ]);
}

export function getRemoveCompoundingLiquidityLogCodec(): Codec<
  RemoveCompoundingLiquidityLogArgs,
  RemoveCompoundingLiquidityLog
> {
  return combineCodec(
    getRemoveCompoundingLiquidityLogEncoder(),
    getRemoveCompoundingLiquidityLogDecoder(),
  );
}
