/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RemoveCollateralLogV3 = {
  owner: Address;
  market: Address;
  collateralPrice: bigint;
  collateralPriceExponent: number;
  deltaCollateralAmount: bigint;
  finalCollateralAmount: bigint;
  finalCollateralUsd: bigint;
  finalSizeAmount: bigint;
  finalSizeUsd: bigint;
  oracleAccountTime: bigint;
  oracleAccountType: number;
  oracleAccountPrice: bigint;
  oracleAccountPriceExponent: number;
};

export type RemoveCollateralLogV3Args = {
  owner: Address;
  market: Address;
  collateralPrice: number | bigint;
  collateralPriceExponent: number;
  deltaCollateralAmount: number | bigint;
  finalCollateralAmount: number | bigint;
  finalCollateralUsd: number | bigint;
  finalSizeAmount: number | bigint;
  finalSizeUsd: number | bigint;
  oracleAccountTime: number | bigint;
  oracleAccountType: number;
  oracleAccountPrice: number | bigint;
  oracleAccountPriceExponent: number;
};

export function getRemoveCollateralLogV3Encoder(): FixedSizeEncoder<RemoveCollateralLogV3Args> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["market", getAddressEncoder()],
    ["collateralPrice", getU64Encoder()],
    ["collateralPriceExponent", getI32Encoder()],
    ["deltaCollateralAmount", getU64Encoder()],
    ["finalCollateralAmount", getU64Encoder()],
    ["finalCollateralUsd", getU64Encoder()],
    ["finalSizeAmount", getU64Encoder()],
    ["finalSizeUsd", getU64Encoder()],
    ["oracleAccountTime", getI64Encoder()],
    ["oracleAccountType", getU8Encoder()],
    ["oracleAccountPrice", getU64Encoder()],
    ["oracleAccountPriceExponent", getI32Encoder()],
  ]);
}

export function getRemoveCollateralLogV3Decoder(): FixedSizeDecoder<RemoveCollateralLogV3> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["collateralPrice", getU64Decoder()],
    ["collateralPriceExponent", getI32Decoder()],
    ["deltaCollateralAmount", getU64Decoder()],
    ["finalCollateralAmount", getU64Decoder()],
    ["finalCollateralUsd", getU64Decoder()],
    ["finalSizeAmount", getU64Decoder()],
    ["finalSizeUsd", getU64Decoder()],
    ["oracleAccountTime", getI64Decoder()],
    ["oracleAccountType", getU8Decoder()],
    ["oracleAccountPrice", getU64Decoder()],
    ["oracleAccountPriceExponent", getI32Decoder()],
  ]);
}

export function getRemoveCollateralLogV3Codec(): FixedSizeCodec<
  RemoveCollateralLogV3Args,
  RemoveCollateralLogV3
> {
  return combineCodec(
    getRemoveCollateralLogV3Encoder(),
    getRemoveCollateralLogV3Decoder(),
  );
}
