/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type SwapAndOpenLog = {
  poolName: string;
  owner: Address;
  receivingCustodyUid: bigint;
  collateralCustodyUid: bigint;
  targetCustodyUid: bigint;
  amountIn: bigint;
  swapAmountOut: bigint;
  swapFeeAmount: bigint;
  market: Address;
  entryPrice: bigint;
  entryPriceExponent: number;
  sizeAmount: bigint;
  sizeUsd: bigint;
  collateralPrice: bigint;
  collateralPriceExponent: number;
  collateralAmount: bigint;
  collateralUsd: bigint;
  positionFeeAmount: bigint;
  feeRebateAmount: bigint;
  receivingOracleAccountTime: bigint;
  receivingOracleAccountType: number;
  receivingOracleAccountPrice: bigint;
  receivingOracleAccountPriceExponent: number;
  collateralOracleAccountTime: bigint;
  collateralOracleAccountType: number;
  collateralOracleAccountPrice: bigint;
  collateralOracleAccountPriceExponent: number;
  targetOracleAccountTime: bigint;
  targetOracleAccountType: number;
  targetOracleAccountPrice: bigint;
  targetOracleAccountPriceExponent: number;
};

export type SwapAndOpenLogArgs = {
  poolName: string;
  owner: Address;
  receivingCustodyUid: number | bigint;
  collateralCustodyUid: number | bigint;
  targetCustodyUid: number | bigint;
  amountIn: number | bigint;
  swapAmountOut: number | bigint;
  swapFeeAmount: number | bigint;
  market: Address;
  entryPrice: number | bigint;
  entryPriceExponent: number;
  sizeAmount: number | bigint;
  sizeUsd: number | bigint;
  collateralPrice: number | bigint;
  collateralPriceExponent: number;
  collateralAmount: number | bigint;
  collateralUsd: number | bigint;
  positionFeeAmount: number | bigint;
  feeRebateAmount: number | bigint;
  receivingOracleAccountTime: number | bigint;
  receivingOracleAccountType: number;
  receivingOracleAccountPrice: number | bigint;
  receivingOracleAccountPriceExponent: number;
  collateralOracleAccountTime: number | bigint;
  collateralOracleAccountType: number;
  collateralOracleAccountPrice: number | bigint;
  collateralOracleAccountPriceExponent: number;
  targetOracleAccountTime: number | bigint;
  targetOracleAccountType: number;
  targetOracleAccountPrice: number | bigint;
  targetOracleAccountPriceExponent: number;
};

export function getSwapAndOpenLogEncoder(): Encoder<SwapAndOpenLogArgs> {
  return getStructEncoder([
    ["poolName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["owner", getAddressEncoder()],
    ["receivingCustodyUid", getU64Encoder()],
    ["collateralCustodyUid", getU64Encoder()],
    ["targetCustodyUid", getU64Encoder()],
    ["amountIn", getU64Encoder()],
    ["swapAmountOut", getU64Encoder()],
    ["swapFeeAmount", getU64Encoder()],
    ["market", getAddressEncoder()],
    ["entryPrice", getU64Encoder()],
    ["entryPriceExponent", getI32Encoder()],
    ["sizeAmount", getU64Encoder()],
    ["sizeUsd", getU64Encoder()],
    ["collateralPrice", getU64Encoder()],
    ["collateralPriceExponent", getI32Encoder()],
    ["collateralAmount", getU64Encoder()],
    ["collateralUsd", getU64Encoder()],
    ["positionFeeAmount", getU64Encoder()],
    ["feeRebateAmount", getU64Encoder()],
    ["receivingOracleAccountTime", getI64Encoder()],
    ["receivingOracleAccountType", getU8Encoder()],
    ["receivingOracleAccountPrice", getU64Encoder()],
    ["receivingOracleAccountPriceExponent", getI32Encoder()],
    ["collateralOracleAccountTime", getI64Encoder()],
    ["collateralOracleAccountType", getU8Encoder()],
    ["collateralOracleAccountPrice", getU64Encoder()],
    ["collateralOracleAccountPriceExponent", getI32Encoder()],
    ["targetOracleAccountTime", getI64Encoder()],
    ["targetOracleAccountType", getU8Encoder()],
    ["targetOracleAccountPrice", getU64Encoder()],
    ["targetOracleAccountPriceExponent", getI32Encoder()],
  ]);
}

export function getSwapAndOpenLogDecoder(): Decoder<SwapAndOpenLog> {
  return getStructDecoder([
    ["poolName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["owner", getAddressDecoder()],
    ["receivingCustodyUid", getU64Decoder()],
    ["collateralCustodyUid", getU64Decoder()],
    ["targetCustodyUid", getU64Decoder()],
    ["amountIn", getU64Decoder()],
    ["swapAmountOut", getU64Decoder()],
    ["swapFeeAmount", getU64Decoder()],
    ["market", getAddressDecoder()],
    ["entryPrice", getU64Decoder()],
    ["entryPriceExponent", getI32Decoder()],
    ["sizeAmount", getU64Decoder()],
    ["sizeUsd", getU64Decoder()],
    ["collateralPrice", getU64Decoder()],
    ["collateralPriceExponent", getI32Decoder()],
    ["collateralAmount", getU64Decoder()],
    ["collateralUsd", getU64Decoder()],
    ["positionFeeAmount", getU64Decoder()],
    ["feeRebateAmount", getU64Decoder()],
    ["receivingOracleAccountTime", getI64Decoder()],
    ["receivingOracleAccountType", getU8Decoder()],
    ["receivingOracleAccountPrice", getU64Decoder()],
    ["receivingOracleAccountPriceExponent", getI32Decoder()],
    ["collateralOracleAccountTime", getI64Decoder()],
    ["collateralOracleAccountType", getU8Decoder()],
    ["collateralOracleAccountPrice", getU64Decoder()],
    ["collateralOracleAccountPriceExponent", getI32Decoder()],
    ["targetOracleAccountTime", getI64Decoder()],
    ["targetOracleAccountType", getU8Decoder()],
    ["targetOracleAccountPrice", getU64Decoder()],
    ["targetOracleAccountPriceExponent", getI32Decoder()],
  ]);
}

export function getSwapAndOpenLogCodec(): Codec<
  SwapAndOpenLogArgs,
  SwapAndOpenLog
> {
  return combineCodec(getSwapAndOpenLogEncoder(), getSwapAndOpenLogDecoder());
}
