/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokenRatios = { target: bigint; min: bigint; max: bigint };

export type TokenRatiosArgs = {
  target: number | bigint;
  min: number | bigint;
  max: number | bigint;
};

export function getTokenRatiosEncoder(): FixedSizeEncoder<TokenRatiosArgs> {
  return getStructEncoder([
    ["target", getU64Encoder()],
    ["min", getU64Encoder()],
    ["max", getU64Encoder()],
  ]);
}

export function getTokenRatiosDecoder(): FixedSizeDecoder<TokenRatios> {
  return getStructDecoder([
    ["target", getU64Decoder()],
    ["min", getU64Decoder()],
    ["max", getU64Decoder()],
  ]);
}

export function getTokenRatiosCodec(): FixedSizeCodec<
  TokenRatiosArgs,
  TokenRatios
> {
  return combineCodec(getTokenRatiosEncoder(), getTokenRatiosDecoder());
}
