/**
 * Constraint Builder Type Definitions
 *
 * Target types for the add-protocol pipeline generators.
 * Generated schema/descriptor files import from "../types.js".
 *
 * Constraint primitives (ConstraintOperator, DataConstraintArgs,
 * AccountConstraintArgs, ConstraintEntryArgs) are Codama-generated
 * and must NOT be redeclared here — import from generated/index.js.
 *
 * Three protocol tiers:
 * - Verified: pipeline-generated schemas + descriptors (Tier 1)
 * - Unverified: runtime IDL fetch → parsed schemas, no descriptors (Tier 2)
 * - Incompatible: no IDL, binary allow/block with user-acknowledged warning (Tier 3)
 */

import type { Address } from "@solana/kit";
import type {
  AccountConstraintArgs,
  DataConstraintArgs,
} from "./generated/index.js";

// ─── Schema Types ───────────────────────────────────────────────────────────
// Used by Tier 1 (verified, build-time) and Tier 2 (unverified, runtime)

export type FieldType =
  | "u8"
  | "u16"
  | "u32"
  | "u64"
  | "u128"
  | "i8"
  | "i16"
  | "i32"
  | "i64"
  | "i128"
  | "pubkey"
  | "bool";

export interface SchemaField {
  readonly name: string;
  readonly offset: number;
  readonly type: FieldType;
  readonly size: number;
}

export interface InstructionSchema {
  readonly name: string;
  readonly discriminator: Uint8Array;
  readonly fields: readonly SchemaField[];
  readonly accounts: Readonly<Record<string, number>>;
  readonly dataSize: number;
}

/**
 * Schema for a protocol's instruction byte layouts.
 * Tier 1: generated at build-time by the add-protocol pipeline.
 * Tier 2: constructed at runtime from a fetched IDL.
 */
export interface ProtocolSchema {
  readonly protocolId: string;
  readonly programAddress: Address;
  readonly instructions: ReadonlyMap<string, InstructionSchema>;
}

// ─── Rule / Descriptor Types ────────────────────────────────────────────────
// Tier 1 only — generated by the add-protocol pipeline for verified protocols

/** JSON-serializable rule parameter values. No BigInt — strings are parsed to BigInt at compile time. */
export type RuleParamValue = string | number | boolean | string[];

export interface ActionRule {
  type: string;
  actions: string[];
  params: Record<string, RuleParamValue>;
}

/**
 * A compiled rule targeting one instruction, ready for assembly into
 * on-chain constraint entries. Produced by ProtocolDescriptor.compileRule().
 */
export interface CompiledConstraint {
  discriminator: Uint8Array;
  dataConstraints: DataConstraintArgs[];
  accountConstraints: AccountConstraintArgs[];
}

export type RuleParam =
  | {
      name: string;
      type: "bigint" | "number";
      label: string;
      required: boolean;
    }
  | {
      name: string;
      type: "select" | "multiselect";
      label: string;
      required: boolean;
      options: Array<{ value: string; label: string }>;
    };

export interface RuleTypeMetadata {
  type: string;
  displayName: string;
  description: string;
  applicableActions: string[];
  params: RuleParam[];
}

/**
 * Descriptor for a verified protocol (Tier 1). Generated by the add-protocol
 * pipeline. Provides rule templates and compilation for a specific DeFi program.
 * Access protocol identity via schema: descriptor.schema.protocolId.
 */
export interface ProtocolDescriptor {
  schema: ProtocolSchema;
  compileRule(rule: ActionRule): CompiledConstraint[];
  getRuleTypes(): RuleTypeMetadata[];
  validateRule(rule: ActionRule): string[];
  checkStrictModeWarnings(config: {
    actionRules: ActionRule[];
    strictMode?: boolean;
  }): string[];
}
